### ISSUE TITLE
non-alphabet characters in usernames break @name system

### ISSUE THREAD

**Issue by mathewlippincott** [publiclab/plots2#195] opened 2015-01-17 02:12 UTC
Alex-McCarthy has a dash in the username-- won't reference right.
![screen shot 2015-01-16 at 6 10 24 pm](https://cloud.githubusercontent.com/assets/1203280/5787200/2b36209a-9dab-11e4-88bd-8b8f793d0050.png)

**Comment by btbonval** [comment] 2015-01-17 02:14
duplicate of #126

**Comment by mathewlippincott** [comment] 2015-01-17 02:15
oops.  thanks @btbonval

**Closed by btbonval** 2015-01-17 02:14 UTC

**Comment by btbonval** [comment] 2015-01-17 02:17
@mathewlippincott no problem. it is hard to know what to search for, but I happened to work on the other tickets so I knew this problem was pre-existing :)
