### ISSUE TITLE
Use co-authored instead of coauthored

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5137] opened 2019-03-17 20:38 UTC
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

**Update**
co-authored would look better than coauthor.
![Selection_072](https://user-images.githubusercontent.com/32747809/54497566-0ef28000-4922-11e9-8ff8-af8bb548ff88.png)

Change need to be done:
https://github.com/publiclab/plots2/blob/6507b559b61f3228dbbd795ecbd972b6da2eabba/app/views/users/profile.html.erb#L48

Change this to 
    ```
<a href="#coauthored" class="btn btn-default" data-toggle="tab">Co-authored  <%= "(#{ @coauthored.count })" %></a>
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by An0u** [comment] 2019-03-18 01:57
I'd like to work on this

**Comment by gauravano** [comment] 2019-03-18 14:47
hey @An0u, change need to be done at  https://github.com/publiclab/plots2/blob/6507b559b61f3228dbbd795ecbd972b6da2eabba/app/views/users/profile.html.erb#L48

**Comment by PritiShaw** [comment] 2019-03-24 06:44
Can i Work on this ?? @divyabaid16

**Comment by gauravano** [comment] 2019-03-24 19:08
Hey @PritiShaw, this issue is claimed. We would love to have your help with other issues. If you're looking for FTO, we can add your name to https://github.com/publiclab/plots2/issues/4963? Thanks!

**Comment by pkayres** [comment] 2019-10-09 11:44
Hey thanks I'll take a whack at this!

**Comment by loranazarenko** [comment] 2019-10-24 21:18
Hello! Can i work with this issue?

**Comment by loranazarenko** [comment] 2019-10-25 20:15
Hello, I'm an outreachy applicant and I am looking for a FTO issue if possible. I would like to contribute to this project. Thanks.

**Comment by jywarren** [comment] 2019-11-27 15:17
This is now available again! No need to ask, folks can just leave a comment to take this up! Thanks, all!!

**Comment by MaheshPawar97** [comment] 2019-12-23 20:14
Hello, I am taking up this issue

**Comment by cesswairimu** [comment] 2020-01-01 11:14
Hi @MaheshPawar97, You still working on this? Thanks

**Comment by taysa91** [comment] 2020-03-16 21:58
Hi,
I am an outreachy participant and new to open source. Is this still open, can I try it.

**Comment by taysa91** [comment] 2020-03-16 22:08
Hi @gauravano 
I am an outreachy participant and new to open source. Is this still open, can I claim it.

**Comment by cesswairimu** [comment] 2020-03-23 21:00
@taysa91 please go ahead

**Comment by Ljungwaldh** [comment] 2020-08-14 05:54
Has this been addressed? I'm new to open source and would be happy to tackle this if this isn't claimed/assigned

**Comment by Ljungwaldh** [comment] 2020-08-14 06:21
Seems the reference to the issue is no longer placed where the description of this issue claims - I'm assumed then this would need to be closed?

**Comment by cesswairimu** [comment] 2020-08-16 10:15
Hi @Ljungwaldh :wave: ...checking that for you in a sec

**Comment by cesswairimu** [comment] 2020-08-16 10:23
@Ljungwaldh yes, it is still available...Its all yours. Thanks

**Comment by Ljungwaldh** [comment] 2020-08-19 08:28
@cesswairimu I cloned the plots2 repo over to my Visual Studio code application - however, the reference for a line 48 in plots2/app/views/users/profile.html.erb where the issue is meant to be does not exist there. Even tried to do a search for 'coathuored' and 'co-authored' but found nothing similar to the issue posted. 
My process has involved forking the repo in question, doing git clone on VSCode, creating a new branch and being ready to make the change. Is there anything I'm missing? 
<img width="1440" alt="Screenshot 2020-08-19 at 10 21 42" src="https://user-images.githubusercontent.com/60058573/90610999-74792900-e206-11ea-8d90-bd67022801b1.png">

Just a little confused as I've first learnt how to contribute via this repo:
https://github.com/firstcontributions/first-contributions

However perhaps I am not aware of and/or am missing a step on how to sort this issue correctly? Thanks in advance!

**Comment by cesswairimu** [comment] 2020-08-19 09:22
Yeah @Ljungwaldh you are right. My bad I must have looked at an old commit..Seems like the word was moved to config/locales but I don't see it used anywhere in the views so no need to change it there too. 

I will close this...Let me know if you need help finding another first-timer issue. Sorry for the confusion

**Closed by cesswairimu** 2020-08-19 09:22 UTC
Labels: HTML, assigned, first-timers-only

**Comment by Ljungwaldh** [comment] 2020-08-19 11:51
@cesswairimu no worries at all - just very keen to get into the start and flow of open source contribution, so if there's anything recent, up-to-date issues that are first time friendly then please let me know, thanks! :)

**Comment by cesswairimu** [comment] 2020-08-19 13:25
Great, I've created an issue for you here https://github.com/publiclab/plots2/issues/8331, kindly leave a comment to claim it.  We are glad to have you here and feel free o ask for help if stuck. Thanks
