### ISSUE TITLE
"Over 50 years ago" -- spam is back-dated to the dawn of Unix time

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#8332] opened 2020-08-19 13:48 UTC
Hello!
The spam dashboard is getting really awesome! Want to send big thanks @keshavsethi ✨🌻🌈🌳✨

### Please describe the problem

This is a quick share to say that moderators are observing that /spam2 has the same glitch on comments as /spam—they don’t show in recent order and the dates are all 50 years ago. See screenshot: 
<img width="1324" alt="screen_shot_2020-08-19_at_8 17 34_am" src="https://user-images.githubusercontent.com/161439/90642387-4d1f5d80-e200-11ea-82d4-5b22d7f32c9e.png">

The comments do show up properly on /comments, which is where @publiclab-mimi  tends to moderate from.
<img width="1333" alt="screen_shot_2020-08-19_at_8 19 05_am" src="https://user-images.githubusercontent.com/161439/90642401-50b2e480-e200-11ea-82f5-46e51c9d174a.png">

> What did you expect to see that you didn't?
The dates assist in sorting to find non-spam content that may have been buried in the onslaught of attempted spam, so it would be great to have these dates correct. 

### Please show us where to look

http://publiclab.org/spam2

### What's your PublicLab.org username?

liz

**Comment by keshavsethi** [comment] 2020-08-24 01:00
@ebarry @jywarren I think it is not pushed in publiclab.org. Timestamp works fine in https://stable.publiclab.org/spam2/comments/filter/all/30, Please check in stable. 
![Screenshot from 2020-08-24 06-24-48](https://user-images.githubusercontent.com/36025262/90993601-23d14980-e5d3-11ea-9bf7-510c2440b5cd.png)

Thanks!!

**Comment by jywarren** [comment] 2020-08-25 14:08
Hi @keshav234156 - that's odd, i don't think any new code is in stable that's not on plots2 besides in the home controller - take a look! 

...

oh wait -- did we not merge to stable branch last week???? Hmm. 

https://github.com/publiclab/plots2/commits/stable vs https://github.com/publiclab/plots2/commits/

It looks like not. Gah! OK, doing this today.

**Comment by jywarren** [comment] 2020-08-25 14:14
This is now republishing. We'll check the dates after but this should be resolved in the next hour or two when it goes live! https://jenkins.laboratoriopublico.org/job/Deploy%20Plots2/71/

**Closed by jywarren** 2020-08-25 14:14 UTC
Labels: bug

**Comment by jywarren** [comment] 2020-08-25 14:16
Hmm, also, I wasn't able to reproduce the original issue -- i see "about 2 hours ago" here, but I wasn't able to see what URL Mimi was looking at so I'm not sure if I'm looking in the right place -- this is a screenshot of https://publiclab.org/spam2 :

![image](https://user-images.githubusercontent.com/24359/91185512-ed232e00-e6bb-11ea-8038-204d10e1d706.png)

**Comment by ebarry** [comment] 2020-08-25 14:21
@jywarren will be the only one who can see this, but the issue was reported here in the org's slack : https://publiclab.slack.com/archives/CV7KG8MFT/p1597843123001500
