### ISSUE TITLE
likes should not be negative at '/events'

### ISSUE THREAD

**Issue by geekychaser** [publiclab/plots2#4589] opened 2019-01-10 19:22 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![image](https://user-images.githubusercontent.com/24489162/50991490-c93cc400-153a-11e9-9478-66a0dde9b5b9.png)

> What did you expect to see that you didn't?

### What's your PublicLab.org username?

geekychaser

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by geekychaser** [comment] 2019-01-10 19:23
@jywarren @SidharthBansal @gauravano can i give it a try ?

**Comment by gauravano** [comment] 2019-01-10 19:34
Hi @geekychaser, sure go ahead. Also, could you solve this #4237 with this one along? Thanks!

**Comment by geekychaser** [comment] 2019-01-10 19:37
yeah sure! I think both of the problem has same origin

**Comment by gauravano** [comment] 2019-01-10 19:41
Copying issue as reported by @JonathanXu1 in #4237 
------------------------------------------
I was browsing through https://publiclab.org/notes/recent, and noticed that a note has a negative number of likes:
![image](https://user-images.githubusercontent.com/22998430/49713581-58db1400-fc17-11e8-90ed-5d4f839a2eb4.png)
You can also see it at https://publiclab.org/notes/liked/ :
![image](https://user-images.githubusercontent.com/22998430/49713688-cbe48a80-fc17-11e8-8d56-f89351f9fd33.png)

As far as I'm aware, this has only occurred on the listing for this specific note. Moreover, this doesn't appear on it's own page:
https://publiclab.org/notes/warren/12-03-2018/openhour-usability-feedback-for-publiclab-org
This happens when I am logged in or out.

Please refrain from liking this note as it may hamper our ability to debug the issue! 

Browser/system: Firefox Quantum Windows 10
---------------------------------------------------------------------

Thanks @geekychaser!

**Comment by sashadev-sky** [comment] 2019-01-17 01:41
@geekychaser Hey! Any progress on this one? 

I was looking into it myself as well and I found many posts with negative likes.
<img width="955" alt="screen shot 2019-01-16 at 8 30 59 pm" src="https://user-images.githubusercontent.com/41092741/51289477-5619ce80-19ce-11e9-8832-a1f49625a22c.png">

Unfortunately was having trouble figuring out the solution myself because I don't know how I would check if the problem is solved or not in a test environment. So just going to follow along here.

One thing I did notice, if this is helpful, is that when I liked a post with -1 likes, it immediately bumped up to 1 like. After that, unliking will result in the post going back to 0, not -1.

Second thing is, on this page, when you click on the note itself even if it does have likes in the main index page on the note page itself it says it has none. So for some reason these are not translating over.

**Comment by geekychaser** [comment] 2019-01-17 11:43
@sashadev-sky yes, i noticed the same and even the post with `-2` likes once liked will show as 1 and on again disliking will give 0. I am facing difficulty in locating the same issue on local server.
can you help me regenerating the same on local server. So that we can identify the root cause behind the issue.
Thank you

**Comment by geekychaser** [comment] 2019-01-18 17:38
@sashadev-sky Great, lets wait for @jywarren reply

**Comment by jywarren** [comment] 2019-01-28 21:17
Yes, my apologies! Those with write permissions can push to the `unstable` branch at publiclab's repository on Github, and that will initiate a build at https://unstable.publiclab.org. Both of you should be able to, or either I or someone in @publiclab/maintainers can give you this permission i believe. Just be sure to coordinate in the chatroom (announce it) when you do because there is only one test server we all must share. Thanks!

**Comment by sashadev-sky** [comment] 2019-02-13 13:23
@geekychaser @jywarren I have found the line that was causing the issue:
https://github.com/publiclab/plots2/blob/5379e9780f07c31e3ef81113b0bf53c3e9f1d149/app/views/notes/_notes.html.erb#L37

changing `node.likes` -> `node.likers.length` fixes the issue. But I will wait to open a PR until #4778 is resolved because I am trying to figure out if there is a bigger problem with the source code overall with using 'node.likes' and `node.cached_likes` and `node.likers.length` all over the views that would cause issues. What do you guys think?

**Comment by sashadev-sky** [comment] 2019-03-16 19:13
closed via #4852

**Comment by sashadev-sky** [comment] 2019-03-16 19:13
closed via #4852

**Closed by sashadev-sky** 2019-03-16 19:13 UTC
Labels: bug
