### ISSUE TITLE
500 error on posting comment on an answer

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#3051] opened 2018-07-11 15:03 UTC
@Souravirus I'm not sure if this is a routing error or what, but do you think you could take a look?

`https://publiclab.org/comment/answer_create/1068?type=question&body=Ah%2C+ok.+Thanks+for+such+a+careful+look+at+this.+So+we+no+longer+get+separate+modified+lenses+--+we+just+get+whole+modified+and+unmodified+cameras+from+the+factory.+It%27s+very+helpful+to+know+that+the+loose+lenses+don%27t+work+well+for+the+latest+Mobius+camera+bodies%2C+so+we%27ll+probably+be+retiring+that+option+and+just+selling+whole+modified+and+unmodified+Mobius+cameras.+If+you%27d+like+to+exchange%2C+please+send+it+back+to+Kits+at%3A%0D%0A%0D%0APublic+Lab%0D%0A55+Cromwell+St+1C%0D%0AProvidence+RI+02907%0D%0A%0D%0ASorry+for+the+trouble+and+thank+you+x1000000+for+your+help+with+this+issue.+It+really+makes+a+difference.%0D%0A%0D%0AWe%27ll+add+in+a+free+extra+lens+with+different+geometry+if+you%27d+like+to+try+that+too+on+a+newer+Mobius+body.+Just+discussed+this+with+%40amanda+--+thanks+again!&_=1531320597441`

On this page:

https://publiclab.org/questions/tuomas_j_mattila/07-01-2018/mobius-lens-out-of-focus

Note that the comment actually gets posted, so i guess that means it's not a routing issue... @ViditChitkara perhaps this could be related to the comment form submission? Just trying to figure it out, any help appreciated:

![screen shot 2018-07-11 at 11 00 48 am](https://user-images.githubusercontent.com/24359/42581120-0f3ab8b2-84fa-11e8-8a83-e93f0edf1096.png)

**Comment by Souravirus** [comment] 2018-07-11 15:08
ok taking a look at it. Thanks!!

**Comment by jywarren** [comment] 2018-07-11 15:14
thank you!!!

**Comment by Souravirus** [comment] 2018-07-11 15:14
How is this possible @jywarren? 
![screenshot from 2018-07-11 20-42-20](https://user-images.githubusercontent.com/17192149/42581737-13f9c6da-854b-11e8-9285-68133679c482.png)
I have not commented it. I just opened this link to see this. suprised!!

**Comment by Souravirus** [comment] 2018-07-11 15:17
oh got it. Sorry to say I clicked the first link. Sorry again!! :smile: :smile:

**Comment by Souravirus** [comment] 2018-07-11 15:17
deleted the comment.

**Comment by Gauravano** [comment] 2018-07-11 15:18
Yup, its a request, my comment also got published :smile:

**Comment by jywarren** [comment] 2018-07-11 15:21
hahaha sorry i should've marked it as "don't open" my bad....

**Comment by Souravirus** [comment] 2018-07-11 15:33
This is the error I am getting while attempting a similar link.
![screenshot from 2018-07-11 21-02-51](https://user-images.githubusercontent.com/17192149/42582954-d1c8f0ee-854d-11e8-9be5-75aca0fa2b54.png)
Checking this.

**Comment by ViditChitkara** [comment] 2018-07-12 19:17
Hi @jywarren , I am not able to reproduce this on my local machine as well as the link. Any other question on which it occurred?

**Comment by jywarren** [comment] 2018-07-18 18:28
I'll close this for now, in part because we've had the whole commenting interface upgraded. But will look out for it!

**Comment by Souravirus** [comment] 2018-07-19 04:17
Ok I will try to see the request parameters

**Comment by Souravirus** [comment] 2018-07-20 22:11
Hi @jywarren, when I tried to see the request parameters Here what I got:
![screenshot from 2018-07-21 03-38-47](https://user-images.githubusercontent.com/17192149/43027425-c613fa18-8c97-11e8-9399-738e6b325e62.png)
Here as you can see the request type is html. So I guess changing to `.html` format might working. Testing if it works. Thank you!!

**Comment by jywarren** [comment] 2018-07-21 02:40
Awesome! We could show both .js and .html in the controller!

**Comment by Souravirus** [comment] 2018-07-23 20:43
I tried with format.html but its giving error as there is no such suitable html file to be rendered during creation of a comment to an answer. Also for now answering a comment on an answer is working perfectly. So, should we close this issue. What do you think?

**Comment by jywarren** [comment] 2018-07-23 21:40
Hmm, and we'd expect a js file to be sent back, right? I wonder how this happened...

https://github.com/publiclab/plots2/blob/bce1f1fb7847f5444474f26218284cfaf602d2c5/app/controllers/comment_controller.rb#L86

Could you try making an html template to see how that works? Otherwise could we modify the original request to send a .js request?

**Comment by Souravirus** [comment] 2018-07-23 21:42
Ok I will work on modifying the original request to send a .js request. Let's see.

**Closed** 2018-08-01 18:00 UTC
Labels: Ruby, bug, in progress
