### ISSUE TITLE
Add explanatory text to top of /tools

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#485] opened 2016-04-06 18:18 UTC
Hey folks, 
We're getting ready to start adding some standard information to each tool page (AKA wiki pages tagged "tool" https://publiclab.org/wiki/tag/tool which drives what's shown on https://publiclab.org/tools). This was prioritized during the March 2016 staff meeting. I anticipate that we will want to add some explanations at the top of /tools so i'm opening this issue to get started on that. The stuff we're going to add to each tool page will be something like: 

* current tier of use
* intended tier of use
* type of data collected
* usability / time required to use this tool
* etc

References: 

* Original issue on Tool Page Standardization: https://github.com/publiclab/plots2/issues/260
* Tiers of Use https://publiclab.org/notes/gretchengehrke/10-07-2015/intended-purposes-for-different-tools-and-techniques
* The Emporium: https://docs.google.com/spreadsheets/d/1Uln2B5ftYPGVQ_MRVRKKwgp3MQftu0hBeXKUBa5Meog/edit#gid=0

**Comment by jywarren** [comment] 2016-04-30 16:27
I'm really interested also in:

*  a listing of "hello world" type activities to get people caught up enough to participate in codesign
* a list of open challenges (please suggest a better name) so people know where to contribute (building on help-wanted developer outreach work at https://publiclab.org/wiki/developers#Contributing+for+non-coders)

**Comment by jywarren** [comment] 2016-04-30 16:37
For tiers, I think there'll typically be several aimed for, if fewer achieved yet. Maybe we could have them stated as a single sentence each, like:

* For [alert-level]() data collection of waterways
* For [regulatory-level]() data collection of air grab samples

It'd probably have to be even more specific, and I'm not using the named tiers from Gretchen's note yet. 

There's a lot to put on a given methods page; it might need a 2x3 grid or something: here I didn't even get to "intended uses" vs "current uses":

![tmp_24190-img_20160430_123141 2367941707](https://cloud.githubusercontent.com/assets/24359/14937250/d664ec26-0ecf-11e6-8d4f-1e328e6c848d.jpg)

**Comment by jywarren** [comment] 2016-04-30 16:49
Maybe it could be roughly divided into a few sections:

* Get started
  * Materials
  * Setup steps (on boarding/hello worlds)
  * Reproduce existing tests
  * Ask a question
* What's happening
  * Case studies
  * Goals and current status
  * Recent activity
* Contribute
  * Open challenges/questions
  * Upcoming/proposed revisions

**Comment by ebarry** [comment] 2016-05-05 16:00
This is looking great. @gretchengehrke please check out the comments in this thread. Also, for reference, here's a sandbox page where we can test out formatting: https://publiclab.org/wiki/sandbox-tool

**Comment by gretchengehrke** [comment] 2016-06-29 19:32
Hi @ebarry , 
I'm working on filling out the info in the sandbox-tool for each tool. Can you please provide a list of wiki pages for which you'd like this section added? I'm not sure what the most relevant or up-to-date wiki page is for some of the tools. Thanks!! Also, do you want this info at the top of the page for each wiki? Or elsewhere? Thanks!

**Comment by ebarry** [comment] 2016-06-29 19:46
The full set would be what's on https://publiclab.org/tools

But for now, could you pick the minimum set required to put this template
idea through its paces, and then report back how it's working and what you
suggest?

Then we can make a revision, Jeff can make a nicelooking template and we
can go from there...

--

+1 336-269-1539
@lizbarry <http://twitter.com/lizbarry>

**Comment by ebarry** [comment] 2016-07-01 16:29
also @jywarren, regarding the graphic sketch you posted earlier in this thread, look at the clarity of the info-design in http://openrov.dozuki.com/Guide/Guide+6+-+Finishing/68 (HT @sdosemagen)

**Comment by jywarren** [comment] 2016-07-05 19:34
Yeah, i love it! +1 also thinking about prompt forms for "i build this!"
etc. "i built this" tags could be profile tags.

**Comment by jywarren** [comment] 2016-08-29 18:28
I wanted to put out the idea of showing `# activities` and `# upgrades` in the list view, and/or just below the header of a method page. Maybe something like that openROV page: 

![screenshot 2016-08-29 at 2 21 01 pm](https://cloud.githubusercontent.com/assets/24359/18062215/e115efb6-6df3-11e6-9e64-20372738683f.png)

**Comment by jywarren** [comment] 2016-10-28 23:04
Are there other design priorities we're not capturing in the new activity grids, related to this post? I'm going to close it, but we may want to think through overall UI design for tool/technique pages, perhaps along the lines of the 3-column layout above, or at least thinking about what to do with the sidebar.

**Closed by jywarren** 2016-10-28 23:04 UTC
Labels: Outreach, priority
