### ISSUE TITLE
"Show more" button on tables of notes not useful any more; adapt or remove

### ISSUE THREAD

**Issue by kabuur** [publiclab/plots2#10901] opened 2022-04-01 11:48 UTC
**Please describe the desired behavior.**
Describe the solution you'd like.

**Additional context (optional)**
Feel free to include any applicable: code, screenshots, or gifs.

**Comment by TildaDares** [comment] 2022-04-01 13:50
Duplicate of #10817

**Closed by TildaDares** 2022-04-01 13:50 UTC
Labels: feature
