### ISSUE TITLE
Questions search redirects to the post page when no search results found

### ISSUE THREAD

**Issue by ananyo2012** [publiclab/plots2#700] opened 2016-08-19 07:14 UTC
### What happened just before the problem occurred

When I am trying to search a question by typing in the search title in the question search box(and then pressing enter) in the question page it redirects to the post page if no search results are found. This is not happening if the search result exists. 

This is certainly not a Ruby related problem as I didn't put any redirects in either of the actions in `questions_search` controller as you can see here: https://github.com/publiclab/plots2/blob/master/app/controllers/questions_search_controller.rb

This is further confirmed by directly going to the questions_search page by typing in the url like: https://publiclab.org/questions_search/dou. You can see it clearly mentions no search results are found and Proceed to question button. This also should have been the result while searching from the questions page.

So this is basically a JavaScript related problem. Here is the javascript file that contains the search logic: https://github.com/publiclab/plots2/blob/master/app/assets/javascripts/questions_search.js and this is the search form: https://github.com/publiclab/plots2/blob/master/app/views/questions/index.html.erb#L17-L29
### Relevant URLs

https://publiclab.org/questions
### PublicLab.org username

ananyo2012
(to help reproduce the issue)
### Browser, version, and operating system

Google Chrome, Firefox on Ubuntu 14.04 LTS

**Comment by ananyo2012** [comment] 2016-08-19 07:15
I am missing something here. This can be made into a `first-timer-only issue` in case i can figure out what is happening.

**Comment by jywarren** [comment] 2016-08-19 15:14
Hi, Ananyo -- if there's not a clear path to a solution, maybe we should
make it a `help-wanted` issue, rather than a `first-timers-only` one. And
if you'd like me to take a look, i'm happy to later today.

**Comment by ananyo2012** [comment] 2016-08-19 15:17
@jywarren Yes I have labeled it as a help wanted issue. Yes it would be great if you take a look. I have added the link to the areas that effects it.

**Comment by jywarren** [comment] 2016-11-04 17:47
I'm reading this over again and I'm not sure it's clear what the correct expected outcome is, Ananyo -- could you clarify? Do you not think it should go to a new post form? I thought that was intended -- that if there's no existing matching question, it prompts you to ask the question yourself?

**Comment by jywarren** [comment] 2017-11-16 01:40
I believe this is the expected behavior! Closing, thank you!

**Closed by jywarren** 2017-11-16 01:40 UTC
Labels: bug, help-wanted, JavaScript
