### ISSUE TITLE
PRs are failing because of 'bad argument (expected URI object or URI string)' error

### ISSUE THREAD

**Issue by Manasa2850** [publiclab/plots2#9756] opened 2021-06-07 11:40 UTC
A lot of the recent PRs are failing because of this error. This causes all 4 tests - unit, functional, integration and system tests to fail.
Closing and reopening the PR is not solving this error.
![Screenshot 2021-06-07 17:09:27](https://user-images.githubusercontent.com/43354059/121010511-247a4b80-c7b3-11eb-92ed-74da7120f954.png)

**Comment by anirudhprabhakaran3** [comment] 2021-06-08 03:04
This seems to come up on searching for the error on Google.
https://stackoverflow.com/a/18550240

**Comment by cesswairimu** [comment] 2021-06-08 07:49
thanks for reporting this @Manasa2850 ..looking into it

**Comment by cesswairimu** [comment] 2021-06-08 08:29
I think this is caused by one of the libraries updates because I can see the tests all pass with no failures

**Comment by cesswairimu** [comment] 2021-06-08 10:19
okay was able to get https://github.com/publiclab/plots2/pull/9757 to pass with 3 restarts

**Comment by Manasa2850** [comment] 2021-06-08 11:18
@cesswairimu closing and reopening doesn't seem to work always. I tried it a couple of time on #9733 but the tests are still failing :cry:

**Comment by cesswairimu** [comment] 2021-06-08 11:21
Yeah you are right, seems like its a codecov problem

**Comment by cesswairimu** [comment] 2021-06-08 13:13
Barun also mentioned on gitter

> Major CDN outage affecting lots of popular websites including GitHub, Reddit, StackOverflow. So if you are experiencing issues in some of these websites might wanna wait for things to get back normal :)

**Comment by cesswairimu** [comment] 2021-06-09 06:45
Looks like this is now resolved...Found this conversation other people were having the same prob with codecov https://github.com/codecov/codecov-action/issues/330 and looks like a fix was deployed 5 hours ago. Closing this. Thanks

**Closed by cesswairimu** 2021-06-09 06:45 UTC
Labels: bug

**Comment by RuthNjeri** [comment] 2021-06-09 08:24
Thanks for helping figure this out @cesswairimu 🎉
