### ISSUE TITLE
Issues with Input Fields in Login Modal

### ISSUE THREAD

**Issue by kevinzluo** [publiclab/plots2#4244] opened 2018-12-10 08:06 UTC
Currently at a specific width, the Login Modal errors and the input fields stick out of the body.

![issueswithwidth](https://user-images.githubusercontent.com/44309027/49717466-c9386400-fc1c-11e8-8603-a25cf04f85cf.gif)

I believe this is a CSS issue but I am not too familiar with it.
Perhaps looking into the code here  (plots2/app/views/user_sessions/_new.html.erb) will give some answers.
      
Chrome Ubuntu

**Comment by kevinzluo** [comment] 2018-12-10 08:13
Issue also occurs using cloud9 on windows chrome.
[![Image from Gyazo](https://i.gyazo.com/370cbb884dec230b99b12ddb9a605a60.gif)](https://gyazo.com/370cbb884dec230b99b12ddb9a605a60)

**Comment by SidharthBansal** [comment] 2018-12-10 09:57
@kevinzluo I guess I have rewarded you for this.

**Comment by IshaGupta18** [comment] 2018-12-20 06:53
Hey @kevinzluo @SidharthBansal can anyone tell me where is the css file for making it responsive? I think I have some idea on how to fix this, but I would be needing the css file for that. Thanks a lot.

**Comment by SidharthBansal** [comment] 2018-12-20 07:04
Hi I think @kevinzluo has fixed the issue.
Let's ask him first. If the issue is solved then we can close this issue.
Thanks all

**Comment by kevinzluo** [comment] 2018-12-20 16:30
Actually I haven't tried solving this issue yet. @IshaGupta18 please go ahead 😄 . I don't really know where the CSS for the modal is contained.

**Comment by SidharthBansal** [comment] 2018-12-23 12:42
@IshaGupta18 how is it going?

**Comment by IshaGupta18** [comment] 2018-12-23 12:48
I actually fixed this issue by inspecting the site in developer's console. I tried a lot to find the css file where the code for making this responsive is written, but couldn't do so. I think I'll have to think of a different solution, but I can't be sure of finding it, because I tried a lot to resolve this issue before, but couldn't. I am terribly sorry if I caused any delay or trouble in this.

**Comment by IshaGupta18** [comment] 2018-12-23 13:04
Will it be okay if I take a little more time in attempting to fix it?

**Comment by jywarren** [comment] 2018-12-23 13:17
If you look at the site in the dev console in development mode you should
be able to see the separate css files, but on production they've been
compiled into one giant file so it's harder to track. Good luck! We can
help more if you get stuck!

**Comment by IshaGupta18** [comment] 2018-12-23 13:31
Alright, thank you for the tips! I will get back to you in case I get stuck!

**Comment by IshaGupta18** [comment] 2018-12-23 14:31
I think this looks a bit better. What do you think @SidharthBansal @jywarren ? Ps: I am really sorry for the poor quality gif.

![inputfields 1](https://user-images.githubusercontent.com/40794215/50384625-67343000-06ed-11e9-88bf-3620a1e74ffb.gif)

**Comment by IshaGupta18** [comment] 2018-12-23 19:46
@SidharthBansal let me know if it looks good to you.

**Comment by SidharthBansal** [comment] 2018-12-24 12:35
Awesome!!!

**Comment by IshaGupta18** [comment] 2018-12-24 12:42
Should I create a PR for this then?

**Comment by SidharthBansal** [comment] 2018-12-24 12:49
Yeah sure!!!

**Comment by IshaGupta18** [comment] 2018-12-24 14:59
I am sorry I wasn't able to make a PR for this issue. I am facing some difficulty with git in doing so, I'll make a PR as soon as it is resolved.

**Comment by SidharthBansal** [comment] 2018-12-24 15:04
Take your time. No hurry.

**Closed** 2018-12-25 08:53 UTC
Labels: design, help-wanted
