### ISSUE TITLE
Route Error in logging in from wiki/events

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#4392] opened 2018-12-24 14:42 UTC
When on page /wiki/events and trying to log in from there, this error has been caught.

![image](https://user-images.githubusercontent.com/40794215/50401895-1f2e0f80-07b8-11e9-8402-0430cc803898.png)

Kindly have a look at it. Your help is truly appreciated.

**Comment by SidharthBansal** [comment] 2018-12-24 15:00
Thanks Isha for reporting the issue.
Nice catch

**Comment by IshaGupta18** [comment] 2018-12-24 15:01
No problem!

**Comment by gauravano** [comment] 2018-12-25 09:04
Hi @IshaGupta18 could you point using which button or link you tried logging in? Also, if you want to solve it yourself, please go ahead. Thanks!

**Comment by IshaGupta18** [comment] 2018-12-25 09:08
The login button in nav bar. I even tried linking a button to login modal and logging in through that from the same oage (wiki/events) but it still didn't work, because both would mean the same altogether. I am so sorry but currently I am working on #4344 . In case it's done in time, I'll try to do this as well. If anyone wants to start working on this one, they are most welcome to.

**Comment by oorjitchowdhary** [comment] 2018-12-25 09:48
@sidharthbansal this is the same error I was getting at #4254
Glad @ishagupta18 had reported this earlier

**Comment by IshaGupta18** [comment] 2018-12-25 10:01
Hey I locally tried @gauravano fix for this and it works really well, however, whenever I login (and probably wherever I login from) , I am redirected to root with this message, was this message intended to be there? (PS: I am sure it had nothing to do with @gauravano 's fix, if this message is an error)

![image](https://user-images.githubusercontent.com/40794215/50420016-f9594700-0859-11e9-8736-ff01f3301a34.png)

**Comment by gauravano** [comment] 2018-12-25 10:17
Hey @IshaGupta18 @oorjitchowdhary I have resolved the login issue. @oorjitchowdhary please update your PR.

@IshaGupta18 yes, that error is not related to my fix. That error or say message is coming when you are on /login and try to login using modal?

**Comment by gauravano** [comment] 2018-12-25 10:30
Whenever at time of login return to would be carrying ''/login" then this message would come, as login page can only be shown to logged out user. I don't think it should come at every page. This can be handled by removing the return_to if it contains "/login" . If you can specify, particular page or button at which this message is coming, then it would be of help. Thanks!

**Comment by IshaGupta18** [comment] 2018-12-25 10:32
By every page I meant on logging in from e=any page you are on right now.

**Comment by gauravano** [comment] 2018-12-25 14:33
Could you please paste the logs or GIF as I am unable to reproduce the error. I am trying on stable.publiclab.org as it is updated with master branch. Thanks!

**Comment by SidharthBansal** [comment] 2018-12-25 17:08
I have opened this issue as both of you are working on it. Once the issue which you both collaboratively are trying to solve is resolved, please feel free to close this issue.

**Comment by gauravano** [comment] 2018-12-25 17:50
Tried on stable.publiclab.org
![login_redirect1](https://user-images.githubusercontent.com/20878070/50425421-9e484400-089b-11e9-87d1-1820da76b398.gif)

Will check on localhost soon..

**Comment by SidharthBansal** [comment] 2018-12-27 19:43
What's the status?

**Comment by gauravano** [comment] 2018-12-28 15:55
You don't need to be sorry if you observed error and we can't find it now or even if that error was due to outdated branch. 

It's good if it's fixed but if you see it again then don't feel shy to open a new issue.

Thanks @IshaGupta18 :)

**Closed by gauravano** 2018-12-28 15:55 UTC
Labels: bug

**Comment by IshaGupta18** [comment] 2018-12-28 16:06
Okay Thanks a lot! I am glad the main issue here is resolved!
