### ISSUE TITLE
Update color of "share your work" dropdown caret on homepage dashboard

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#7812] opened 2020-04-14 02:11 UTC
## First Time?

This is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**.

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, consider leaving this one for someone new, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

## The problem

What happens:

On the publliclab dashboard: https://publiclab.org/dashboard, the dropdown caret for the share your work button is black. This causes some unusual hover behavior as it quickly toggles between black and white when you click on it.

![2020-04-13 22 03 00](https://user-images.githubusercontent.com/41092741/79178227-ad297180-7dd2-11ea-93a4-8ce48feb7882.gif)

Note: (not shown above) that it also toggles between black and white on hover when the dropdown is expanded.

## Solution

We can make it stop toggling between black and white by just initially setting it to white.

**Where to find the relevant lines of code**:

https://github.com/publiclab/plots2/blob/dc6a61f60761eb5731f4e1d27f25ee572352ba44/app/views/sidebar/_dashboard.html.erb#L5

**What to change them to**:

add the class "fa-white" to the end of the class on the `a` tag linked above.

Thanks!!

## Step by Step
- [ ] Claim this issue with a comment here, below, and ask any clarifying questions you need
- [ ] Fork the repository and set it up locally following the main repo README instructions [https://github.com/publiclab/plots2](https://github.com/publiclab/plots2)
 - [ ] Create a new feature branch with a unique name descriptive to the issue
- [ ] Try to fix the issue following the steps above, but even before you're done, you can:
  commit your changes to your branch and start a pull request (see [contributing to Public Lab software](https://publiclab.org/wiki/contributing-to-public-lab-software)) but mark it as "in progress" if you have questions or if you haven't finished
- [ ] Reference this issue in your pull request body
- [ ] Once you submit your pull request, an additional checklist will be provided for getting it merged

### Please keep us updated
💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

##  💬   Get help
If you need any help - here are some options: 

- Comment below
- Join our gitter chat at https://gitter.im/publiclab/publiclab

**Comment by nila99** [comment] 2020-04-14 02:16
I can work on this :)

**Comment by sashadev-sky** [comment] 2020-04-14 02:33
@nila99 ok awesome assigning you! thanks :)

**Comment by satyamgipu** [comment] 2020-05-06 03:36
I want to work on  this issues .

**Comment by ioampatzidis** [comment] 2020-06-03 11:14
Hello, could i work on this issue? 
Thank you

**Comment by avats-dev** [comment] 2020-08-02 21:46
#### Is this issue needs to be worked on? @sashadev-sky @cesswairimu 
> I would like to contribute.

**Comment by cesswairimu** [comment] 2020-08-03 14:38
Hi @avats-dev , let me check if the issue is still there

**Comment by cesswairimu** [comment] 2020-08-03 14:42
This was solved on this PR https://github.com/publiclab/plots2/pull/7981 . Closing this... @avats-dev  seen your name is on the fto list, we will ping you when smth comes up thanks

**Closed by cesswairimu** 2020-08-03 14:42 UTC
Labels: assigned, first-timers-only, good first issue

**Comment by avats-dev** [comment] 2020-08-03 17:41
@cesswairimu ok.
