### ISSUE TITLE
Problem with Login/Oauth/signup in production

### ISSUE THREAD

**Issue by Dsxv** [publiclab/plots2#4569] opened 2019-01-08 17:19 UTC
![dsxv_log](https://user-images.githubusercontent.com/36789080/50847156-e46ece80-1396-11e9-8eed-7fd59aae28ea.gif)
![dsxv_log1](https://user-images.githubusercontent.com/36789080/50847161-e769bf00-1396-11e9-9001-c5cc3ce7766a.gif)
not able to login in anyway  D: 
Thanks for help!

**Comment by geekychaser** [comment] 2019-01-10 16:05
@jywarren @gauravano facing same issue, not able to login/signup in any of the ways
![login1](https://user-images.githubusercontent.com/24489162/50980786-81f50a00-151f-11e9-8d06-2622048b21db.gif)

**Comment by gauravano** [comment] 2019-01-11 10:57
Same issue reported by @dhruvgupta167 and @dewanhimanshu at #4534 

![screenshot 2019-01-05 at 5 57 39 pm](https://user-images.githubusercontent.com/32172694/50724434-736bb480-1113-11e9-9427-ae557c69f3a1.png)
Screenshot by @dhruvgupta167 


![screenshot from 2019-01-11 12-15-28](https://user-images.githubusercontent.com/32437794/51017705-f91bb400-159a-11e9-8209-b210e0804e8e.png)
Screenshot by @dewanhimanshu 

-------------------------------------------------------------------
@jywarren @SidharthBansal so Google OAuth isn't working but somehow due to a bug probably the user is shown signed-in alert.

@SidharthBansal how about trying OAuth locally so that better debugging can be done with logs in hand?

Thanks!

**Comment by gauravano** [comment] 2019-01-11 11:00
@Dsxv @geekychaser @dewanhimanshu @dhruvgupta167 please use normal signup/signin form till the issue is solved. Thanks!

**Comment by Dsxv** [comment] 2019-01-11 11:56
@gauravano It's actually different in my case , I am not able to login from any way , That's why I created this issue so that mods would delete my profile , So that I can lsignup again .
Thanks!

**Comment by gauravano** [comment] 2019-01-11 12:01
I can understand @Dsxv, as profile is not visible to moderators too, so it's little tough situation. I know with GSoC coming and all, you guys don't want to miss any updates. I would suggest to signup again with alternate email ID email so that you can stay updated. 

Thanks!

@jywarren can you copy production logs for signup and signin via OAuth?

**Comment by gauravano** [comment] 2019-01-14 23:34
Closing this one as it's just same issue as #4522. Thanks all!

**Comment by jywarren** [comment] 2019-01-14 23:50
I'd like to re-open this and carefully collect additional info on it to try to reproduce. I've been puzzling on it for a while, but can't reproduce. Can people note:

1. what page they were on when they started
2. what they pressed to get the login form
3. what page they were redirected to,
4. did they see the `Signed In` message
5. did they still see `Login` and `Signup` even after refreshing the page one more time?

**Comment by jywarren** [comment] 2019-01-15 00:00
I've logged in from https://publiclab.org using Twitter and GitHub, both to `warren` account, without issues. 

I logged in using username/pwd for account `tester` without problems.

**Comment by ebarry** [comment] 2019-01-15 00:04
I logged in from the homepage dropdown menu option to Login, using an incognito tab in Chrome, and everything worked fine. 

Separately, it's kind of funny that i have a hard time logging out of a regular tab in Chrome, it just redirects me to the homepage with an error banner that says "you have to be signed in to see this page" but i am still signed in.

**Comment by jywarren** [comment] 2019-01-15 00:07
Hi, Liz, can you file that as a separate issue please? Thanks!

I tested using a throwaway Facebook account and was directed to
https://publiclab.org/?_=1547510492# with the message `Signed in` but i was
not signed in. This seems to replicate the issue.

**Comment by gauravano** [comment] 2019-01-15 00:12
Hey @jywarren @ebarry I reproduced this error of OAuth - https://drive.google.com/open?id=1w9tc4kIkoLJ5tvceoyQ1-kO_yug2pMDR 

As I commented in #4522, this error is due to banned user accounts. And, I guess this is what we are looking for. Thoughts?

**Comment by jywarren** [comment] 2019-01-15 15:08
Believe this is now resolved in #4522 and #4618!

**Closed by jywarren** 2019-01-15 15:08 UTC
Labels: brainstorm, bug, gsoc, inspection, priority, rgsoc
