### ISSUE TITLE
Save option is not activated

### ISSUE THREAD

**Issue by nikhilrayaprolu** [publiclab/plots2#8136] opened 2020-07-13 13:34 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I installed plots2 locally and was creating a new post
![image](https://user-images.githubusercontent.com/15216503/87310339-77179d00-c53b-11ea-97d7-dfbf77c82716.png)

> What did you expect to see that you didn't?

But the save option is inactive not letting me to save the post

### Please show us where to look

https://publiclab.org/ ...
http://localhost:3000/post

> This can help us diagnose the issue: 

There's this error locally in my browser console
```
Uncaught DOMException: Failed to execute 'atob' on 'Window': The string to be decoded is not correctly encoded.
    at dataURItoBlob (http://localhost:3000/post:1370:24)
    at http://localhost:3000/post:1385:71
    at http://localhost:3000/post:1387:5
```

**Comment by cesswairimu** [comment] 2020-07-13 13:44
HI @nikhilrayaprolu,  I believe you need to add text in the "body part"...i.e on number 4 for the button to be active (atleast 10 chars I think). Let me know if you are still experiencing issues after that. Thanks

**Comment by nikhilrayaprolu** [comment] 2020-07-13 13:53
@cesswairimu Thanks for the reply, you are right.
It would be great if the min length is mentioned in the conditions in that page.

**Comment by cesswairimu** [comment] 2020-07-13 14:59
yeah I agree we could add a placeholder for now with the data as we have on the title....will that help?

**Comment by cesswairimu** [comment] 2020-07-23 19:45
I have created an fto here https://github.com/publiclab/plots2/issues/8180 to add a placeholder for this hopefully this will make a little difference...I am closing this since its not a bug but its deactivated until the body content is input by design. Thanks

**Closed by cesswairimu** 2020-07-23 19:45 UTC
Labels: bug
