### ISSUE TITLE
Translation string replacement errors

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7798] opened 2020-04-08 17:56 UTC
A huge and wonderful effort to set up translation strings for site-wide texts has been going on for some time in #7416 and other issues -- many thanks to those who've helped!

I noticed that when a non-english language is selected, we now have some issues with the translation icons appearing:

![image](https://user-images.githubusercontent.com/24359/78816790-32122680-79a0-11ea-8896-94c97cf16062.png)

Some are parsing errors causing for example the text `" data-placement="bottom" href="/dashboard">Dashboard` to appear. Others simply add the globe icon causing items not to fit in the layout anymore. For comparison, here is the dashboard in English:

![image](https://user-images.githubusercontent.com/24359/78816959-6ede1d80-79a0-11ea-9b2c-1d90447b4d23.png)

You can see this happening by clicking on this link which will change the language of the `stable` server so you can see the translations turned on (this for spanish):

https://stable.publiclab.org/change_locale/es

I'd like to ask for help in solving these parsing and layout issues! They should be pretty simple and you should be able to test them locally by setting a language locally, for example with:

http://localhost:3000/change_locale/es

Thanks, everyone!

**Comment by jywarren** [comment] 2020-04-08 18:01
Many of these translations were added starting from this issue, for reference! https://github.com/publiclab/plots2/issues/6579

**Comment by jywarren** [comment] 2020-04-08 18:22
I believe that the switch to the custom translation function has caused a parsing issue in some cases. 

Here is documentation on how this process is supposed to work, via @gauravano (hiiii!!! 👋 ❤️ hope you're well!!!)

https://github.com/publiclab/plots2/issues/5737#issuecomment-546853536

> Hi @jywarren @nstjean, yeah, `t(..)` can be replaced by `translation(...)`. The code for translation is in `helpers/application_helper.rb`. 

> **NOTE:** After replacing, testing that view is necessary as it may not work for complex blocks like div, span, etc. 

> And, if corner cases need to be handled, then one can change the helper definition.

**Comment by jywarren** [comment] 2020-04-08 18:22
cc @cesswairimu @SidharthBansal @nstjean just as a heads up! Thanks to everyone!

**Comment by jywarren** [comment] 2020-04-08 19:35
Approved. I believe this is all resolved now -- thank you SO MUCH for reporting, and if there are more issues i can take another look!

**Comment by jywarren** [comment] 2020-04-08 19:36
Ah sorry! Wrong issue! This is still open!

**Comment by cesswairimu** [comment] 2020-04-08 21:04
oh that looks not pretty will do some investigating tomorrow

**Comment by Tlazypanda** [comment] 2020-04-10 23:27
@jywarren I went through the stable.publiclab.org and apart from this error that you have already fixed, I can't find anything as such :sweat_smile: . I looked up the recent translation codes and looked through those routes specifically but doesn't seem to be breaking anywhere else. Any particular route that has any other issue? Would be happy to help :smile:

**Comment by Tlazypanda** [comment] 2020-04-10 23:32
@jywarren Had a look apart from the error that you already fixed can't seem to find any more buggy routes :sweat_smile: . I checked by seeing the recent translation codes merged and checking those specific routes. If there is any particular route that has bugs I would be happy to help :smile:

**Comment by jywarren** [comment] 2020-04-12 17:28
Hi @Tlazypanda i think the routes issue should be all good now? That was separate from this, and i think i just had them mixed up with too many tabs. Does this translation bug make sense though? Thanks!

**Comment by cesswairimu** [comment] 2020-04-13 13:25
@jywarren did you manage to fix this...I am looking at stable and I don't see the bugs

**Comment by jywarren** [comment] 2020-04-14 15:06
i don't think so - to reproduce you have to select a non-english language using the footer selector

**Comment by jywarren** [comment] 2020-04-14 15:15
So for the navbar, which is the worst issue, I see the HTML resulting from the adapted translation code is as follows:

```html
<div class="input-group">
          <input type="text" id="searchform_input" class="form-control search-query typeahead" role="search" qrytype="tags" placeholder="<span>Search on Public Lab <a href=" https:="" www.transifex.com="" publiclab="" publiclaborg="" translate="" #de="" $?q="text%3ASearch" on="" public="" lab"="" style="cursor: text;">
          <i data-toggle="tooltip" data-placement="top" title="" style="position:relative; right:2px; color:#bbb; font-size: 15px;" class="fa fa-globe" data-original-title="Needs translation? Click to help translate this text."></i>
       "  value="" required&gt;
          <div class="input-group-append">
            <button class="btn btn-light" type="submit"><i class="fa fa-search"></i></button>
          </div>
        </div>
```

So, it's not nesting properly and looks like this:

![image](https://user-images.githubusercontent.com/24359/79241523-29f33480-7e41-11ea-90a8-940ab2d1a391.png)

**Comment by jywarren** [comment] 2020-04-14 15:17
For that one (let's do other fixes on other issues but this walks us through the process of one particular fix, as an example), I see line 20 shows there's only one change, to the `placeholder` attribute of the search:

https://github.com/publiclab/plots2/blob/81df65f8b99c3cd1dcaf427c0fde42e87206fde4/app/views/layouts/_header.html.erb#L17-L25

**Comment by jywarren** [comment] 2020-04-14 16:41
There are also a lot of layout issues related to the globe icon appearing in the header navbar. I'm going to revert the bunch right now in https://github.com/publiclab/plots2/pull/7815, and we may want to think about a different kind of indicator for use in those places.

**Comment by jywarren** [comment] 2020-04-14 17:16
Great, that fixed the navbar. Let's sum up next steps:

* [ ] warnings about usage in buttons and HTML tag attributes
* [ ] better guidance on how to test these locally and how to post screenshots of them working
* [ ] any other follow-up fixes for bad layout issues resulting

Thanks!!

**Comment by jywarren** [comment] 2020-04-14 18:23
Just noting that there have also been a lot of these translation changes made to the login/signup form and that is potentially another area where they may have caused issues. However I can't seem to document these well as I can't switch languages in incognito mode... maybe i need to be logged in?

**Comment by Tlazypanda** [comment] 2020-04-16 19:06
@jywarren I am not sure what's wrong but I am not able to reproduce any bugs... when I previously commented too I was referring to the navbar and it was not buggy (before you committed the fix) @cesswairimu did you face the same issue? I tried again with both stable/local, in incognito mode, setting various languages (hindi,spanish,dutch) can you point out where I am going wrong :sweat_smile:

**Comment by Tlazypanda** [comment] 2020-04-16 19:18
As for the buttons part I went through the code and these are the instances where translation is used inside a button so that we can test if these routes are bug free. For the warnings generation we can update the internationalization part in the docs to specify what @gauravano  had mentioned in his comment earlier. Please help me with how to reproduce these bugs too :sweat_smile: . Thanks :v:  - 
![Screenshot from 2020-04-17 00-38-27](https://user-images.githubusercontent.com/33183263/79496990-9a1dd800-8044-11ea-9c1b-c1cc31b074dc.png)

**Comment by jywarren** [comment] 2020-05-06 17:17
Hi, sorry for slow response, thanks for the thorough look! I'm not sure why it's not appearing for you, but I agree about use inside buttons. I just filed a new instance that is exactly that!

https://github.com/publiclab/plots2/issues/7882

**Comment by jywarren** [comment] 2020-10-13 17:21
Hi all, i've just created 2 FTOs with examples of this going wrong - check out the above links! In both cases, I left an explanatory note to future coders. Both are reproducible on the live site right now! Thanks @Tlazypanda and apologies for responding slowly! Also cc'ing @gauravano ❤️

**Comment by jywarren** [comment] 2020-10-13 20:30
Another instance i had to revert due to poor rendering -- #8565 

And, noting a couple bad renders here at https://stable.publiclab.org/tag/water-quality -- (click https://stable.publiclab.org/change_locale/es first to turn on translations to see this)

![image](https://user-images.githubusercontent.com/24359/95912799-4d0b8c00-0d71-11eb-8f2b-f955a936be33.png)

**Comment by gauravano** [comment] 2020-10-14 13:50
Hi @cesswairimu @Tlazypanda, you're not able to see the globe icons because your profile doesn't have `translation-helper` tag. It is the first condition checked in the code. 

`if current_user&.has_tag('translation-helper')`. 

This wiki - https://publiclab.org/wiki/translation contains join the translation group button which is also doing the same thing, Adding the tag to the user profile.

I also checked out the documentation - https://github.com/publiclab/plots2#internationalization and I feel it is very much focussed on developers. Like, we can also provide link to Public Lab Transifex account and user can sign-up for being contributor there?

I saw some PRs opened for https://github.com/publiclab/plots2/issues/6579 and looks like views are not tested. Maybe contributors were not aware of adding `translation-helper` tag. So, a point about this can be called out in the documentation. Or, we can provide **Translator role** from the Settings page?

Thanks!

cc @jywarren @ebarry

**Comment by tawahpeggy** [comment] 2020-10-15 10:59
i am intrested to work on this issue if possible.

**Comment by YogeshSharma01** [comment] 2021-04-04 06:33
Hi, @grvsachdeva like only users who have an account on Transifex those users can only translating the website into different languages using Transifex. When I try to translate the text by clicking on the 'Get Started' in the globe icon, I'm directed to the 404 pages on the transfix website 
![Screenshot 2021-03-30 at 11 50 10 PM](https://user-images.githubusercontent.com/51679200/113500388-261d5e00-953b-11eb-8c9e-5ce9b37fa2af.png). 
Also, I have contacted the support team but it takes so long to respond so can you help me with this I also open an issue for this https://github.com/publiclab/plots2/issues/9394 this is the [link](https://www.transifex.com/publiclab/publiclaborg/translate/#de/$?q=text:%23%7Btranslated_string%7D) no longer work.
What do you think the account expired or if they substantially changed the API?

**Comment by grvsachdeva** [comment] 2021-04-04 10:47
Hi @YogeshSharma01, yeah account is required to act as a translator on Transifex, and apart from that I believe the project need to act a person as translator or in relevant role too. I can see there are bunch of requests pending to be accepted. 

Hey @jywarren @ebarry please checkout https://www.transifex.com/publiclab/teams/65351/requests/ 😄

**Comment by YogeshSharma01** [comment] 2021-04-04 12:19
Hi, @grvsachdeva this [link](https://www.transifex.com/publiclab/teams/65351/requests/) also shows me 403 forbidden error I have shared a ScreenShot below, or either @jywarren  and @ebarry can only open this page and able to see the requests?
![Screenshot 2021-04-04 at 5 46 42 PM](https://user-images.githubusercontent.com/51679200/113508465-d0ae7480-956d-11eb-96a2-350c854d7d2c.png).

**Comment by YogeshSharma01** [comment] 2021-04-05 16:07
Hi, @grvsachdeva you're right please accept my request. 
Thanks

**Comment by ebarry** [comment] 2021-04-05 16:17
I just approved 4 people's requests in Transifex to localize in Hindi. I did not yet approve @YogeshSharma01 to localize in Spanish and Russian -- please let me know if you really speak those languages! thank you :))))

**Comment by YogeshSharma01** [comment] 2021-04-05 18:07
Hi, @ebarry Thanks for approval. No no not really I only speak English and Hindi languages actually i was just trying to figure out how this transfix is really working so i requested for other languages too and sorry for that.
😁 Thanks for approved my request in Transfix to localize in hindi.

**Closed** 2021-06-05 06:45 UTC
Labels: Translation System, bug, fto-candidate, help wanted, high-priority
