### ISSUE TITLE
Stats page bug

### ISSUE THREAD

**Issue by cesswairimu** [publiclab/plots2#5728] opened 2019-05-15 20:00 UTC
A couple of things looking off on the stats page https://publiclab.org/stats. Font a little huge, back and front arrows not aligned correctly plus wierd gray background, needs more spacing between the sections, question asked vs question answered bar graph not showing one side percentage

**Comment by jywarren** [comment] 2019-05-16 22:58
Yes, this probably needs a little post Bootstrap-4 work!

**Comment by cesswairimu** [comment] 2019-05-26 21:17
### Solution 
On https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb
- Change `h5`'s  to `h6`'s.
- Change  `h4`'s to `h5`' s.
- Change `class="btn btn-secondary"` to `class="btn btn-default"` on line 118, 127, 134, 140,151, 162, and 169.
- Move https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L114 after the `<% end %> `on line 112
- Change https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L115 to `<div class="col-lg-4 offset-lg-1">`

On https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb
- Change line 1 to  `div class="col-lg-12 offset-col-lg-1" style="margin-bottom:20px; margin-left:25px;">`
- Change `h5` on line 6 and line 13 to `h6`
- Change `h4` on line 7 to `h5`

**Comment by AnshitaVishwa** [comment] 2019-05-28 18:12
@cesswairimu and @jywarren I want to work on this issue. Should i start working on it?

**Comment by cesswairimu** [comment] 2019-05-28 18:15
Hi @AnshitaVishwa, Benjamin was interested in this.
@skilfullycurled did you already get started on this or can @AnshitaVishwa go ahead?

**Comment by skilfullycurled** [comment] 2019-05-28 19:02
Hi everyone, I was out of town and just got back yesterday so I haven't had a chance to work on it.  @AnshitaVishwa, why don't we check back in this Friday and if I haven't been able to start work on it, then I'll pass it along to you.  Would that work?

**Comment by skilfullycurled** [comment] 2019-05-29 01:03
156, 170

**Comment by skilfullycurled** [comment] 2019-05-29 02:07
Correction to task list: add L156 and switch L169 for L170 in the following:

> Change class="btn btn-secondary" to class="btn btn-default" on line 118, 127, 134, 140,151, 162, and 169.

**Comment by skilfullycurled** [comment] 2019-05-29 02:37
Also, @cesswairimu, take a look at the attached image, what do you think about making the text in red look like the text in green? This would require:

I think this would require deleting the [title attribute in the chart] (https://github.com/publiclab/plots2/blob/989001db25cb20d9d1d559468c45efe4857f5488/app/views/stats/index.html.erb#L241)

Unfortunately, there does not seem to be a way to make the title underlined so we'd have to remove the `<u>` here:https://github.com/publiclab/plots2/blob/989001db25cb20d9d1d559468c45efe4857f5488/app/views/stats/index.html.erb#L33)

**Comment by skilfullycurled** [comment] 2019-05-29 03:05
Also, @cesswairimu, take a look at the attached image, what do you think about making the title text in the charts more consistent.

![Screen Shot 2019-05-28 at 11 04 01 PM](https://user-images.githubusercontent.com/950291/58526424-eba74500-819c-11e9-9727-d8adf941a1d3.png)

I've been playing around and it would require the following changes (I'm using the chart in [index.html.erb](https://github.com/publiclab/plots2/blob/master/app/views/stats/index.html.erb#L203) as an example, but the same changes (more or less) would have to be made to the chart in [_range.html.erb](https://github.com/publiclab/plots2/blob/989001db25cb20d9d1d559468c45efe4857f5488/app/views/stats/_range.html.erb#L188) :

1) ` fontFamily: 'Junction Light'` to the chart options here:

https://github.com/publiclab/plots2/blob/989001db25cb20d9d1d559468c45efe4857f5488/app/views/stats/index.html.erb#L209-L224

2) adding the following alignment and styles to the title section in chart options:
```
title: {
  text: "Popular Tags in this period",
  align: 'center',
  style: {
   fontSize: '24px',
   color: '#212529'
  }
}
```
https://github.com/publiclab/plots2/blob/989001db25cb20d9d1d559468c45efe4857f5488/app/views/stats/index.html.erb#L241-L243

3) Unfortunately, there does not seem to be a way to make the title underlined so we'd have to remove the `<u>` here: 

https://github.com/publiclab/plots2/blob/989001db25cb20d9d1d559468c45efe4857f5488/app/views/stats/index.html.erb#L33

**Comment by cesswairimu** [comment] 2019-05-29 07:59
Wow @skilfullycurled the center alignment looks great :tada: :tada: . Yeah sure lets go ahead and have the proposed version. Thanks

**Comment by skilfullycurled** [comment] 2019-05-29 17:41
@cesswairimu, I made the proposed changes but had another idea with regard to consistency.  I promise this will be the last one for this issue! : )

What do you think about moving the Q&A bar from above the download buttons to the area with the other charts?

<img width="769" alt="Screen Shot 2019-05-29 at 1 29 32 PM" src="https://user-images.githubusercontent.com/950291/58578699-62812400-8217-11e9-8014-8d93dc8e8cd9.png">

This will require moving the related code from _range.html.erb to index.html.rb.  Another benefit will be that all of the chart code will be in the same file as well.  I've already tested the changes and they work.

Two notes: 

1) While the bar looks wider than the bars below, the total graph is actually the same width.  It's just that the labels on the "Popular Tags" graph push the bars over.  I tried adding a label of Q&A to the Q&A chart but despite a bunch of options that I tried in apex charts API, I was not successful.  Not a huge deal.

2) The Q&A bar only says 100% questions because the "mark as answered" feature is no longer available due to the answers to comments migration in #4094.  Therefore my local version cannot create any accepted answers.

**Comment by cesswairimu** [comment] 2019-05-29 18:43
Yeah @skilfullycurled yeah that would be great and am open to more changes no worries :smile:. 
Actually you do not need to move the code from that file you can just move https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L26-L28 to after line 181. 

Also for the width diff we could change the div to something like
```
<%if @questions.present? %>
   <div class="col-md-10 offset-md-1" id="chart2"> </div>
<% end %>
``` 
or tweak the width percentage https://github.com/publiclab/plots2/blob/master/app/views/stats/_range.html.erb#L192 to see if it gives a better alignment.

Hope any of the two is helpful.
Thanks.

**Comment by skilfullycurled** [comment] 2019-05-29 19:04
Thanks @cesswairimu, I obviously hadn't thought of that!  Since I already moved it do you have any objection to putting it with the other charts in index.html.erb (or moving the other charts to _range.html.erb)?  After I moved it, I thought it might be good to have them all in the same place.

I'll try your div suggestion regarding the width.  I already tried the width percentage but the problem is that because the chart starts all the way to the left, it just gives the appearance of a bar that doesn't go as far to the right.  So, that would work if the cart itself can be centered which I was unable to find in the chart API, and I'm not sure how to do in CSS such that it is still responsive and is within best practices (i.e., not a special inline style).  But if you know how to center the graph, then I think this would work.

**Comment by cesswairimu** [comment] 2019-05-29 19:35
Gotcha, I remember there was a graph offset feature for the axis maybe that could help. Cannot rem correctly how that worked but you give it a try https://apexcharts.com/docs/options/xaxis/

**Comment by jywarren** [comment] 2019-05-29 20:13
Hi all, really cool seeing this discussion and collaboration! Keep up the
awesome work!

**Comment by ebarry** [comment] 2019-05-30 19:22
Hi all, 
Loving this page and the graphs look great!

On the "Choose a Start Date" interface, could we add the exact start date of our website as a "quick pick" OR perhaps make an option to choose "for all time" as the period of inquiry? I'm causing errors by guessing at the start date when i just need a "for all time" result. 

Also, the lead text is "5638 research notes have been posted by 1437 contributors since over 8 years ago" but i hardly ever need this information whereas i often need "how many **total unique contributors**," which is nowhere on the page. Could we add this? Thank you!

**Comment by skilfullycurled** [comment] 2019-05-31 01:02
Hey @ebarry, yes, will do, I'll probably move them into new issues since I'm almost finished with this one and it was more about fixing the design changes that came from the bootstrap update.

Looks like you edited your text but regarding the download "for all time" part, that's in the works via downloadable pre-built 6 mo. csv's.  Also, there are some dates in there which for some reason cause and error and we're still trying to figure those out.  There are issues for both of those somewhere.

**Comment by skilfullycurled** [comment] 2019-05-31 01:06
@ebarry two issues you might be interested in are #5524 and #5490.  If you have any info/opinions on either please write in.  Especially the page causing errors issues.  I'm trying to track down any dates which are a problem.  If you look in the one about that, you'll see there's a date in there which we know is one which causes issues.  I think it's April 25, 2013...or maybe the 24th...

**Comment by skilfullycurled** [comment] 2019-05-31 23:42
Okay, well, I tried both of the things you suggested @cesswairimu, but for various reasons they did not work (happy to elaborate if you'd like).

What did work is `align="right"` and then a `width: '91%'` in the chart like so (note: the 100% inside the bar looks off center but this will change when there are actually answers to the questions):

```
<h4 align="center">Questions Asked vs. Answered</h4>
    <div align="right" id="questAns"> </div>
<% end %>
```

```
var options = {
    chart: {
        type: 'bar',
        height: 120,
        stacked: true,
        stackType: '100%',
        width: '91%',
    },
```

![Screen Shot 2019-05-31 at 7 30 07 PM](https://user-images.githubusercontent.com/950291/58739887-fea75880-83da-11e9-955e-0b23563c7d21.png)

So, if you want to go with that, we could do it.  It's sort of hack-y though.  But I'm good with it if you are.  Like I said, who knows, the chart might change anyway due to the new Q&A changes (which if you want to weigh in on has been moved to #5478).

**Comment by skilfullycurled** [comment] 2019-06-07 19:43
@cesswairimu, when you have a moment, can I get your feedback on my solution above?  That will allow me to either switch it back or keep it so that I can complete the PR request.  At your leisure.  Thanks!

**Comment by cesswairimu** [comment] 2019-06-07 20:05
Sorry @skilfullycurled didn't see this... :point_up: the graphs looks great. Am good with your fix. Thanks

**Comment by skilfullycurled** [comment] 2019-06-07 20:14
Awesome, thanks for your help @cesswairimu, will push commits to my branch and update PR request.

**Comment by cesswairimu** [comment] 2019-06-07 20:15
Great :+1:

**Closed** 2019-06-10 18:38 UTC
Labels: HTML, UI/API improvements
