### ISSUE TITLE
Follow up bugs in new designs of All sections including Profile,Tags, People etc

### ISSUE THREAD

**Issue by CleverFool77** [publiclab/plots2#6097] opened 2019-08-02 15:28 UTC
- [ ] Fix unequal margins/paddings in the featured questions cards on shadow interface https://github.com/publiclab/plots2/issues/6092
- [x] Mismatch working of Subscribe and `Subscribe to answer questions on this topic` in Individual tags page @CleverFool77 
- [x] Side-wrap up in tab issue
- [x] x more posts link fix @CleverFool77 
- [ ] renaming tags id fix -mismtach @Anupam-dagar 
- [x] Sidebar major fix and change to `...` @CleverFool77

**Comment by CleverFool77** [comment] 2019-08-03 07:27
Hi @jywarren @gautamig54 I had a doubt regarding this - 
In the one main card of Individual Tag page , we have a subscribe button but when I click on the button, it shows related tag, but not let us subscribe to that particular tag. We are only able to subscribe to related tags and not the main tag whose Individual page we are on. 

Instead we have another button below called ` Subscribe to answer questions on this topic`. And this button is the one which lets us subscribe to tag.

![Screenshot from 2019-08-03 12-53-11](https://user-images.githubusercontent.com/26685258/62408943-b7616200-b5ed-11e9-8d0e-7e9bac75a16a.png)

This should be fixed right ?  Or Is it going to be like this only.

**Comment by jywarren** [comment] 2019-08-03 12:40
No I think you're right, it should be fixed!

**Comment by CleverFool77** [comment] 2019-08-03 13:04
Cool!! I'll fix it.

**Comment by gautamig54** [comment] 2019-08-04 16:44
On the individual tags page, for a few tags, the content on the side bar shifts to the bottom. Whereas the page seems to be divided properly. 

![Screen Shot 2019-08-04 at 10 12 37 PM](https://user-images.githubusercontent.com/35326753/62426646-28e00400-b705-11e9-9f39-04152197b92c.png)

**Comment by gautamig54** [comment] 2019-08-04 17:04
I think this happens when there are tab content. With no tab contents, it displays it on the right side only. 
Can you also generate this issue @CleverFool77?

**Comment by CleverFool77** [comment] 2019-08-05 06:54
Can you write down specific points of generating this Issue, I tried it in
3-4 tags but I'm unable to generate this.

**Comment by CleverFool77** [comment] 2019-08-05 07:42
Hi @gautamig54 I was able to reproduce this Issue. I'll try fixing it. Cool.
Thanks !!

**Comment by gautamig54** [comment] 2019-08-07 09:50
Hi @CleverFool77. I think the problem is with the questions tab. It is working fine for wikis and posts

**Comment by CleverFool77** [comment] 2019-08-07 10:58
Hi @gautamig54 I checked it, Its pretty similar to matter when we have the side-wrap issue in tag page without login. I saw that the col-3 sidebar is going out the row class and thus its wrapping up in tab-content. Instead both of them should be inside the div of row class. So I'm checking and trying to work it out.
Thanks !!

**Comment by gautamig54** [comment] 2019-08-08 06:58
Hi @CleverFool77! Should we make a separate issue for correcting the responsiveness of pages?

**Comment by CleverFool77** [comment] 2019-08-08 07:32
No need to piling up issues I guess. Juts adding in this checklist would be
ok according to me.
Thanks !!

**Comment by CleverFool77** [comment] 2019-08-09 12:46
If you wanna add a new feature then opening an issue would do, In bug we can just checklist here for now ?

**Comment by gautamig54** [comment] 2019-08-09 14:09
Sure @CleverFool77 !

**Comment by CleverFool77** [comment] 2019-08-12 11:33
Hi @gautamig54 @jywarren 
Found this - 
I clicked on question and found this -
![Screenshot from 2019-08-12 17-02-05](https://user-images.githubusercontent.com/26685258/62862274-15472580-bd23-11e9-8113-f866f6faddc5.png)

**Comment by CleverFool77** [comment] 2019-08-12 11:34
Maybe this is related to Individual tags page ?

**Comment by CleverFool77** [comment] 2019-08-12 11:38
I saw the unstable and I don't see any map here. What could be the reason ?
As much as I know, even if the location is not added, a map should be still there. ??

![Screenshot from 2019-08-12 17-07-24](https://user-images.githubusercontent.com/26685258/62862556-c77eed00-bd23-11e9-8a92-75d336fc6924.png)

**Comment by jywarren** [comment] 2019-08-15 15:06
@ebarry @steviepubliclab  how do you feel about the functionality of the `Subscribe` button opening a dropdown with not only the tag itself but other related tags, in a "multi-subscribe" function, as in the screenshot above (https://github.com/publiclab/plots2/issues/6097#issuecomment-517902584)? (on tag pages)

This made sense in other places, but now that the tag page is kind of the lead page for a topic-based forum, maybe it should just subscribe you to the tag itself, and if you're subscribed, show `unsubscribe`? Or do we like this multi-subscribe? 

The simpler subscribe/unsubscribe is shown on the /tags page, for comparison:

![image](https://user-images.githubusercontent.com/24359/63104299-b7962180-bf4c-11e9-9ca7-5c85228aa34a.png)

**Comment by jywarren** [comment] 2019-08-15 15:07
Versus on the tag page now:

![image](https://user-images.githubusercontent.com/24359/63104340-d1376900-bf4c-11e9-9cbc-a47ca817b78a.png)

**Comment by jywarren** [comment] 2019-08-15 21:06
Hi! One more I noticed - -perhaps the "X more posts" links in the profile page tag cards should go not just to the tag page, but to the page showing tagged content by that author:

https://publiclab.org/profile/warren

so, to https://publiclab.org/tag/community-atlas/author/warren for example. What do you think?

**Comment by CleverFool77** [comment] 2019-08-16 06:16
Hi @jywarren 
I found another thing !!

I saw what you wrote about link ! and opened a PR on this !!
But I have one doubt !!
When I clicked on the link, its showed `3 more posts`  but when I clicked on it, the directed link to list of posts doesn't show those three posts ..

![li](https://user-images.githubusercontent.com/26685258/63147315-525d3180-c01b-11e9-9bad-186aa11ec10d.gif)


Here is full page of new directed page !!

![Screenshot from 2019-08-16 11-45-34](https://user-images.githubusercontent.com/26685258/63147333-64d76b00-c01b-11e9-8790-d0ca344e894f.png)

The post count for that tag is for profile user only and couldn't be wrong. So I was wondering where the bug and problem would be ?

**Comment by jywarren** [comment] 2019-08-16 15:31
Oh hmm, how odd. What you can try is to do this locally and watch your
rails console output to see if the queries differ. Or you could trace
through the code to see how each is calculated?

**Comment by CleverFool77** [comment] 2019-08-17 03:37
I'll try this.
Cool.

**Comment by CleverFool77** [comment] 2019-08-17 12:48
There is another bug here !!
I have used the tags bu there isn't any note being shown in these topic cards !!

![Screenshot from 2019-08-17 18-16-24](https://user-images.githubusercontent.com/26685258/63211897-42c51200-c11b-11e9-8d17-0d05860cd329.png)

**Comment by CleverFool77** [comment] 2019-08-17 12:51
Hi @jywarren !!
We had discussed this earlier but Is it still ok to have this much repetition of the notes ?
Like as we can see in screenshot that one of the notes is being repeated a lot. And As I haven't used much tags, so repetition wasn't much compared to a condition when we will have lots of tags in one note.

![Screenshot from 2019-08-17 18-18-43](https://user-images.githubusercontent.com/26685258/63211923-95063300-c11b-11e9-8eeb-b36de1b60ec5.png)

![Screenshot from 2019-08-17 18-19-02](https://user-images.githubusercontent.com/26685258/63211924-95063300-c11b-11e9-8fc8-637053b31d1a.png)

**Comment by jywarren** [comment] 2019-08-19 14:53
Ah, so this might need the same kind of "tagCard(tagname, excludeNids)"
template helper as where we've discussed elsewhere, that includes some kind
of parameter of [1,2,3] nids to exclude from displaying, that would have
been displayed higher up?

**Comment by ebarry** [comment] 2019-08-19 20:53
Back to the multi-subscribe dropdown currently offered on a specific tag page, i agree with your idea that perhaps it should just be subscribe/unsubscribe as shown on the top-level /tags page.

**Comment by jywarren** [comment] 2019-08-19 22:25
I was also interested in changing the 2-page icon to a `...` -- i'm sorry if i missed the discussion on that one! 

![image](https://user-images.githubusercontent.com/24359/63303744-b64b5880-c2ae-11e9-8ef5-9482f6f2a35d.png)

That's a pretty simple one if folks are OK with it?

**Comment by ebarry** [comment] 2019-08-19 22:49
sure!
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by CleverFool77** [comment] 2019-08-20 10:53
Sure @jywarren @ebarry I'll fix these bugs !!
Thanks !!

**Comment by CleverFool77** [comment] 2019-08-27 14:25
Hi @jywarren Regarding the 2 page icon to `...`. What's the position of `...` icon ? Is it a same position of 2-page icon? is it besides the title of notes as per the draft design ?

![63303744-b64b5880-c2ae-11e9-8ef5-9482f6f2a35d](https://user-images.githubusercontent.com/26685258/63779149-b1685380-c903-11e9-8faf-1a8b2042b722.png)

![Screenshot from 2019-08-27 19-52-54](https://user-images.githubusercontent.com/26685258/63779523-4ec38780-c904-11e9-9361-423f30d9ebf3.png)

But the modal shown after clicking on `...` icon on draft is not print page modal rather its different and consist of data from notes like views and etc. 
So does that mean we'll have two `...` in same page ? which are - 
* One in sidebar with modal of print page
* Another in note with details of notes hidden behind this button and opened on modal only when clicked.

**Comment by jywarren** [comment] 2019-08-27 14:27
Hm, that's a good point. Shall we try to combine the two into a single ...
menu in the sidebar, alongside the other circle buttons?

**Comment by CleverFool77** [comment] 2019-08-27 14:48
Hi @jywarren 
We can combine it but I'm not sure how it would look all-together. As both of them have different information. 
* one of them shows print option
* And another shows the views, comments etc. 

I'm not sure how we gonna Combine these two - ??
![Screenshot from 2019-08-27 20-17-16](https://user-images.githubusercontent.com/26685258/63781697-bf1fd800-c907-11e9-8ce1-4c702bde1b91.png)
![Screenshot from 2019-08-27 20-17-26](https://user-images.githubusercontent.com/26685258/63781698-bfb86e80-c907-11e9-8302-7ce3e8daa708.png)

Instead; having two icon buttons , one of them at side of notes-title and another on sidebar looks much better.

**Comment by CleverFool77** [comment] 2019-08-27 14:48
cc: @gautamig54 What's your views regarding this.

**Comment by CleverFool77** [comment] 2019-08-27 14:50
Or should we change the icons ? Let one them have `...` and have a different one for second one ?? Maybe we can have a `print icon` https://fontawesome.com/v4.7.0/icon/print for 2-page icon ? And for the info regarding the notes like views,comments. We have `...` icon.

**Comment by jywarren** [comment] 2019-08-27 14:52
How about:

* we compact the barnstar item to 1 line if possible
* we remove the header section of "More tools" etc
* we have a horizontal divider so the views, revisions, talk, can all go at
the top
* some, like comments, permalink, and views, could be made into simply
icons, like comment-bubble, "chain link" icon, and "eye" icons, on a single
line, to save space? Also Delete could be a trash can.

Could that help?

**Comment by CleverFool77** [comment] 2019-08-27 14:57
Ohkk !! This seems fine. And So to put barn-stars in one line; We can have a button and we can have dropdown along with it for various kinds of barnstars. 
We all just this much portion in button and dropdown -
![Screenshot from 2019-08-27 20-26-34](https://user-images.githubusercontent.com/26685258/63782437-05296b80-c909-11e9-88f1-500729dee716.png)

And rest would would be -
 information like views, comments etc...

And other extra stuff would be removed.

**Comment by CleverFool77** [comment] 2019-08-27 14:58
What about the position of button ? Its looks fine and cool below notes title .. is it ?

**Comment by CleverFool77** [comment] 2019-08-27 14:59
I'll take this issue up and resolve this,
Thanks !!

**Comment by jywarren** [comment] 2019-08-27 16:12
I guess I imagine it may be more naturally placed next to the other circle
buttons.

Just watch out that we should try to have this reflected on the
notes/questions pages, but the wiki page too!

**Comment by CleverFool77** [comment] 2019-08-27 17:55
Sure. I'll see it all pages including notes,wikis, questions etc.
Thanks !!

**Comment by simonastefan** [comment] 2019-08-28 12:52
Hi, I think I found an issue related to the new UI changes. On the Profile page, a new tag is not longer added to the list of user tags but it shows at page reload.

I looked into it a bit to fix it but now I am not sure how. It seems that the JS code relies on the "tags" id and the same id was also used to the most common tags section.

**Comment by CleverFool77** [comment] 2019-08-28 13:05
Ohh !!! So Renaming tags id would do ?? I'll check into this.

**Comment by Anupam-dagar** [comment] 2019-08-28 13:08
Hi, I would like to take up renaming of the tags id.

**Comment by CleverFool77** [comment] 2019-08-28 13:33
Hi @Anupam-dagar Sure. And one more thing. There would be uses of tags id in js too, you need to keep that in mind too.
Thanks !!!

**Comment by ebarry** [comment] 2019-08-29 17:31
Hi @CleverFool77 !
Very much enjoying all the new UI features 🤗 

I'm wondering if it is the goal to eventually have the list of contributions by type that's shown on profile pages be **linked** to the actual content? For instance, shown in this screenshot, the grey text is not clickable, meaning that to the best of my current understanding, there's no way to see what someone has contributed from their profile page which, i feel, should be possible: 

<img width="254" alt="Screen Shot 2019-08-28 at 4 04 41 PM" src="https://user-images.githubusercontent.com/161439/63962501-fce44400-ca60-11e9-8f52-17bc32fca563.png">

Also i'm wondering if it's intentional that the word "asked" appears after the username? 
Thank you!

**Comment by CleverFool77** [comment] 2019-08-29 17:44
Hi @ebarry  i intentionally added asked as per the style guide. Regarding
clickable thing. It's not visible, like hover or other feature. But While
changing the Ui, I didn't remove the link in them. So we do reach on
different pages after clicking on it. Notes, questions, activity posted and
attempted are working.
Wikis don't work because we usually don't have another page for list of
Wikis which have been edited i guess.

Also, we did had a list of Wikis to be shown in profile page earlier in
right bottom corner of Page. But we don't have this anymore
So should we add this? Or maybe do some Refinements to ui.

I'll look into comments matter.

Right now, I'm working on adding all Info of note and print feature into
one dropdown PR. I'll most probably complete the final Patch soon in a day
. And after that I'll look into it.

**Comment by gautamig54** [comment] 2019-08-30 06:38
Hi @CleverFool77! I notice some bug here on the tags page. 
Also, here teh subscribe and the learn more button doesn't work. 

![Screen Shot 2019-08-30 at 12 06 08 PM](https://user-images.githubusercontent.com/35326753/63998370-93c30600-cb1e-11e9-9168-9d84573742ee.png)

I see its working fine for other tags like air-quality : 
 
![Screen Shot 2019-08-30 at 12 07 17 PM](https://user-images.githubusercontent.com/35326753/63998436-b81ee280-cb1e-11e9-8ab2-7ee03900eef9.png)

**Comment by CleverFool77** [comment] 2019-08-30 07:05
Hi @gautamig54 The bug is not in `subscribe` button rather its the distortion because of huge content for that particular tag. If you would have noticed than you must have seen that we are able to subscribe other tags. 

And I've recently updated the subscribed button work. As earlier, we are just able to subscribe to `related-tags` but not that actual tag. So It will be updated soon when it get pushed to production.

To fix this bug, we can limit the content of a particular tag to be shown in the main card of that individual tag page.

**Comment by gautamig54** [comment] 2019-08-30 07:08
That content is limited to 2 lines as you can see in air-quality tag.

**Comment by CleverFool77** [comment] 2019-08-30 07:12
ohk Cool. So bug is somewhere else. But not in button I guess. Is there any other pages which you have seen with same bug ? of not able to subscribe ?

**Comment by jywarren** [comment] 2019-08-30 16:56
Hm, is it limited by # of newlines, or # of characters? Could this just be
a really really long paragraph?

**Comment by CleverFool77** [comment] 2019-08-31 16:46
Hi @gautamig54 As jeff asked, did you add limit by newline ?

**Comment by gautamig54** [comment] 2019-08-31 22:40
Yes. I have limited the content by the number of lines.

**Comment by SidharthBansal** [comment] 2019-09-03 15:22
This is really amazing piece of work folks. Super thanks

**Comment by jywarren** [comment] 2019-09-05 19:07
Oops, re-opening! Also, we found this one, could be related to #6027  perhaps...

![image](https://user-images.githubusercontent.com/24359/64371546-ce311500-cfee-11e9-94e1-c9d273e0eaee.png)

The URL is https://publiclab.org/tag/activity:*/author/mimiss

Thanks!!!

**Comment by jywarren** [comment] 2019-09-11 15:01
I noticed the edit button in the new sidebar is not visible in mobile-width devices. Could there be a relatively quick fix for this?

**Comment by SidharthBansal** [comment] 2019-09-13 16:01
Great Lekhika!

**Comment by jywarren** [comment] 2019-09-23 19:33
I think i've got the edit button fix in my big new PR here: #6322 -- lots of fixes there!

**Comment by CleverFool77** [comment] 2019-09-24 10:39
Thanks for the fix @jywarren .
My exams has ended finally. I'll look for other fixes in the design.
Thanks !!

**Comment by jywarren** [comment] 2019-09-24 17:07
awesome. I'm working on a lot of smaller items in #6326! I'd love help with
the weird ones with the wildcard tags, where the tag card is going a bit
out of control. And the one where there's a big space below the tag card on
/tag/____ on mobile devices!

**Comment by jywarren** [comment] 2019-09-24 21:26
Aha - ok, now the tag page header cards are really in bad shape, and I think I found the issue. These lines set percentage-based positioning, and the use of `row/col` is a little odd within the card:

https://github.com/publiclab/plots2/blob/02b44b9daafc1ec0e8bc4f4dbb1f575ed7587336/app/views/tag/show.html.erb#L73-L126

If you are able to do some reworking of this, please do, and we'll try to rush it into production late tonight or early tomorrow. 

![image](https://user-images.githubusercontent.com/24359/65551637-57ea4900-def0-11e9-81a9-7bffa9810ea0.png)
![image](https://user-images.githubusercontent.com/24359/65551674-67699200-def0-11e9-8d23-cbdb0df72eac.png)

I think we should set `top: 70px` and redo the `row/col` code there. That should address a lot of the other issues with that card as well!

**Comment by jywarren** [comment] 2019-09-24 21:48
That is, the `wiki-sub` and `tag-buttons` should be in their own `<div class="row">`, i think!

**Comment by jywarren** [comment] 2019-09-24 21:50
Quick attempt here: https://github.com/publiclab/plots2/pull/6328

**Comment by jywarren** [comment] 2019-09-25 02:30
Continued work here: https://github.com/publiclab/plots2/pull/6330

I am still not getting the background to show up on mobile screens:

![image](https://user-images.githubusercontent.com/24359/65564409-cba14b80-df1a-11e9-8d75-17a524ce6127.png)

But everything else is relatively better organized and with fewer custom styles. There are still some custom `.card` styles however, in `/app/views/notes/_notes.html.erb` -- I'd prefer to go with strict Bootstrap styles as much as possible, as it helps avoid the kinds of unexpected layout issues we're seeing here! https://getbootstrap.com/docs/4.3/components/card/

**Comment by jywarren** [comment] 2019-09-25 13:26
Oof, made it even worse in some scenarios. It's very strange that there are differences between stable, local, and production!

![image](https://user-images.githubusercontent.com/24359/65605062-73983280-df76-11e9-8321-e1f96a7340b6.png)

**Comment by jywarren** [comment] 2019-09-25 20:43
OK, did some more work on this, and the latest changes are publishing to the live site now!

**Comment by jywarren** [comment] 2019-09-25 21:34
Lots of pages look much better now!!!

**Comment by jywarren** [comment] 2019-09-27 22:34
I believe this is complete now. Any last follow-ups?

**Comment by CleverFool77** [comment] 2019-09-30 03:46
I guess this is ready.
Thanks @jywarren !!!

**Closed** 2019-09-30 14:30 UTC
Labels: bug, design
