### ISSUE TITLE
Login modal shows up abruptly

### ISSUE THREAD

**Issue by oorjitchowdhary** [publiclab/plots2#4348] opened 2018-12-21 10:04 UTC
### Please describe the problem (or idea)
When clicked `link a location` button on a particular page, the map shows up the the usual way but the login modal is displayed behind it.
This is happening when the user is logged in.

> What happened just before the problem occurred? Or what problem could this idea solve?

![login modal abrupt error](https://user-images.githubusercontent.com/39333058/50337003-c8b19e80-0535-11e9-80a4-657178ddffff.gif)

> What did you expect to see that you didn't?

The login modal shouldn't have appeared.

### Please show us where to look

https://publiclab.org/notes/bryanchua/12-18-2018/hydro-powered-diy-ftir-spectrometer

### What's your PublicLab.org username?

oorjit_chowdhary

### Browser, version, and operating system

Chrome, Windows 10

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment] 2018-12-21 10:06
@publiclab/mentors This should be looked into quickly as we have released it on PL...

**Comment by jywarren** [comment] 2018-12-21 13:41
Yes, thanks!!! It'll be related to the z-index css value!

**Comment by gauravano** [comment] 2018-12-23 07:41
Hi @oorjitchowdhary would you be interested in solving this one?

**Comment by kevinzluo** [comment] 2018-12-26 02:38
The issue is with https://github.com/publiclab/plots2/blob/fefa4aa7ed91776a7b1b25902e804089de2f9d89/app/views/tag/_location.html.erb#L14-L15

The selector targets both the blurred location modal and the new login modal. We need to make it select only the blurred input modal. @oorjitchowdhary would you like to fix this?

**Comment by SidharthBansal** [comment] 2018-12-26 11:02
I have assigned this issue to Oorjit. Kevin is helping him and this is great appreciated.
Thanks

**Comment by oorjitchowdhary** [comment] 2018-12-26 13:31
Hi, @SidharthBansal .. I'm really sorry I won't be able to complete this one. I'm gonna be off laptop for a while as I'm on a vacation.

**Comment by kevinzluo** [comment] 2018-12-26 13:37
No worries @oorjitchowdhary . I will try to submit a fix then.

**Closed** 2018-12-27 15:52 UTC
Labels: bug, in progress
