### ISSUE TITLE
Weekly Community Check-In #10 - "Trespassing Boundaries"

### ISSUE THREAD

**Issue by IshaGupta18** [publiclab/plots2#4844] opened 2019-02-18 04:36 UTC
Hi everyone  :wave: !

We all at Public Lab  :balloon: - learn, grow, work, brainstorm ideas, contribute together so why not share about our weekly goals and the awesome work we have done at Public Lab with each other, so we can support and collaborate with each other better. The goal of our Community Check-In is for every community member to share something about their work from the past week and about their current week's goal :dart:  . You are also welcome to share fun-fact :smile:  , new ideas  :bulb: , your learning goals :ballot_box_with_check:  .

If you're new here, welcome :balloon: , and please comment a Hello message below, we love to work with you. If you're looking for new issues, please try some of our first-timers-only issues.

We're SO EXCITED to have your help!

Is there anything, you would like to share with us from past week's work? What is your plan for this week?

If you have not planned yet, just leave a Hello! so that we know that you are in sync with us :arrows_clockwise:   and doing well!

As always, if you're waiting for a review, or if you're stuck, you can request help here, leave a comment on your issue with @publiclab/reviewers mentioned, or ask the community in our [Gitter](https://gitter.im/publiclab/publiclab) chatroom :open_hands:  .

### Gitter
Gitter is an active chatroom in our community and we'll be sending weekly reminders about check-ins there. Be sure to sign up there for these updates or just to join the conversation :pager: .

### This Week's Theme

I thought of making this week’s theme on “Trespassing Boundaries”. By working as contributors to Public Lab, many of us get inclined to solve some particular kinds of issues and that becomes our comfort zone. I think it’s time we move out of it and explore tons of other stuff out there! We can do this by collaborating with someone on a PR towards a project or by simply helping them debug. This not only enhances our knowledge of the codebase but also interests us towards new technologies. I would encourage new contributors to try different kinds of [FTOs](https://github.com/publiclab/plots2/issues?utf8=%E2%9C%93&q=first-timers-only) and [help-wanted issues](https://github.com/publiclab/plots2/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22). Since open source is all about community and helping others, let's find some issues which might be good for someone else who is contributing or just beginning and help them solve it. Let’s expand our community as much as we can! :tada: 

### Summer of Code
@jywarren has started a brainstorming post for the ideas page for Summer of Code 2019 -It would be best to get some ideas into the discussion from the fellow community member before time. People have been brainstorming already - let's do it together!
https://publiclab.org/notes/warren/01-02-2019/brainstorming-for-summer-of-code-2019
And this is the official idea’s page:
https://publiclab.org/wiki/gsoc-ideas 

### Software Contributors Survey
This survey is conducted on a yearly basis to improve our experience.
https://goo.gl/forms/4VVMO8dOijRj6BUA3
The form will remain open until early March, but don't wait to respond! This one’s for us!

### MapKnitter

Some great planning and discussions are going on in our MapKnitter repo, do check them out! We are welcoming new contributors there as well, so anyone is welcome to chime in!

cc
@mohitRJranjan @milaaraujo @kevinzluo
@stefannibrasil @gauravano @ViditChitkara @tech4GT @mridulnagpal @namangupta01 @sagarpreet-chadha @Souravirus @MayankKashyap @siaw23 @ryzokuken @icarito @steviepubliclab @ebarry @jywarren, @sagarpreet-chadha, @JonathanXu1, @uzorjchibuzor, @eli6, @ValentinaTironi, @rexagod, @sashadev-sky, @IshaGupta18, @dinaelhanan, @cesswairimu, @dependabot[bot], @oorjitchowdhary, @okonek, @wanzulfikri, @mohitRJranjan @publiclab/mentors @publiclab/image-sequencer-guides @publiclab/leaflet-environmental-layers-guides @Paarmita @publiclab/reviewers @Divy123 @bhavayAnand9 @Mridul97 @avsingh999 @Rishabh570 @aSquare14 @hydro-m @love-opensource @romanrodriguez @Dhiraj240 @geekychaser @codeIriss @CoderJolly @rishabhc32 @chirag-singhal @Saurabh19126848_twitter @IgorWilbert @dhruvgupta167 @vrk99 @pdurbin @dave-light @shubhscoder @HarshKhandeparkar @aashna27

Thanks and keep contributing! Contributing to Public Lab means contributing to the Environment.    

People who did the check-ins-
Gaurav Sachdeva (@gauravano )
Sidharth Bansal (@SidharthBansal )
Cess (@cesswairimu )
Harman Jolly (@CoderJolly )
Rishabh Rawat (@Rishabh570 )
Sasha Boginsky (@sashadev-sky)
Rishabh Kr Bothra (@geekychaser)
Shubham Sangamnerkar (@shubhscoder)
Siddhant N Trivedi(@sidntrivedi012)
Isha Gupta (@Ishagupta18)
Have a great week everyone :balloon: :tada: :sparkler:

**Comment by jywarren** [comment] 2019-02-20 01:07
Hi @IshaGupta18 thanks so much for your great welcome and check-in!

I wanted to share some work i was doing in the [Leaflet Environmental Layers](https://github.com/publiclab/leaflet-environmental-layers) library that is exciting to me. I've cleaned up some of the issues, merged a PR, and added some documentation, as well as updated the `gh-pages` demo. It remains an exciting project that has a lot of promise! 

We've been cleaning out and expanding a lot of our libraries recently and this is a cool one. I especially wanted to point out this interesting issue I crafted for making a new Leaflet library from the Spreadsheet-to-Map function @kevinzluo built during GCI: https://github.com/publiclab/leaflet-environmental-layers/issues/121

Thanks everyone and hope exams are going well for those who have them!! 🎉 💯

**Comment by sashadev-sky** [comment] 2019-02-20 02:19
Hi all,

This week I have finally settled the plots2 issue with the "likes" functionality not working properly and opened a PR #4852 for it. In the spirit of trespassing boundaries and working with others, I would love help in two areas on it: 

(Note I am just referring to the primary code changes - I will clean up my Gemfile, etc. later) 

1) **suggestions for refactoring** - I don't love the way I structured the solution but I had trouble thinking of other ways to do it that would be simple because it is so interdependent with a lot of other code. I would appreciate the opportunity to learn from a fresh perspective :)  

2) **testing - requesting mentoring** - I want to test the functionality of the likes buttons and that the database is updating accurately. The tests that were in place at the time I wrote the code were deprecated and also not organized properly.  I don't have prior experience testing front-end code so if there is someone willing to mentor me and help me write a few tests it would go a long way for me in both learning and actually starting to integrate testing into all my solutions

@VibhorCodecianGupta @aashna27 don't mean to cold call you two but I noticed you do a lot of testing work. Please check out the PR if you have time and let me know if either of you would be interested in working on this and letting me follow along. Thank you in advance guys!

**Comment by gauravano** [comment] 2019-02-20 08:17
Hi everyone!

Great check-in @IshaGupta18 and nice theme! 

I believe that if we want to achieve a goal or something, we need to get out of our comfort zone. Same goes for Open Source or self-learning, many contributors start with FTO issues, which are designed to be easy/welcoming but after solving some issues of any project(that make one familiar with a project a bit), one should definitely try to solve issues which they think of as difficult.

I learned a bit of testing and wrote my first test in plots2 only, and wrote API in production also here only. It took time to complete those issues but yeah, it feels great after PR gets merged :). So, I will advice everyone to claim an issue which they feel is difficult for them. Don't feel shy about asking silly questions/comments. (If you are having exams right now, try this out after exams)

**Week's goal**   
I would be busy with exams from this Friday to next one, so would be spending limited time contributing. I will try to upload our new file structure to Transifex and to make a testing URL with which translation prompt testing can be done in production.

Thanks and have a great week :smiley: :+1:

**Comment by cesswairimu** [comment] 2019-02-20 13:24
Hello all,

I just realized that I started with the `not so complicated` issues in my milestone.
So this week I am working on the issues I have been kinda avoiding :smile: 

Awesome theme @IshaGupta18 .
Thanks and have a great week ahead.

**Comment by RizwanSyed357** [comment] 2019-02-20 15:09
Hey all, I am thrilled to have discovered that Public Lab take part in the Outreachy scheme - after I made my first open source contribution to Public Lab (https://github.com/publiclab/infragram/pull/53).

I have applied to Outreachy and am now in the process of making open source contributions to hopefully secure an internship. I look forward to helping you guys on your Outreachy-listed project once it is up on the Outreachy website, and will be continuing to make open-source contributions regardless. 

<3 Public Lab 

Riz

**Comment by gauravano** [comment] 2019-02-20 15:42
Hi @RizwanSyed357, 

Glad to see that you were successful to complete your first OSS contribution with us. We would also love to have more contributions from you. 

Regarding Outreachy, it's not confirmed yet that Public Lab would be participating in upcoming Outreachy round or not, maybe @jywarren or @publiclab/community-reps can answer this. Keep tuned for alert and announcements. 

Last time,  there was a call for Outreachy proposals made - https://publiclab.org/notes/warren/10-23-2018/call-for-outreachy-2018-19-proposals, so you can signup to publiclab.org and subscribe to tags mentioned on above note like `outreachy`, `outreachy-2019`, etc. 

/cc @IshaGupta18 @jywarren

Thanks!

**Comment by ebarry** [comment] 2019-02-20 16:46
Hi everyone, 
This week, myself and ~60 other Public Labbers are convening in Texas: 
<img width="786" alt="flyer-texasbarnraising2019" src="https://user-images.githubusercontent.com/161439/53108474-b2f03380-34fc-11e9-9054-16b25cb8e47b.png">

Looking forward to the in-person discussions and connections to the software platforms we build together!

**Comment by jywarren** [comment] 2019-02-20 23:22
Don't worry @cesswairimu all your work to date will make it easier to tackle these last few! 

Regarding Outreachy, we are discussing it and will do our best to get an answer back soon! We are of course interested, so it is partly a matter of finding the funding. Note that we will also be applying to Rails Girls Summer of Code!

Thanks, everyone!

**Comment by Rishabh570** [comment] 2019-02-23 08:43
Hi everyone! Great theme :tada: :fireworks: 
For this week, I'll be looking into some of the refactoring stuff that is needed in community-toolbox. It is good to see our growing and active community, more & more people are getting involved in our projects day by day (469+ total contributors currently).

So for now, I've opened up a [roadmap](https://github.com/publiclab/community-toolbox/issues/141) for community-toolbox, most probably that will be the workflow for future enhancements...but that roadmap can be applied (most probably) to other PL libraries as well, so respective people can check it out :)

Happy to be a part of this :smile: :v:

**Comment by gauravano** [comment] 2019-02-23 12:53
Nice checklist @Rishabh570!

@jywarren I think there should be a dedicated documentation page for Public Lab projects too which can contain the flowcharts showing which PL libraries are utilised at which project like Leaflet, Editor, etc used at plots2 and so on. This will give the clarity to new-comers and they may be interested in contributing/improving the library too. What do you think?

Thanks!

**Comment by gauravano** [comment] 2019-02-23 12:53
Anyone interested in opening next week's check-in ??

**Comment by jywarren** [comment] 2019-02-23 13:48
Ah that's a great idea @gauravano! We have some diagramming issues and a
Google presentation we could build off of!

**Comment by IshaGupta18** [comment] 2019-02-23 13:51
Thank you all for liking the check-in! Hope all of you had a lovely week!

**Comment by gauravano** [comment] 2019-02-25 13:36
Hey everyone, I have opened a new issue at #4880 for showcasing project dependency chart/flow. Please chime-in whenever you are free. 

Also, new check-in open at #4879. Thanks!

**Closed by gauravano** 2019-02-25 13:36 UTC
Labels: community check-in, outreach

**Comment by jywarren** [comment] 2019-02-27 20:12
Hi, all - just reporting back on the Outreachy topic - we have been accepted to Outreachy! You can read more here and I'll be posting a welcome soon: https://www.outreachy.org/communities/cfp/public-lab/

**Comment by RizwanSyed357** [comment] 2019-03-02 11:41
Great to hear @jywarren , looking forward to making contributions as an Outreachy applicant

**Comment by SidharthBansal** [comment] 2019-03-02 12:42
Thanks @RizwanSyed357
