### ISSUE TITLE
Language translation in footer not functional

### ISSUE THREAD

**Issue by dongskyler** [publiclab/plots2#9055] opened 2021-01-20 21:51 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The language translation button in the footer is not functional. No matter what language is selected, English is presented. In other words, the "language" button does not do anything substantial. However, selecting a language does append a query parameter to the URL, such as `https://publiclab.org/?_=1611179421`. But the language of the website remains English.

> What did you expect to see that you didn't?

After selecting a language, the website is expected to be translated to the selected language.

### Please show us where to look

https://publiclab.org/

![image](https://user-images.githubusercontent.com/19198708/105245676-ccaab300-5b37-11eb-9ce4-0f1f8b70c58e.png)

![image](https://user-images.githubusercontent.com/19198708/105245701-d6341b00-5b37-11eb-8b20-d651f78c547b.png)

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

Did not login. This bug is irrelevant to login.

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

At the time of writing, the bug is demonstrated on the latest Chrome browser on macOS and the latest Safari browser on iOS and macOS. The bug is suspected to be present on all browsers across all platforms, because it is not believed to be a browser-side bug.

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by RATED-R-SUNDRAM** [comment] 2021-01-22 04:39
I would like to work on fixing this bug

**Comment by coder645** [comment] 2021-01-22 08:34
Please go ahead.
Cheers!

**Comment by sakshi-2412** [comment] 2022-01-18 07:48
As mentioned in #9405, the button is functional however very few things get translated. So, ig this issue should be closed. @TildaDares can you please confirm? Thanks!

**Comment by TildaDares** [comment] 2022-01-18 08:46
@sakshi-2412 The problem is not with the button. Some texts have not been translated to that language so some of them are still in English. So, you’re right about closing it. Thanks!

**Closed by TildaDares** 2022-01-18 08:46 UTC
Labels: bug
