### ISSUE TITLE
Missing Email Causes User to be Banned

### ISSUE THREAD

**Issue by nicoleiocana** [publiclab/plots2#6883] opened 2019-11-30 15:57 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

I attempted to log in using my username and password, then was prompted with the alert "that I was banned and if I believed this to be in error to contact the moderators." During my conversation with the moderators, they notified me that my email address was not associated with my username.

I was notified that the dev team was DM'ed my email address to keep it private.  I was also directed to mention @skilfullycurled to validate/verify this issue.

> What did you expect to see that you didn't?

The alert that I was successfully logged in.

### Please show us where to look

The Log In modal window

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

nicoleiocana

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

![chrome](https://user-images.githubusercontent.com/44947175/69902793-3f5e3b00-1346-11ea-8b65-8570c446001e.PNG)

![win10](https://user-images.githubusercontent.com/44947175/69902795-42f1c200-1346-11ea-8933-c869b2987f01.PNG)

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by skilfullycurled** [comment] 2019-12-02 17:22
Just chiming in here to add some information from the moderators point of view.

1) The email issue became appearant to us because when we tried to look up @nicoleiocana's using the email lookup in the moderation back end, the email could not be found.

2) However, once we had the username and I went to the profile page, @nicoleiocana's email *was* on the profile page *and* it was the correct email.

**Comment by skilfullycurled** [comment] 2019-12-02 17:39
Ah, I see why, seems like @nicoleiocana was testing something, and as this was the first post, I can see how that could be interpreted as spam-like.

https://publiclab.org/notes/nicoleiocana/11-09-2019/test-for-blank-tag

More importantly (and I'm embarrassed to say this), both @nicoleiocana's email and profile were correct in both the initial spam notification email and the post "marked as spam" conformation email (which is where we could have found it in the first place, that's the embarrassing part).

So my diagnosis would be that the banning and the email are unrelated and it may be limited to the moderator email look up function.

**Comment by jywarren** [comment] 2019-12-03 18:39
Not sure what might have happened, but I just double checked and was able to look up the account using the email:

![image](https://user-images.githubusercontent.com/24359/70079247-59ac4900-15d2-11ea-998d-fa286541eb7d.png)

I'm going to close this but if it happens again let's re-open and delve further in! Thanks, all!

**Closed by jywarren** 2019-12-03 18:39 UTC
Labels: bug

**Comment by skilfullycurled** [comment] 2019-12-03 21:07
Yes, but that could be because @nicoleiocana is no longer banned.

Does that functionality only work on active users?

**Comment by skilfullycurled** [comment] 2019-12-05 13:38
@jywarren, can you check out my question when you have a moment and reopen or keep closed accordingly?

**Comment by jywarren** [comment] 2019-12-05 19:46
Oh, sorry, i thought you'd be able to check with a banned user! I'll look
now at https://publiclab.org/people. Thanks!

**Comment by jywarren** [comment] 2019-12-05 19:48
So https://publiclab.org/profile/noomisoomi is banned, and indeed their
email did not manage to identify an account in the email search function.
Do you think it ought to, and we should open an issue for that?

**Comment by skilfullycurled** [comment] 2019-12-05 19:58
I don't think so.  Given the amount of spam we find and therefore users that are banned, the work wouldn't be proportional to the gain.  It's pretty rare that we have an error relative to the overall amount of spam we receive.  I think the important thing is that we've figured out that that this is a feature (albeit unintended) and not a bug.  Therefore, the "fix" is more knowledge based than programming.  I'll just send out an email to the moderators explaining that the only piece of information that can help in finding a previously banned user, is to have their username.

**Comment by skilfullycurled** [comment] 2019-12-05 20:08
Okay, I just emailed everyone.

@nicoleiocana, I know that the constant back and forth of the "are you sure this is your email..." contributed to the length of time it took to resolve the issue.  So while this knowledge comes too late to help you, you will have saved others the same trouble.
