### ISSUE TITLE
Move an integration test to integration test folder which is present in Unit test file [PART 6]

### ISSUE THREAD

**Issue by namangupta01** [publiclab/plots2#3433] opened 2018-09-24 19:22 UTC
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Currently some integration tests are present in unit test folder, so we can move them from this folder and add them to integration test folder.

https://github.com/publiclab/plots2/blob/faa03523b35ccaddd26f4bfc00a2c0bcce591b5b/test/unit/comment_test.rb#L260

**Comment by SidharthBansal** [comment] 2018-10-22 21:01
This task is published on GCI dashboard. Thanks all.

**Comment by kopecs** [comment] 2018-10-26 19:51
This issue appears to be a duplicate of #3432.

**Comment by namangupta01** [comment] 2018-10-26 20:00
Yes @kopecs you are right. Thanks for noticing.

**Closed** 2018-10-26 20:00 UTC
Labels: gci-candidate, help-wanted, refactorization, small
