### ISSUE TITLE
Improve navbar for short resolution or mobile view Part 3

### ISSUE THREAD

**Issue by avsingh999** [publiclab/plots2#3452] opened 2018-09-25 13:13 UTC
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### Problem
 
- Click on About us

 in this section when About us  Drop down then It also shows store option so there is twice store option

![store](https://user-images.githubusercontent.com/25272573/47339331-8811e200-d6b8-11e8-84c8-3bfb3d40811e.PNG)

### 📋Solution

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** 
remove extra store option
Code links….
https://github.com/publiclab/plots2/blob/fdf99c577d9ceeddc45c7726e9578d9af13418e0/app/views/layouts/_header.html.erb#L68

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by SidharthBansal** [comment] 2018-10-22 18:06
@avsingh999 @igniteeng000 please format the issue properly before posting them onto the GCI dashboard. The issue is not at all formatted as I have told you as per our code of conducts.

**Comment by jywarren** [comment] 2018-10-22 19:31
Ah, i think this is OK because it's `Store` versus `Stories` -- so we can close this. I don't think it's a code of conduct issue, just a small thing we got confused on! Thank you!

**Comment by jywarren** [comment] 2018-10-22 19:31
But yes, we will need lots of the GCI issues formatted so that newcomers can more easily solve them. Thanks, everyone!

**Comment by igniteeng000** [comment] 2018-10-22 22:32
@jywarren @SidharthBansal sorry for the confusion but actually we were talking about store not stories. On all smaller resolution, there is a redundant store option. I have updated the image. Please take a look.

**Comment by jywarren** [comment] 2018-10-22 22:37
Ah, ok! Can you find the line of code where we'd have to remove the smaller one? From this file? https://github.com/publiclab/plots2/blob/master/app/views/layouts/_header.html.erb

Thanks!!!

**Comment by SidharthBansal** [comment] 2018-10-23 09:59
Published

**Closed** 2018-10-24 15:36 UTC
Labels: design
