### ISSUE TITLE
Inconsistent log-in experience between browsers

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#11099] opened 2022-04-25 21:08 UTC
### Please describe the problem

> What happened just before the problem occurred? Or what problem could this idea solve?

Stevie logged in on Chrome, but after successful login was redirected away from the page she was on (www.publiclab.org/questions) and put onto the publiclab.org/dashboard: 

![login](https://user-images.githubusercontent.com/161439/165174690-c9a6ab12-3b3a-4ab0-a6c8-0a1ae75a915b.gif)

I'm not sure that the problem is differences between browsers, but that is at least a variable in this. 

> What did you expect to see that you didn't?

I expected to see what I see when logging in on the Brave browser on MacOS, that after successfully logging in via the popup menu, the menu closes and I remain on the page I was on: 
![logging in](https://user-images.githubusercontent.com/161439/165174857-f2f94d41-2ce6-4f8b-84d3-e468a36dc010.gif)

This is the ideal user experience. 

### What's your PublicLab.org username?
> This can help us diagnose the issue: 

liz
stevie

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Chrome on MacOS

**Comment by Forchapeatl** [comment] 2022-04-26 08:27
Great catch @ebarry  thank you.
@TildaDares please may I  work on this issue ?

**Comment by TildaDares** [comment] 2022-04-26 09:49
Hi @Forchapeatl, yeah go ahead.

**Comment by jywarren** [comment] 2022-04-26 18:32
Hi all! Thanks all and great documentation. I can see that Stevie clicked the "To ask a question, please log in or sign up" prompt, while Liz used the navbar Login button. The "To ask a question" link seems to be malfunctioning:

https://github.com/publiclab/plots2/blob/e211e63cf709141e1de86d996ad073f362e7ef68/app/views/questions/index.html.erb#L25

Here's the one in the navbar:

https://github.com/publiclab/plots2/blob/3433febd0bb33d701966a052321c78d2bd140ccc/app/views/layouts/_header.html.erb#L195

The navbar one is run using this code:

https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/app/views/user_sessions/_form.html.erb#L92-L96

What's supposed to happen is that any link with the class `requireLogin` should be connected up to actually open the modal (docs here: https://github.com/publiclab/plots2/blob/main/doc/LOGIN_SYSTEMS.md#how-to-setup-login-modal-on-various-locations)

The code running that is here: 

https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/app/views/user_sessions/_form.html.erb#L71-L79

I think we should first check that the `requireLogin` system is working normally. I think it's protected with system tests so i think it should be? But worth checking. Then, see if the link we've generated is working correctly - it should not only log you in but also redirect you back to the same page. 

The raw HTML generated for the bad link is here:

```html
<p>To ask a question, please<a href="/login?return_to=/questions"> log in </a>or <a href="/signup?return_to=/questions">sign up</a> 
          first.</p>
```

Does that look right? I think maybe... 


WAIT - ok Stevie actually pressed the CONTINUE button here:

<img width="572" alt="image" src="https://user-images.githubusercontent.com/24359/165367386-8d73b263-3322-42d2-8679-5d37ccdfd8b2.png">

So how is that triggering the login modal? 

It's in this inline JS code:

https://github.com/publiclab/plots2/blob/e646cfd248e46fe9cf11a2eb7860bbf29f949b7d/app/views/questions/index.html.erb#L84-L90

We should adjust that so it uses the same logic as the `requireLogin` feature! 

Hope this helps!

If you'd like we can also add these links to the documentation readme!

Thank you!

**Comment by Forchapeatl** [comment] 2022-04-28 12:20
The "To ask a question" redirects to dashboard because of this function.   Here is the cause of our problem.
https://github.com/publiclab/plots2/blob/3433febd0bb33d701966a052321c78d2bd140ccc/app/controllers/home_controller.rb#L5-L7
Question is ,Please  how may I manipulate User sessions from home_controller ?

**Comment by ebarry** [comment] 2022-05-03 15:23
Thanks for working on this @Forchapeatl !

**Comment by jywarren** [comment] 2022-05-03 22:15
Hi thank you @Forchapeatl i wanted to try to just check that the different possible failure modes are accounted for here:

- [ ] clicking continue button correctly flows to login and then posting a question
- [ ] clicking "log in" at "log in or sign up" correctly redirects back to /questions
- [ ] in general, the `requireLogin` class is working as designed 

I think you fixed the first of the three, right? Thank you so much! If so we can either just manually test to confirm the remaining 2 or if necessary open new issues for them.

**Comment by Forchapeatl** [comment] 2022-05-04 12:38
@jywarren ,unfortunately  the second test fails on normal mode but passes on incognito (private) mode.

* [x]  clicking continue button correctly flows to login and then posting a question
* [ ]  clicking "log in" at "log in or sign up" correctly redirects back to /questions
* [x]  in general, the `requireLogin` class is working as designed.

Chrome Click "log in" or "sign up".    **(Failed)**

https://user-images.githubusercontent.com/24577149/166680755-b3f6cb9f-0fd9-4927-b36e-612baac853c9.mp4

Chrome - **incognito mode** Click "log in" or "sign up".      **(Passed)**

https://user-images.githubusercontent.com/24577149/166680764-12b918b3-ca5e-4f84-8991-608281afd189.mp4

clicking continue button correctly flows to login and then posting a question       **(Passed)**

https://user-images.githubusercontent.com/24577149/166680774-09471681-fc71-4a9a-bafb-b06aff29f81a.mp4

**Comment by Forchapeatl** [comment] 2022-05-04 13:06
> Thanks for working on this @Forchapeatl !

your welcome!

**Comment by Forchapeatl** [comment] 2022-05-13 03:57
Please any comment on this [https://github.com/publiclab/plots2/issues/11099#issuecomment-1117264440](https://github.com/publiclab/plots2/issues/11099#issuecomment-1117264440) response

**Comment by jywarren** [comment] 2022-06-07 08:04
Hi @Forchapeatl sorry for the delay but I'm going to have a look at this today!

**Comment by jywarren** [comment] 2022-06-07 10:29
OK, so in https://stable.publiclab.org/login, it now correctly sets the return_to parameter. But when you actually log in, you are not directed there. Strange! I think we need to trace the logic and watch the rails log at the same time, to see if the parameter is being properly passed through.

**Comment by Forchapeatl** [comment] 2022-06-07 21:26
Thank you @jywarren . I will investigate the rails logs more this time.

**Comment by jywarren** [comment] 2022-06-14 06:17
OK, i just used gitpod on the main branch, and went to `/login?return_to=/questions` - logged in, and was redirected back to `/questions`. That's correct. Now trying again on stable server.

**Comment by jywarren** [comment] 2022-06-14 06:18
It worked on Questions too now. Maybe i didn't wait long enough on stable? Seems like we're actually OK... i'll double check everything again but hopefully!

**Comment by jywarren** [comment] 2022-06-14 06:25
OK confirmed. It works in stable, but in production, it still shows the following error because:

```diff
-<input type="hidden" name="return_to" class="login-modal-redirect" value="/login?return_to=/questions" />
+<input type="hidden" name="return_to" class="login-modal-redirect" value="/questions" />
```

![image](https://user-images.githubusercontent.com/24359/173507635-7962b357-77ff-4430-9faa-6ca65ac3865c.png)

So, we can close this now!

**Comment by jywarren** [comment] 2022-06-14 06:27
Thanks everyone for your help!

**Closed** 2022-06-14 06:27 UTC
Labels: bug

**Comment by Forchapeatl** [comment] 2022-06-14 06:55
@jywarren Thank you
