### ISSUE TITLE
Multiple broken links on profile page

### ISSUE THREAD

**Issue by shubhscoder** [publiclab/plots2#5085] opened 2019-03-15 09:18 UTC
The issue can be found here( https://publiclab.org/profile/warren#2/41.0/-71.0/BL1 )

Following are the broken links : 
1. Link to questions asked
2. Link to activities posted
3. Link to activities attempted

**Comment by gauravano** [comment] 2019-03-15 13:40
Hi @shubhscoder, the issue is already reported at  https://github.com/publiclab/plots2/issues/5008 and fix is in progress. So, closing it. Thanks!

**Closed by gauravano** 2019-03-15 13:40 UTC
