### ISSUE TITLE
Add return_to field in the login modal

### ISSUE THREAD

**Issue by SidharthBansal** [publiclab/plots2#4188] opened 2018-12-08 16:17 UTC
@okonek has claimed this and is working on this.

**Comment by SidharthBansal** [comment] 2018-12-08 16:32
@okonek please claim https://codein.withgoogle.com/dashboard/tasks/5754476527878144/ and push a pr. I want to do a quick merge and approval.

**Comment by SidharthBansal** [comment] 2018-12-08 18:39
@okonek I checked your changes by pushing them onto the unstable
![image](https://user-images.githubusercontent.com/20972099/49689386-75f3e200-fb46-11e8-898d-94f4b0dd8b71.png)

The return_to works well but you have by mistake written the line
![image](https://user-images.githubusercontent.com/20972099/49689392-9754ce00-fb46-11e8-8807-0348f688dc5f.png)

Because of which we get the output on unstable as 
![image](https://user-images.githubusercontent.com/20972099/49689402-b5223300-fb46-11e8-993e-2c02e1901fe3.png)

**Comment by SidharthBansal** [comment] 2018-12-08 18:40
So please remove that line and create a pr soon so that I can merge and give you your reward points.

**Comment by SidharthBansal** [comment] 2018-12-09 15:57
Resolved the issue as per @okonek suggestion in #4197.
I did pr because @JonathanXu1 and @oorjitchowdhary's work was dependent on this work.
Credit given to @okonek for his work.

**Comment by gauravano** [comment] 2018-12-15 10:56
Hi @SidharthBansal is this issue still required?

**Comment by SidharthBansal** [comment] 2018-12-15 11:03
I resolved this issue.
But I opened it again so that someone can check it.
When I checked with Oorjit, Jonathan, Kevin and Okonek everything was
working fine.
Can you now check the behaviour?
Also, the integrated signup and login modal may face this issue. So, we can
close this one after Jonathan's PR is merged.

**Comment by SidharthBansal** [comment] 2018-12-17 05:47
@gauravano I think we can check this and close this.
I did the changes in the PR. Please check them so that we can close this up.
Thanks

**Comment by gauravano** [comment] 2018-12-17 16:31
return_to get embedded to url on signup but due to captcha failure user switch to spamaway verification return_to get out of context as user has to click another link. 

As publiclab.org do support recaptcha so the issue is not coming there, so I think we can close this. Thanks!

**Comment by gauravano** [comment] 2018-12-17 16:32
@SidharthBansal

**Comment by SidharthBansal** [comment] 2018-12-17 16:37
@gauravano this is login return to not signup.

**Comment by SidharthBansal** [comment] 2018-12-17 16:38
Please see to it again.
Thanks

**Comment by SidharthBansal** [comment] 2018-12-26 19:45
@gauravano have you checked this? I submitted the patch and I believe it is working correctly.
Just want to do cross check. 
We have two separate issues one for the login return to and other is for sign up modal. We can those which are working correctly.
I did both in December.
Thanks

**Comment by gauravano** [comment] 2018-12-26 19:53
Here's for the login  - https://drive.google.com/open?id=186KAwftumt7dVeROgUkgimMbqwXJel7V

**Comment by gauravano** [comment] 2018-12-26 19:53
I think this is what we are looking for? @SidharthBansal

**Comment by SidharthBansal** [comment] 2018-12-26 20:08
Awesome
Many thanks to you for checking this again. Let's close this then
@jywarren return to is solved now.

**Closed** 2018-12-26 20:08 UTC
Labels: gci-candidate
