### ISSUE TITLE
Make processes asynchronous

### ISSUE THREAD

**Issue by grvsachdeva** [publiclab/plots2#6126] opened 2019-08-10 07:50 UTC
Many services such as marking node as spam or approving them can be done asynchronously. Create worker for all such services. So, these activities do not use main thread resources. Also, for each such conversion make changes to the frontend i.e., AJAXify the view so that effect of the action can be shown to the user at that time only. 

Services which can utilize this:
1. Spam moderation
2. Notification calls
3.

**Comment by SidharthBansal** [comment] 2019-08-10 13:45
Great idea.
I think you missed to type third field.

**Comment by gauravano** [comment] 2019-08-10 17:49
The third one is open for ideas/edits :)

**Comment by newbazz** [comment] 2019-08-11 04:42
I would like to work on this issue, i think i will work on the first part. Can you please explain the same.

**Comment by gauravano** [comment] 2019-08-11 06:50
Currently, when a moderator or admin, moderates a note by clicking spam or approve. Behind the scenes, we send emails to respective people and the page reloading also take place. But, for process like this, we can utilize Sidekiq, so on pressing "Approve", the job will be triggered and will take place in a different thread and we can remove/show note approval using AJAX to the moderator. It will save time as moderators don't have to wait for the page to reload to review next note.

**Comment by Anupam-dagar** [comment] 2019-08-30 12:13
@gauravano for the spam moderatoin, In the code, there are redirects being used after approval or marking as spam. As per the issue, there shouldn't be any redirects. Using ajax calls I can achieve the intended behaviour but do we need to keep the redirect behaviour? Also if we do remove the redirects, then we need to send some response for ajax call success. I have been doing this till now by use of making an API and sending a json response. Should I send in a json response?

**Comment by gauravano** [comment] 2019-08-31 14:44
If we implement it using AJAX, then no need to redirect, as we can just modify the view. In case, where the view changes would be more, we can think of keeping redirect. We can show the success and failure message using the JS only i.e., the JS.erb file using which we will change the view, we can also trigger notification from there, like noty. What do you think?

**Comment by jywarren** [comment] 2021-02-02 18:11
I'd like to narrow this to any remaining instances of `deliver_now` which uses ActionMailer and can be deferred; except where it happens in tests. In tests, we need it to happen immediately, but if it's not in the `/test/` folder, we should change `deliver_now` to `deliver_later`:

https://github.com/publiclab/plots2/search?q=deliver_now

I see instances in:

* app/models/comment.rb
* app/models/user.rb
* app/models/node.rb
* app/controllers/user_sessions_controller.rb
* app/controllers/admin_controller.rb
* app/controllers/notes_controller.rb

These should substantially improve performance for routes using these!

**Comment by jywarren** [comment] 2021-03-30 14:34
This has been tremendous. Thanks @SidharthBansal !!!

**Comment by jywarren** [comment] 2021-04-09 20:17
A quick check through this shows all have been converted, many thanks @SidharthBansal!!!

The only ones remaining are non-batch, like resetting password. Closing this now, and we've already seen huge speedups in commenting speed on Skylight! from 4-8s to ~900ms!!!

**Closed by jywarren** 2021-04-09 20:17 UTC
Labels: break-me-up, feature, help wanted
