### ISSUE TITLE
Different Read more buttons for the Public Lab blog and the articles

### ISSUE THREAD

**Issue by gautamig54** [publiclab/plots2#5158] opened 2019-03-18 17:48 UTC
It will be a convenient UI change. Using different colour buttons or style will be helpful.
 
![Screen Shot 2019-03-18 at 11 16 32 PM](https://user-images.githubusercontent.com/35326753/54551378-ffcc0a80-49d3-11e9-8dba-9a8f7899b6b1.png)

**Comment by CleverFool77** [comment] 2019-03-18 17:50
Is it similar to #4990 ? :thinking:

**Comment by gautamig54** [comment] 2019-03-18 17:52
@CleverFool77 yes! Thank you for mentioning.

**Comment by gauravano** [comment] 2019-03-18 18:31
Closing it as it's a duplicate of #4990. Thanks!

**Closed by gauravano** 2019-03-18 18:31 UTC
