### ISSUE TITLE
Wrong wiki count in Dropdown by type

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7334] opened 2020-01-23 12:22 UTC
In https://publiclab.org/contributors/newsletter dropdown by type Wiki pages is showing 3 but on clicking it shows only 1
Image is shown below
![Screenshot from 2020-01-23 17-47-30](https://user-images.githubusercontent.com/36025262/72984149-0653bb80-3e09-11ea-91e5-5c905567f5a1.png)

**Comment by keshavsethi** [comment] 2020-01-23 12:26
If we click on by Views button then it shows all 3 but again if try to sort all 3 of them by title it again shows 1 newsletter

**Comment by gabrielbaldao** [comment] 2020-01-24 20:24
Can I try fix this?

**Comment by keshavsethi** [comment] 2020-01-25 08:47
yes, you can try this but before doing this get it reviewed by @SidharthBansal @nstjean @jywarren

**Comment by SidharthBansal** [comment] 2020-01-25 14:33
Sure. Please provide a fux

**Comment by NitinBhasneria** [comment] 2020-02-12 12:46
@gabrielbaldao are you doing this or can I proceed?

**Comment by SidharthBansal** [comment] 2020-02-21 09:22
Go ahead

**Comment by jywarren** [comment] 2020-06-16 19:53
Note we should make this match the code and tests here: https://github.com/publiclab/plots2/pull/7476

and the idea for a "single source of truth" here: https://github.com/publiclab/plots2/issues/6855#issuecomment-578331475

Thank you!

**Comment by jywarren** [comment] 2020-06-16 20:05
And noting a more detailed investigation here -- I think we need to be sure all counts are from a unified body of code maintained in the models, and unit tested!

https://github.com/publiclab/plots2/issues/7965#issuecomment-644980326

**Comment by jywarren** [comment] 2020-07-21 21:20
So we should confirm that all counts are coming from the respective `Tag.count` style methods. Key areas are here:

https://github.com/ckchu8/plots2/blob/0fbcc07bd61fd238d88779e49a3fbd2e300ef041/app/controllers/tag_controller.rb#L542-L561

And on tag cards, for example on https://publiclab.org/tags

**Comment by jywarren** [comment] 2020-07-21 21:27
Just noting that the original issue at top may be a special case. I see in the DB that we're fetching these three pages:

* https://publiclab.org/n/3928 https://publiclab.org/wiki/newsletter (`Public Lab Community Newsletter`)
* https://publiclab.org/n/4965 https://publiclab.org/newsletter (`Newsletter`)
* https://publiclab.org/wiki/subscribe

Only the middle one is the correct one. The first may be some kind of strange clone... not sure. From the early days of the site? And the last, doesn't look like a page anymore?

Here are the full records:

```
irb(main):005:0> Node.for_tagname_and_type('newsletter', 'page', wildcard: false).last
=> #<Node nid: 4965, vid: 18544, type: "page", language: "", title: "Newsletter", uid: 1, status: 1, created: 1353450804, changed: 1484959036, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 1, comments_count: 0, drupal_node_revisions_count: 5, path: "/wiki/newsletter", main_image_id: nil, slug: "newsletter", views: 1471, latitude: nil, longitude: nil, precision: nil>
irb(main):006:0> Node.for_tagname_and_type('newsletter', 'page', wildcard: false).first
=> #<Node nid: 308, vid: 20121, type: "page", language: "", title: "Subscribe", uid: 1, status: 1, created: 1306885186, changed: 1484959009, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 0, comments_count: 0, drupal_node_revisions_count: 13, path: "/subscribe", main_image_id: nil, slug: "subscribe", views: 25, latitude: nil, longitude: nil, precision: nil>
irb(main):007:0> Node.for_tagname_and_type('newsletter', 'page', wildcard: false)[1]
=> #<Node nid: 4965, vid: 18544, type: "page", language: "", title: "Newsletter", uid: 1, status: 1, created: 1353450804, changed: 1484959036, comment: 0, promote: 0, moderate: 0, sticky: 0, tnid: 0, translate: 0, cached_likes: 1, comments_count: 0, drupal_node_revisions_count: 5, path: "/wiki/newsletter", main_image_id: nil, slug: "newsletter", views: 1471, latitude: nil, longitude: nil, precision: nil>
```

Very mysterious!

**Comment by jywarren** [comment] 2020-07-28 14:10
Jeanette from PL noted this page also has an elevated number of wiki pages listed on the tab count:

![image](https://user-images.githubusercontent.com/24359/88676289-e5bb3580-d0b9-11ea-8f48-4a4173d6b260.png)

83 is a much bigger error than what @keshavsethi had found, as only 6 wiki pages are shown. We can go into the database directly to just skim what those wiki pages actually are, in the query returning 86, and compare the queries too.

**Comment by jywarren** [comment] 2020-08-04 18:32
OK! The disparity, for the `method` tag, is these different queries:

```
irb(main):002:0> Node.for_tagname_and_type('method', 'page', wildcard: false).count
=> 83
irb(main):001:0> Tag.find_nodes_by_type('method','page').count
=> 5
```

I'll look at the code behind them to confirm what's going on. 

Here is the tab count: https://github.com/publiclab/plots2/blob/92834ead6c53d6d9431bb99024d4044b282518be/app/controllers/tag_controller.rb#L542-L561

It references `Node.for_tagname_and_type`:

https://github.com/publiclab/plots2/blob/122e8a73b440bb752f080375aad3f24a02b7c8f9/app/models/node.rb#L621-L630

By contrast, `Tag.find_nodes_by_type` is here:

https://github.com/publiclab/plots2/blob/122e8a73b440bb752f080375aad3f24a02b7c8f9/app/models/tag.rb#L94-L116

Noting that the first 6 items on both https://publiclab.org/wiki/tag/method and https://publiclab.org/methods are the same, but /wiki/tag/method cuts off after 6. A clue? 🕵️

**Comment by jywarren** [comment] 2020-08-04 18:33
Both segments of code are significantly complicated by `parent` tag references.

**Comment by jywarren** [comment] 2020-08-04 18:36
OK, so the difference is in the `limit` term:

```ruby
irb(main):010:0> Tag.find_nodes_by_type('method','page', false).count
=> 83
irb(main):011:0> Tag.find_nodes_by_type('method','page').count
=> 5
```

Let's track where the limit is being set on https://publiclab.org/wiki/tag/method

But, a follow-up could be to consolidate this code and/or remove the `parent` functionality.

**Comment by jywarren** [comment] 2020-08-04 18:52
So, the query for the listing of wiki pages in the table below on /wiki/tag/method is: https://github.com/publiclab/plots2/blob/92834ead6c53d6d9431bb99024d4044b282518be/app/controllers/tag_controller.rb#L117

I /believe/ none of these have parent tag issues, having checked in the db. So we're left with a strange mystery of pagination, which I can't quite figure out.

Each of these pages show a different collection, with some overlapping items:

* https://publiclab.org/wiki/tag/method
* https://publiclab.org/wiki/tag/method?page=2
* https://publiclab.org/wiki/tag/method?page=3
* https://publiclab.org/wiki/tag/method?page=4

We can probably get all 83 pages this way. So it could be pagination being missing -- we could activate by adding `@pagination = true` in the controller, to activate this line:

https://github.com/publiclab/plots2/blob/92834ead6c53d6d9431bb99024d4044b282518be/app/views/wiki/_wikis.html.erb#L30

But there's something else -- why is `Odor Logging` and `Stormwater Monitoring` the top entry for both the first couple pages? And why does `Facilitate your meetings` show up again on pages 3 and 4? Something is going on with our query.

**Comment by jywarren** [comment] 2020-08-04 19:15
Let's fix pagination, and then return here to see what we can do about the repeated display of some items, as well as figure out why page 1 shows only 6, but later pages show a full 24 (i think?)???

**Comment by jywarren** [comment] 2020-08-04 19:33
VERY strange -- https://github.com/publiclab/plots2/pull/8243#issuecomment-668782325 --- pagination mysteries persist...

**Comment by jywarren** [comment] 2020-08-11 21:45
OK, noting from [this comment](https://github.com/publiclab/plots2/issues/7965#issuecomment-672248369) that the `/tag/____` page is cached every 5 mins.

**Comment by jywarren** [comment] 2020-08-11 21:52
Indeed:

```ruby
> Node.for_tagname_and_type('method','page',question:false).paginate(page: 1,per_page: 24).order('node_revisions.timestamp DESC').length
=> 4
```

**Comment by jywarren** [comment] 2020-08-11 21:59
It seems to be the mix of `.order('node_revisions.timestamp DESC')` and `.paginate()` that is causing this. If I remove one, it starts to return 24 items:

```

**Comment by jywarren** [comment] 2020-08-11 22:00
https://github.com/publiclab/plots2/blob/f38bd542c380185f504a82b2806a49995ef0f736/app/models/node.rb#L626-L629

**Comment by jywarren** [comment] 2020-08-11 22:07
I believe this may be an issue with our pagination library, `will_paginate` --

* https://github.com/mislav/will_paginate/issues/573
* https://github.com/mislav/will_paginate/issues/604
* esp "Missing record on pagination when records are sorted" https://github.com/mislav/will_paginate/issues/553

**Comment by jywarren** [comment] 2020-08-11 22:08
Maybe we look at https://github.com/kaminari/kaminari or https://www.imaginarycloud.com/blog/paginating-ruby-on-rails-apps-with-pagy/ ?

**Comment by jywarren** [comment] 2020-08-25 20:05
OK, we've installed `pagy` gem for pagination in #8326 - let's see how this does in staging now.

**Comment by jywarren** [comment] 2020-08-25 20:09
Confirming that https://unstable.publiclab.org/wiki/tag/method now shows https://unstable.publiclab.org/wiki/tag/method?page=2, https://unstable.publiclab.org/wiki/tag/method?page=3, https://unstable.publiclab.org/wiki/tag/method?page=4 with all entries. 

That resolves [this original issue](https://github.com/publiclab/plots2/issues/7334#issuecomment-665063229)

(we should count the results to be sure)

however, I now notice that, strangely, the first page lists only 4, while later pages show the full max per-page limit:

![image](https://user-images.githubusercontent.com/24359/91222508-46578580-e6ed-11ea-8855-b051e0629fdf.png)

**Comment by jywarren** [comment] 2020-08-25 20:13
OK, we are doing better... 32 are listed. But the total should be 83! 

13 are listed per page, so if the first page were missing, say, 9 to make a full 13, we'd still only be at 41 total. Let me try to get a list of the full 83 to check discrepancies...

**Comment by jywarren** [comment] 2020-09-01 22:17
Here are all 83:

> ["guides", "mapknitter", "spectral-workbench", "passenger-pigeon", "infragram", "thermal-flashlight", "gardening-toolkit", "diy-indoor-air-quality-remediation-kit", "facilitation", "pole-mapping-kit-instructions", "start-enviro-monitor-study", "optical-monitoring-of-particulate-matter", "filter-based-monitoring-of-particulate-matter", "pdr-1500", "host-an-event", "photo-sharing", "anonymity", "biobroth-bubbler", "data-logging", "nano-data-logger", "microscopes", "soil-sampling", "water-sampling", "turbidity", "conductivity", "air-sampling", "hydrogen-sulfide-copper-pipe", "raspberry-pi-infragram", "reagents", "image-sequencer", "noise", "micro", "purpleair", "pipeline-monitoring", "simple-water-sensor-platform", "mae-d-agua", "tech-review", "photo-monitoring", "sampling", "hydrogen-sulfide-photopaper", "babylegs", "soil-testing-toolkit", "emery-board", "filters", "bucket-monitor", "thermal-photography", "spectrometry", "balloon-mapping", "stereo-camera", "kite-balloon-hybrid", "balloon-telemetry-kit", "indoor-air-quality-mapping", "timelapse", "hydrogen-sulfide-sensor", "environmental-estrogen-testing", "water-quality-sensor", "air-column-monitor", "portable-energy-scavenging-kit", "potentiostat", "refinery-watching", "riffle", "particle-sensing", "dustduino", "coqui", "fido-the-raspberry-pi-based-temperature-alarm-that-sends-text-messages", "pole-mapping", "kaptery-aerial-rigs", "creating-a-media-campaign", "public-comment", "multispectral-imaging", "literature-review", "health-effects-lit-review", "aerial-photography", "webjack", "stormwater", "minivol", "site-survey", "water-sensors", "sensor-enclosures", "issue-brief", "testing-our-waters", "odor", "simple-air-sensor"]

**Comment by jywarren** [comment] 2020-09-01 22:25
OK - theory - just confirmed that the tag `pin:test` can remove a wiki page from being displayed on `/wiki/tag/test` (in gitpod). How many are being hidden this way???

**Comment by jywarren** [comment] 2020-09-01 22:58
None from the 83. I'm going to try starting a development environment from staging and to try logging out the contents of the `pagy()` pagination collection. Very mysterious that only 4 appear on the first page.

**Comment by jywarren** [comment] 2020-09-01 23:00
wow let's try this! https://ddnexus.github.io/pagy/how-to#custom-count-for-custom-scopes

**Comment by jywarren** [comment] 2020-09-01 23:24
also noting https://ddnexus.github.io/pagy/extras/arel

**Comment by jywarren** [comment] 2020-09-01 23:52
OK, ready to try this in unstable with:

`source ../environment-dev.sh && docker-compose exec web passenger start`

**Comment by jywarren** [comment] 2020-09-22 16:50
custom count didn't work w/ `nodes.count` -- will try reproducing in unstable on the command line...

**Comment by jywarren** [comment] 2020-09-22 17:42
OK, found a deep inconsistency:

```
irb(main):042:0> @pagy, nodesp = pagy(nodes.order('node_revisions.timestamp DESC')) # same as in controller
irb(main):048:0> nodesp.page(1).size
=> 20
irb(main):049:0> nodesp.page(1).collect(&:title)
=> ["Bucket Monitor", "Write an Issue Brief", "Facilitate your meetings", "Air Sampling"]
irb(main):050:0> nodesp.page(1).size
=> 20

```

**Comment by jywarren** [comment] 2020-09-22 19:40
OK, it appears that the wild pagination occurs when running:

`@pagy, nodesp = pagy(nodes.order('node_revisions.timestamp DESC'))`

but not:

`@pagy, nodesp = pagy(nodes.order('node.nid DESC'))`

so i propose that as a short-term fix. This will sort them by descending `nid` which is very close to order of creation. Then we can deprioritize this - i'll leave a comment explaining.

**Closed** 2020-09-22 20:21 UTC
Labels: bug
