### ISSUE TITLE
Login Dialog in Mobile View

### ISSUE THREAD

**Issue by AyanChoudhary** [publiclab/plots2#7552] opened 2020-02-20 17:45 UTC
### Please describe the problem (or idea)

The position of the login dialog box in the mobile view is wrongly configured.

> What happened just before the problem occurred? Or what problem could this idea solve?

On trying to login through a mobile view the dialog box opens out of position.

> What did you expect to see that you didn't?

The dialog was exected to be in the center but has a wrong positioning.

![Screenshot from 2020-02-20 23-09-42](https://user-images.githubusercontent.com/45792768/74962880-c21eff80-5436-11ea-8e14-65bf8f702dcc.png)

### Please show us where to look

https://publiclab.org/#

I would like to work on this.

**Comment by AyanChoudhary** [comment] 2020-02-20 17:45
@nstjean @cesswairimu please review this issue.

**Comment by nstjean** [comment] 2020-02-21 19:44
I thought I saw this issue before, but I can't find any mention of it. Maybe this here: https://github.com/publiclab/plots2/issues/7482

You can look into what the problem is. It does need to be fixed!

**Comment by SidharthBansal** [comment] 2020-02-24 07:08
@cesswairimu is it same as #7448?
If so then let's close this

**Comment by cesswairimu** [comment] 2020-02-25 20:33
oh yeah its the same... @AyanChoudhary seems like we resolved this in the above issue and PR mentioned above in the last two comments.
Thanks everyone and closing this

**Closed by cesswairimu** 2020-02-25 20:33 UTC
Labels: bug
