### ISSUE TITLE
Photos in galleries in old research notes do not display in popup

### ISSUE THREAD

**Issue by Fastie** [publiclab/plots2#1135] opened 2016-12-22 01:20 UTC
Research notes once had galleries of images. These were ported to the plots2 site and appear as a row of icons at the top of some old notes. Clicking on these thumbnails would pop up each photo. Now those photos do not pop up.

Example URLs
https://publiclab.org/notes/elainechoi89/7-5-2012/tyvekbamboo-kite-workshop-pfizer-building-brooklyn-ny
https://publiclab.org/notes/cfastie/4-14-2013/sanm-leafkam

PublicLab.org username
cfastie

Browser, version, and operating system
Chrome or IE in Windows

**Comment by jywarren** [comment] 2016-12-22 13:22
These used a JavaScript plugin, so is it possible to look in the JavaScript
console to see if there are any errors?

Thanks!

**Comment by ryzokuken** [comment] 2016-12-29 01:57
@jywarren Anyone working on this?

**Comment by jywarren** [comment] 2016-12-29 15:38
Not that I know of! Go for it.

**Comment by jywarren** [comment] 2016-12-29 16:39
Can you monitor the "network" pane of the chrome dev tools to see if any
image file is loaded, but not shown? And, can you double check the
JavaScript that's being used to trigger the show, that it's correctly
formatted? Perhaps you could try to trigger it yourself from the JavaScript
console to test that out.

**Comment by ryzokuken** [comment] 2016-12-29 16:47
@jywarren Nope, it's preloading all the images and then must be trying to show them later but with no avail. In my case, all the images (yes, the images not the thumbnails. I checked :P) loaded almost as soon as the page did.

**Comment by jywarren** [comment] 2016-12-29 16:49
Hmm, use the Dom inspector to inspect the elements themselves and see why
they're not showing?

**Comment by ryzokuken** [comment] 2017-01-02 15:59
@jywarren 
![screenshot_20170102_212238](https://cloud.githubusercontent.com/assets/13121330/21592244/e7f07bde-d131-11e6-852d-f3a376334e12.png)
If you notice, the `display: block` property is crossed out. This is because it is being overridden by another rule. Quite evidently, it is the rule for the class `.hide`. Not only is it above the element rule because of precedence, it has this pesky `!important` modifier which automatically puts this rule above every other rule. Perhaps we should try changing these rules a little, they would most probably fix our issue.

**Comment by jywarren** [comment] 2017-01-03 15:59
Oh, good find! Can you see where the .hide class is defined in
/app/assets/stylesheets/ (or maybe in a library dependency?), and perhaps
we can disambiguate it? I think it'll have been compiled into
application-xxxxxxxx.css but in development mode you'd see the uncompiled
version.

**Comment by ryzokuken** [comment] 2017-01-04 14:29
@jywarren Can I reproduce this issue locally? If these are the old notes, maybe I cannot recreate them. Nevertheless, I'll look for this class in the css.

**Comment by ryzokuken** [comment] 2017-01-04 14:33
@jywarren What is the name of the javascript library? None of our own CSS files contain such a class.

**Comment by jywarren** [comment] 2017-01-04 15:33
Ah, this is true about locally... ummmm. things that are hard to reproduce are hard to solve! 

I /think/ the library is included via bower.json: 

`    "bootstrap-lightbox": "jbutz/bootstrap-lightbox#~0.5.0",`

**Comment by jywarren** [comment] 2017-01-04 15:35
the style is in `/public/lib/boostrap-lightbox/less/`

**Comment by jywarren** [comment] 2017-01-04 15:36
Perhaps we could swap for a different "lightbox"-style plugin that doesn't use that. But I'd guess the conflicting style is from the main `bootstrap` library, so maybe this is a version mismatch issue?

**Comment by jywarren** [comment] 2017-01-04 15:38
```
(trusty)warren@localhost:~/sites/plots2$ grep -r '.hide' public/lib/bootstrap/less/
public/lib/bootstrap/less/modals.less:// Measure scrollbar width for padding body during modal show/hide
public/lib/bootstrap/less/scaffolding.less:// See: http://a11yproject.com/posts/how-to-hide-content/
public/lib/bootstrap/less/button-groups.less:// `required` attribute, we have to "hide" the inputs via `opacity`. We cannot
public/lib/bootstrap/less/button-groups.less:// use `display: none;` or `visibility: hidden;` as that also hides the popover.
public/lib/bootstrap/less/mixins.less:@import "mixins/hide-text.less";
public/lib/bootstrap/less/mixins/hide-text.less:// Heads up! v3 launched with with only `.hide-text()`, but per our pattern for
public/lib/bootstrap/less/mixins/hide-text.less:// of v3.0.1 we have added `.text-hide()` and deprecated `.hide-text()`.
public/lib/bootstrap/less/mixins/hide-text.less:.hide-text() {
public/lib/bootstrap/less/mixins/hide-text.less:.text-hide() {
public/lib/bootstrap/less/mixins/hide-text.less:  .hide-text();
public/lib/bootstrap/less/utilities.less:// Note: Deprecated .hide in favor of .hidden or .sr-only (as appropriate) in v3.0.1
public/lib/bootstrap/less/utilities.less:.hide {
public/lib/bootstrap/less/utilities.less:.text-hide {
public/lib/bootstrap/less/utilities.less:  .text-hide();
```

This line sticks out to me:

```
public/lib/bootstrap/less/utilities.less:// Note: Deprecated .hide in favor of .hidden or .sr-only (as appropriate) in v3.0.1
```

**Comment by jywarren** [comment] 2017-01-04 15:41
Indeed, there have been releases since we included it: `v0.7.0`:

**Comment by jywarren** [comment] 2017-01-04 15:41
https://github.com/jbutz/bootstrap-lightbox/releases -- maybe we should upgrade?

**Comment by jywarren** [comment] 2017-01-04 15:42
`.hide` is no longer used: https://github.com/jbutz/bootstrap-lightbox/blob/master/less/bootstrap-lightbox.less

last update was for Bootstrap 3.1 compatibility.

**Comment by jywarren** [comment] 2017-01-04 15:44
So let's bump to `v0.7.0` and see what happens in staging server? 

http://testing.laboratoriopublico.org (once we merge to stable it'll publish there)

**Comment by ryzokuken** [comment] 2017-01-04 17:42
@jywarren so, do I make a small PR for https://github.com/publiclab/plots2/blob/master/bower.json#L7? 
Going to bed today, but will do whatever works for you tomorrow. :)

**Comment by jywarren** [comment] 2017-01-04 18:48
Yep, that's right! Thanks!

**Comment by jywarren** [comment] 2017-01-08 22:50
Solved in #1173, we believe... checking...

**Comment by jywarren** [comment] 2017-01-23 17:43
Ok, I believe the formatting of the gallery items needs to be changed to not use the "hide" CSS class anymore. See docs here:

https://github.com/jbutz/bootstrap-lightbox/blob/master/README.md#example

Compare to:

https://github.com/publiclab/plots2/blob/master/app/views/notes/show.html.erb#L70

**Comment by jywarren** [comment] 2017-01-23 17:45
This could be tested out in JavaScript by manually removing those classes in the developer tools and seeing if the gallery works then. 

```js
$(".lightbox.fade").Remove class("hide");
```

**Comment by jywarren** [comment] 2017-06-13 20:38
For the time being I'm going to close this because the galleries now simply open the image at full resolution in a new window. Thanks!

**Closed by jywarren** 2017-06-13 20:38 UTC
Labels: bug
