### ISSUE TITLE
Identical failing tests on different pull requests. These tests may not work at all

### ISSUE THREAD

**Issue by Uzay-G** [publiclab/plots2#6950] opened 2019-12-11 17:06 UTC
I noticed a problem with the Travis CI testing but probably also the testing in general on the repo since yesterday. My [pull request](https://github.com/publiclab/plots2/pull/6948) and [@chen-robert's](https://github.com/publiclab/plots2/pull/6949) have both been getting the same errors on our travis report that seem totally unrelated to the changes of our pull requests. You can see the details [here](https://travis-ci.org/publiclab/plots2/jobs/623312422?utm_medium=notification&utm_source=github_status) and [here](https://travis-ci.org/publiclab/plots2/jobs/623755453?utm_medium=notification&utm_source=github_status).
 
I think this is pretty important if it actually a problem with the testing because then any new pull requests would then be blocked.

What do you think @SidharthBansal and @jywarren?

**Comment by cesswairimu** [comment] 2019-12-11 18:58
Hey @Uzay-G , yeah, we have been having this problem with travis for a while.. could be it is running some dependent tests before other and hence the failures... most times restarting travis usually does the trick but I agree could be great to investigate and possibly fix it. I will restart both of your builds for the time being. Thanks for opening this.

**Comment by cesswairimu** [comment] 2019-12-11 20:41
Okay, so these errors are more frequent than usual and none seems too pass after restart...investigating more on these errors and checking recent merges to see if I can point out the root cause

**Comment by nstjean** [comment] 2019-12-11 21:38
The tests that are failing:

```
 FAIL["test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:content:lat:lon]_into_maps_which_display_notes", #<Minitest::Reporters::Suite:0x000055c4d437d5b8 @name="NodeSharedTest">, 7.643299305000028]
 test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:content:lat:lon]_into_maps_which_display_notes#NodeSharedTest (7.64s)
        Expected: 1
          Actual: 0
        test/unit/node_shared_test.rb:153:in `block in <class:NodeSharedTest>'
 FAIL["test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:tag:blog:lat:lon]_into_maps_which_display_notes,_but_only_those_tagged_with_\"blog\"", #<Minitest::Reporters::Suite:0x000055c4d41fecc8 @name="NodeSharedTest">, 7.680251494999993]
 test_that_NodeShared_can_be_used_to_convert_short_codes_like_[map:tag:blog:lat:lon]_into_maps_which_display_notes,_but_only_those_tagged_with_"blog"#NodeSharedTest (7.68s)
        Expected: 1
          Actual: 0
        test/unit/node_shared_test.rb:160:in `block in <class:NodeSharedTest>'
```

**Comment by jywarren** [comment] 2019-12-13 16:21
https://github.com/publiclab/plots2/pull/6961 also - test at https://travis-ci.org/publiclab/plots2/jobs/624386719

We can restart/rebase that once we figure this out. Thanks all!

**Comment by jywarren** [comment] 2019-12-13 16:22
And just to note @Uzay-G @chen-robert you're totally right this is a priority as it's blocking all or most PRs. I'll try restarting tests a little (you can do this also by closing and reopening the PR) to see if it's a "sometimes" issue, while we also prioritize a more permanent fix to the issue. Thanks all! 🙌

**Comment by cesswairimu** [comment] 2019-12-13 16:27
@jywarren I got this class change was the issue.. Any ideas why https://github.com/publiclab/plots2/pull/6955

**Comment by jywarren** [comment] 2019-12-13 20:01
We believe this is fixed in https://github.com/publiclab/plots2/issues/2365 - please rebase your pull requests over the latest `master` branch to confirm, thank you all for identifying this issue and for your patience! And thanks @cesswairimu for the fix!!! 🙌 💪 🎉

**Closed by jywarren** 2019-12-13 20:01 UTC
Labels: bug, priority, research, testing
