### ISSUE TITLE
Pagination is not working without login 

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/plots2#3579] opened 2018-10-03 07:11 UTC
### Please describe the problem (or idea)
When you click on next page button without login into PublicLab, it's not working, it leads you to page No. 1. Also, if you click on any of page No. 2, 3, 4... button, it leads to the same above issue. 

> What happened just before the problem occurred? Or what problem could this idea solve?
[🎈 Public Lab_ a community for DIY environmental investigation - Google Chrome 03-10-2018 10_55_11.zip](https://github.com/publiclab/plots2/files/2440867/Public.Lab_.a.community.for.DIY.environmental.investigation.-.Google.Chrome.03-10-2018.10_55_11.zip)

> What did you expect to see that you didn't?

[🎈 Public Lab_ Dashboard - Google Chrome 03-10-2018 11_42_56.zip](https://github.com/publiclab/plots2/files/2440883/Public.Lab_.Dashboard.-.Google.Chrome.03-10-2018.11_42_56.zip)

### Please show us where to look

https://publiclab.org

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Chrome, Version 69.0.3497.100 (Official Build) (64-bit), Windows 10

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment] 2018-10-03 07:19
Thanks for reporting the issue.
The issue is being worked upon in other issue.
So closing this one

**Closed by SidharthBansal** 2018-10-03 07:19 UTC
