### ISSUE TITLE
Interchange font icons in password visibility

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5480] opened 2019-04-15 09:24 UTC
**Description**
It is a small bug.
In the password visibility, the font-awesome icons must be interchanged. 
I.e ```fa-eye``` must be shown when the text fields are visible. 
![Selection_140](https://user-images.githubusercontent.com/32747809/56121657-3888e080-5f8e-11e9-9ad5-472c06ab64b7.png)

**Comment by cesswairimu** [comment] 2019-04-17 22:11
Hi @divyabaid16,
Here are my thoughts  for this.
So my understanding the font-awesome "eye" is working as logic-like and not showing current state...say if you are not showing the password you have the "eye icon" button(option) which translates to show password. If you are showing the password have the "crossed eye icon"(option) which translates to "hide password". What do you think? Thanks

**Comment by divyabaid16** [comment] 2019-04-18 05:25
Hey @cesswairimu !!
Good to hear from you :smile: 
Let me give the example of Gmail here,
![Selection_143](https://user-images.githubusercontent.com/32747809/56338512-f0550280-61c7-11e9-920b-ea75ae80e1b2.png)

When the "eye" is open, the password is visible. 
To ease the process we can also add the tooltip that when "open eye" is shown, we can write ```hide password``` so that upon clicking that, the password is hidden. 
It is very much similar to Gmail. 
![Peek 2019-04-18 10-54](https://user-images.githubusercontent.com/32747809/56338633-66596980-61c8-11e9-9d52-daba61faae18.gif)

**Comment by CleverFool77** [comment] 2019-04-18 10:35
Hi @divyabaid16
As I said here earlier https://github.com/publiclab/plots2/pull/5481#issuecomment-483187988
 
Google has a single login i.e gmail, drive, docs etc all have a same login page.
This methodology is only followed by Google and as per design choice the general convention can be the current one which is implemented. We here have a choice to either follow Google or the general convention (implemented as of now) which is also followed by the other websites over the internet.
For reference, here is a blog post which is a tutorial for implementing the eye icon based password visibility. http://www.css-jquery-design.com/2017/12/toggle-visibility-password-field-eye-icon/

I guess its good for public lab to have its own and a generic design rather than just following a single organisation implementing it differently as per the approval of the mentors.
What do you think about this ? This is one of my opinion but it would be better to hear views from @publiclab/plots2-reviewers

**Comment by gauravano** [comment] 2019-04-23 10:34
I think we can just add tooltip to the icon and we would be good? Thanks!

**Comment by vaibhavmathur13** [comment] 2019-10-30 18:23
Hey @gauravano @divyabaid16 @IshaGupta18 
Is this issue still open?

**Comment by VladimirMikulic** [comment] 2020-01-30 19:30
Duplicate of #7177. The issue has been resolved. Thanks, everyone for working on this.

**Closed by VladimirMikulic** 2020-01-30 19:30 UTC
Labels: CSS, HTML
