### ISSUE TITLE
Remove Login and Signup buttons after being signed in

### ISSUE THREAD

**Issue by dhruvgupta167** [publiclab/plots2#4534] opened 2019-01-05 12:34 UTC
![screenshot 2019-01-05 at 5 57 39 pm](https://user-images.githubusercontent.com/32172694/50724434-736bb480-1113-11e9-9427-ae557c69f3a1.png)
Login and SignUp are present even after being signed in. They should replaced with the link to user's profile.

**Comment by IshaGupta18** [comment] 2019-01-05 14:50
I think that's a bug, because they are changed to profile and dashboard normally, also I think that the user isn't signed in in this case.

**Comment by gauravano** [comment] 2019-01-05 15:59
Hi @dhruvgupta167 this happens in case of anomaly with cache, so if you refresh the page you'll observe that the view would be modified and those buttons would be replaced with "dashboard" and "profile" buttons.

@SidharthBansal @jywarren I think this cache issue confuses many people, any suggestions to solve it besides appending timestamp to the link? 

Thanks!

**Comment by jywarren** [comment] 2019-01-05 16:19
I think the timestamp is our immediate solution but perhaps there's a way
to invalidate cache for some pages using headers? We should open an issue
to research other approaches.

**Comment by dhruvgupta167** [comment] 2019-01-05 17:21
Hi @gauravano @jywarren, I tested it a couple of times before filling this issue. I hard refreshed the browser to confirm that the site is not loading from the cache, I even tried different browsers but all showed the same results.

**Comment by dewanhimanshu** [comment] 2019-01-11 06:54
![screenshot from 2019-01-11 12-15-28](https://user-images.githubusercontent.com/32437794/51017705-f91bb400-159a-11e9-8209-b210e0804e8e.png)


Hi , I am also facing this issue.

**Comment by dewanhimanshu** [comment] 2019-01-11 10:32
@gauravano  I am using google OAuth

**Comment by gauravano** [comment] 2019-01-11 10:36
Then, I think your issue is similar to #4569 i.e., you are not actually signed-in. Do one thing to ensure if you are logged in or not. Go to your profile page and see if access token and link social media buttons are present on your profile. 

Thanks!

**Comment by dewanhimanshu** [comment] 2019-01-11 10:42
Yes i am not signed-in as there is no profile page .   /profile redirects to /

**Comment by gauravano** [comment] 2019-01-11 10:43
/profile/[username]  redirects to -- home right?

**Comment by dewanhimanshu** [comment] 2019-01-11 10:49
@gauravano  yes

**Comment by gauravano** [comment] 2019-01-11 10:53
Ok, then this issue is a duplicate of #4569 as user is not signed-in and alert shown is wrong. Closing this one and merging it with #4569. Thanks everyone!

**Closed by gauravano** 2019-01-11 10:53 UTC
Labels: bug, refactorization
