### ISSUE TITLE
publiclab.org/stats page text updates

### ISSUE THREAD

**Issue by sdosemagen** [publiclab/plots2#962] opened 2016-11-07 14:50 UTC
### What happened just before the problem occurred

I'm trying to gather stats from the publiclab.org/stats page. When I click on "year" "month" or "week" the numbers change, but the base text says for the 1st line "posted in the past week" or "posted in the past month". I think the numbers are correct, it's just that the text doesn't correlate so I'm not positive.

### Relevant URLs

https://publiclab.org/stats

### PublicLab.org username

shannon

### Browser, version, and operating system
Chrome

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by ryzokuken** [comment] 2016-11-07 14:54
Confirmed this. The stats are changing but the text does not seem to change accordingly. Will look into it.

**Comment by ebarry** [comment] 2016-11-07 15:08
I'm taking a look at this as well, sitting here next to Shannon. 
I think it might be a presentation issue VS incorrect queries. 
Like, when i click "year" to see it go back a year farther, the numbers do change but the text explaining what the numbers are now showing -- "Looking back from November 07, 2016 15:02." -- is too high on the page. 

Also, the numbers for how many people "joined" are very high, this is a known spam user problem.

**Comment by ryzokuken** [comment] 2016-11-07 15:12
Yeah, I realized that. The links dont set the date to a week ago/a month
ago/a year ago but rather keeps adding/subtracting to that value.

**Comment by icarito** [comment] 2016-11-07 15:12
On 07/11/16 10:08, Liz Barry wrote:

> Also, the numbers for how many people "joined" are very high, this is
> a known spam user problem. 
This is the main problem that is making the migration to Solr indexer
difficult.

I have setup a testing instance of our website with a backup database,
but am at the moment still having issues with Solr crashing before
finishing to index.

Hopefully the Solr storm will be over and we can use this testing
instance to quickly diagnose and fix such issues.

Regards,
Sebastian

**Comment by ebarry** [comment] 2016-11-07 15:18
Hi Sebastian, on that problem of spam users, would it be helpful for me to give you a list of common spam links present in profiles to do a mass deletion?

**Comment by ebarry** [comment] 2016-11-07 15:52
Hi @icarito I'm going to start a thread on web@publiclab.org for us to work on this, and let this issue return to being about the text on the /stats page ! :D

**Comment by icarito** [comment] 2016-11-07 15:59
Thanks Liz, sorry for the topic hijack!

**Comment by jywarren** [comment] 2016-11-17 21:15
Hi, can you change this and/or repost with a recommendation for wording that would make this more clear? 

> "Looking back from November 07, 2016 15:02." -- is too high on the page.

Sounds like @ebarry has a suggestion, above, and I'd like to provide folks with a clear path forward so this issue doesn't get stuck. Thanks!

**Comment by jywarren** [comment] 2016-11-30 20:19
Pinging @ebarry for a next-step suggestion here, and assigning. Thanks!

**Comment by ebarry** [comment] 2016-12-13 16:27
Yes, let's focus this issue on what text and what graphs change when clicking the textlink for "one year" "one month" "one week" further back. Here's what the basic page looks like on this fine morning: 
![screen shot 2016-12-13 at 11 26 16 am](https://cloud.githubusercontent.com/assets/161439/21148702/15ab71de-c127-11e6-8c69-b395959aca40.png)

**Comment by jywarren** [comment] 2016-12-13 17:03
The graph does change, though: 

![screenshot 2016-12-13 at 12 01 45 pm](https://cloud.githubusercontent.com/assets/24359/21150165/099570ac-c12c-11e6-9fe6-63c92a71cc36.png)

So, do we just need to emphasize the `Looking back from __________` line? 

Also, a sense of urgency on this? I wouldn't want it to displace other projects if it's not top priority. Thanks!

**Comment by ebarry** [comment] 2016-12-13 20:57
I'm gonna close this issue about re-writing the text because we're gonna have to handle this in https://github.com/publiclab/plots2/issues/964

**Closed by ebarry** 2016-12-13 20:57 UTC
