### ISSUE TITLE
Space between image and header

### ISSUE THREAD

**Issue by samagragupta** [publiclab/plots2#6372] opened 2019-10-02 10:58 UTC
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below. 

Make some space between the image and header.
Like this:
![Capture](https://user-images.githubusercontent.com/32234926/66039159-aff8ff00-e531-11e9-848e-4b1ab2459ec5.JPG)

[See this page](https://code.publiclab.org/#r=all) for some help in taking your first steps!

Below is a "diff" showing in red (and a `-`) which lines to remove, and in green (and a `+`) which lines to add:

```diff
$DIFF
```

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by 0sf** [comment] 2019-10-02 11:31
I would love to work on the issue.

**Comment by rimildeyjsr** [comment] 2019-10-02 11:50
@samagragupta - Can I take this up?

**Comment by KMustakas88** [comment] 2019-10-02 13:54
Hello, is there a PR for this already? I would like to contribute. @samagragupta @rimildeyjsr

**Comment by stefanosu** [comment] 2019-10-02 17:54
Hi, I would like to contribute to this has this been claimed by someone else already? @samagragupta @rimildeyjsr

**Comment by aRealCyborg** [comment] 2019-10-02 21:25
Is this already taken?

**Comment by aRealCyborg** [comment] 2019-10-03 00:37
I need help to find out how to claim this issue or start working on the fix, This is my first time but I think I can do this. And should i use it in the Launcher

**Comment by aRealCyborg** [comment] 2019-10-03 00:42
$FILENAME
I click on this and it does not  give me a file or something you want to help fix

**Comment by CoderJolly** [comment] 2019-10-03 16:53
> @samagragupta - Can I take this up?

As @rimildeyjsr was the first one to comment, so the issue is assigned to @rimildeyjsr

**Comment by profread** [comment] 2019-10-03 20:42
hi has this been assigned to someone else

**Comment by rimildeyjsr** [comment] 2019-10-04 03:50
@samagragupta @CoderJolly - Hey, just one question, the image above which space has to be created is the one referenced by `main-image` in the `show.html.erb` right?

Adding a top margin gets me this

<img width="1440" alt="Screenshot 2019-10-04 at 9 18 51 AM" src="https://user-images.githubusercontent.com/10229595/66179842-1b54e500-e688-11e9-880a-906f01fba402.png">

Just want to make sure it is the correct image I am adding a margin above to 😅

**Comment by SerwaddaUG** [comment] 2019-10-04 14:28
Hello here, i  would like to contribute any information rendered will be of high appreciation

**Comment by neeraj3029** [comment] 2019-10-29 17:12
@samagragupta I would like to work on it, can you assign it to me?

**Comment by samagragupta** [comment] 2019-10-29 17:13
@neeraj3029 Go on 🚀

**Comment by SidharthBansal** [comment] 2019-11-22 19:38
What is the issue number?

**Comment by dmahajan980** [comment] 2019-12-23 13:46
@samagragupta I would like to work on this issue if it isn't fixed.

**Comment by samagragupta** [comment] 2019-12-24 06:41
@dmahajan980 Go ahead 🚀

**Comment by dmahajan980** [comment] 2019-12-24 09:13
@samagragupta I've already solved another 'first-timers-only' issue after I asked for this issue But I would be happy to solve this only if you allow me to do so.

**Comment by SidharthBansal** [comment] 2019-12-25 17:00
If you are a GCI student then you can solve 2 ftos BUT if you are not GCI student then you are allowed to solve only one FTO issue.
It will be highly appreciable if you can help us at non gci issues too.
thanks

**Comment by dmahajan980** [comment] 2019-12-25 18:51
@SidharthBansal thanks for informing! I'm not a GCI student so I guess I'll look for other issues.

**Comment by dmahajan980** [comment] 2019-12-30 13:54
@samagragupta @SidharthBansal since nobody is solving this issue currently, I guess the '_assigned_' label should be removed.
Thanks

**Comment by SidharthBansal** [comment] 2019-12-30 16:40
thanks @dmahajan980

**Closed** 2020-09-29 14:30 UTC
Labels: first-timers-only
