### ISSUE TITLE
bug in the display of contributor notes by tag

### ISSUE THREAD

**Issue by ebarry** [publiclab/plots2#2179] opened 2018-01-30 22:35 UTC
### Please describe the problem

> What happened just before the problem occurred?

I am cataloguing all contributors in a research area, and just looked at all notes tagged wetlands. 
On the contributors tag, https://publiclab.org/contributors/tag/wetlands the people at the bottom are listed as having notes, but when you click on notes, there is unexpected behavior: 

![contributor-notes](https://user-images.githubusercontent.com/161439/35595195-cd5df408-05e3-11e8-9cc0-547c19ec9f1d.gif)

> What did you expect to see that you didn't?

I expected to see a display of notes about wetlands that that contributor wrote that is visually similar to the tag pages. 

### Please show us where to look

https://publiclab.org/contributors/tag/wetlands

**Comment by Gauravano** [comment] 2018-01-31 19:04
Hi @ebarry, actually  https://publiclab.org/contributors/wetlands also renders data from the same source as https://publiclab.org/contributors/tag/wetlands so it's also generating the same error.I want to work on resolving this.

**Comment by jywarren** [comment] 2018-02-06 18:31
This would be great -- did your PR #2226 work out? Thank you!!!

**Comment by Gauravano** [comment] 2018-02-06 18:42
> This would be great -- did your PR #2226 work out? Thank you!!!

Hi Jeff, #2226 is an issue opened by @rishabhptr but closed after he noticed that the same issue already exists here, so I guess this issue is open to be claimed.Thanks

**Comment by jywarren** [comment] 2018-02-06 18:50
ah, sorry i assumed it was a PR but that makes sense. This issue could use
a bit more detail and I bet we can find someone to fix it! Thanks!

**Comment by Gauravano** [comment] 2018-02-06 18:58
I can try fixing this.What you say?

**Comment by jywarren** [comment] 2018-02-06 19:48
sure, that'd be great, thanks!!

**Comment by jywarren** [comment] 2018-02-06 20:09
Ah, but is this a duplicate of #2178?

**Comment by jywarren** [comment] 2018-02-06 20:10
I think it is! Merging this then. Thanks!

**Closed by jywarren** 2018-02-06 20:10 UTC
