### ISSUE TITLE
comments on questions not editiable despite edit button

### ISSUE THREAD

**Issue by shapironick** [publiclab/plots2#5354] opened 2019-04-03 01:44 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
I tried to edit this comment because i misspelled the second word.

But it just sent me to a screen where I could @ myself to alert myself of the need to edit??? idk
Here's a gif of what it looked like:

![Can't edit](https://user-images.githubusercontent.com/7503343/55446937-be208f80-558f-11e9-8652-2e3059e339bb.gif)

> What did you expect to see that you didn't?

I expected to see the text of the comment so that I could edit it. 

### Please show us where to look

https://publiclab.org/questions/warren/04-02-2019/what-are-some-activities-for-using-the-simple-air-sensor-as-part-of-a-broader-air-quality-project

### What's your PublicLab.org username?

> This can help us diagnose the issue: @nshapiro

### Browser, version, and operating system
firefox 65.0.1 (64-bit) mac 10.14.3 
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by GettyOrawo** [comment] 2019-04-03 08:10
hey @shapironick this looks like a similar issue to #5318 that's already being worked on. What do you think?

**Comment by shapironick** [comment] 2019-04-03 12:40
Yes I think your right! also your documentation is waaaaaay better

**Comment by gauravano** [comment] 2019-04-04 14:27
Hi @shapironick @GettyOrawo, as the issue is already open for this bug, how about closing this issue? Thanks!

**Closed** 2019-04-04 18:35 UTC
Labels: bug
