### ISSUE TITLE
follow button in dashboard

### ISSUE THREAD

**Issue by keshavsethi** [publiclab/plots2#7811] opened 2020-04-13 19:15 UTC
After following all the suggested tags and then altering the following suggestions by clicking on the checkboxes as shown. The follow button doesn't unfollow the non selected tags that were followed previously. 
Suggestions:
1.)It should either disable the list item's checkbox which is already followed or give some message that the selected tags are already followed by the user.  
2.) suggest only those tags in the list which are not followed by the user.

Note: This button has no use if all the tags are already followed by the user as shown in the image.
![Screenshot from 2020-04-14 00-42-55](https://user-images.githubusercontent.com/36025262/79151929-f84e7f00-7de8-11ea-9f2c-4ed5907994d4.png)

Thanks!

**Comment by chinmay021** [comment] 2020-04-23 01:45
Can you please provide the code linked to this page?

**Comment by jscastanos** [comment] 2020-05-09 11:55
possible duplicate of #7762

**Comment by jywarren** [comment] 2020-10-12 15:14
I'm going to close this in preparation for the new dashboard being created! Thank you though!!

**Closed by jywarren** 2020-10-12 15:14 UTC
Labels: bug
