### ISSUE TITLE
Updated Timestamp shown incorrectly in the questions sidebar 

### ISSUE THREAD

**Issue by Tlazypanda** [publiclab/plots2#7591] opened 2020-03-03 06:48 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

The questions sidebar shows updated by which is actually the created by date.Even after updating it is only checking the time passed since the creation date.
![image](https://user-images.githubusercontent.com/33183263/75749844-cc9b9c00-5d48-11ea-9c20-49ca06b83310.png)
![image](https://user-images.githubusercontent.com/33183263/75749898-e9d06a80-5d48-11ea-8404-ab306ebb81df.png)

### Please show us where to look
/question/

**Comment by Tlazypanda** [comment] 2020-03-03 06:49
@VladimirMikulic can you kindly approve? Thanks :v:

**Comment by VladimirMikulic** [comment] 2020-03-03 07:07
This is great. Thanks @Tlazypanda.

**Comment by cesswairimu** [comment] 2020-03-15 20:19
@Tlazypanda on the timestamp we would like to show the actual time that the question was created not updated. Closing this as its not a bug. Thanks

**Closed by cesswairimu** 2020-03-15 20:19 UTC
Labels: bug

**Comment by Tlazypanda** [comment] 2020-03-16 04:30
@cesswairimu but the text says updated and not created in the second screenshot in the issue description 😅

**Comment by Tlazypanda** [comment] 2020-03-19 06:00
@cesswairimu @SidharthBansal  shouldn't we change that text to created in order to avoid confusion? Kindly have a look at the second screenshot. Thanks :v:
