### ISSUE TITLE
Irregularities in positioning of social media buttons in wiki page

### ISSUE THREAD

**Issue by sukhbir-singh** [publiclab/plots2#2328] opened 2018-02-14 20:55 UTC
### Please describe the problem (or idea)
Social media buttons of Facebook and Twitter in wiki page are not aligned equally. 

### Please show us where to look
Browse to any wiki page like
https://www.publiclab.org/wiki/advanced-grids
and observer positioning of social media buttons below tags selection area.

![screenshot from 2018-02-15 02-02-30](https://user-images.githubusercontent.com/13816752/36227369-e85d6c7e-11f6-11e8-97ea-dda1003488b1.png)

**Comment by sukhbir-singh** [comment] 2018-02-14 20:55
Currently working on this one !!

**Comment by Gauravano** [comment] 2018-02-15 12:05
Hi @sukhbir-singh , I guess its duplicate of #2289

**Comment by sukhbir-singh** [comment] 2018-02-15 15:48
@Gauravano Sorry for that, I didn't noticed the the older issue.

**Comment by Gauravano** [comment] 2018-02-15 15:49
It's fine

**Comment by jywarren** [comment] 2018-02-15 20:54
:-) thanks! Closing this then.

**Closed by jywarren** 2018-02-15 20:54 UTC
