### ISSUE TITLE
Welcome, Outreachy aspirants! (Summer- 2019) 

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#5022] opened 2019-03-11 23:37 UTC
Hello folks from Outreachy - We realized we don't have a main place for you all to ask questions and get support, so we wanted to say WELCOME and create this issue as a discussion zone. Please leave a comment to say hello, in part so we know who's interested in the program! @publiclab/reviewers @publiclab/plots2-reviewers @publiclab/mentors please keep an eye open for opportunities to welcome and support our Outreachy applicants! 👍 🎉 

## First contribution

It's so great to see that several of you have made your first contribution. 🙌 This should really help as all our contributions follow this workflow. If you haven't yet, please see this page to get started:

https://code.publiclab.org

## What next?

If you're looking for a next project, we might recommend one which starts to involve multiple files in the application code, so you can start to get a better understanding of the application's workings. Are you familiar with how a Rails application works, in terms of how the model accesses the database, the controller performs the logic, and the views display the actual web pages? If not, we can help you start to pick apart how our system works one piece at a time. 

You can find a lot of relatively small but not completely documented issues here:

https://github.com/publiclab/plots2/labels/fto-candidate

If you choose one, please leave a comment and we can do our best to help find any missing information or help guide you through the next steps. Don't hesitate to ask questions!

Larger collections of tasks can often be found under the `break-me-up` label, which you can go through to find smaller projects to "break off" and solve:

https://github.com/publiclab/plots2/labels/break-me-up

## Supporting tasks

Another area you might be interested in contributing is in supporting other new people to the project. This is an often unrecognized part of a healthy collaborative project, so we've made these issues to encourage people to take part in this crucial activity. We'd love your help, and as a newcomer yourself, you know exactly what it feels like to be new, so you know how important it is to be welcoming and supportive!

https://github.com/publiclab/plots2/labels/support

You can help new contributors in getting started by creating new FTO issues - https://github.com/publiclab/plots2/issues/4963

### Outreachy Projects

**1. PublicLab.org UI improvements**: https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#publiclaborg-ui-improvements

GitHub issue: https://github.com/publiclab/plots2/issues/4922

**2. Extend Leaflet Environmental Layers with new layer menu and layer addition workflow**: 
 https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#extend-leaflet-environmental-layers-with-new-layer

GitHub issue: https://github.com/publiclab/leaflet-environmental-layers/issues/134

### CALL FOR OUTREACHY PROPOSALS

We've posted a call for proposals here, where we'd like to ask each of you to open a draft proposal and get some comments on it! Thank you!!

https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals

Thanks and we're happy to answer questions!!

**Comment by madeofhuman** [comment] 2019-03-12 00:44
Hi! I'm so happy to be here. This community has been really nice and supporting. I'm really excited to have made my first OSS contribution here and I'm looking forward to adding more value to the project. 😄

**Comment by CleverFool77** [comment] 2019-03-12 02:11
Hey Everyone, I'm Lekhika. It's amazing to be part of this organisation. I mean never been so overwhelmed.
The support given here to first-timers is awesome.
Thanks a lot and looking forward to further guidance in this journey :).

**Comment by Anjalizi** [comment] 2019-03-12 02:38
Hello everyone, my name is Anjali. 
The journey so far has been great and I am eager to learn more about Public Lab's projects. :smile:

**Comment by ananyaarun** [comment] 2019-03-12 05:56
Hi everyone, I'm Ananya Arun.
The past few days has been amazing getting to know the public lab community. Working on installation process, Opening solving and reviewing issues has indeed thought me a lot about working together on an open source project. Looking forward to contribute and learn !! :)

**Comment by divyabaid16** [comment] 2019-03-12 06:32
Hello everyone, I'm Divya Baid, an outreachy applicant. It was great solving the first issue. I had an amazing experience. I'm looking forward to learning the workflow of this project and solving more issues.

**Comment by kuja24** [comment] 2019-03-12 07:14
Hello everyone ! I'm Kuja. I am interested in this project and look forward to make my first contribution

**Comment by helenatxu** [comment] 2019-03-12 07:30
Hello! I am Helena, an Outreachy applicant and I just saw this project and it looks very interesting :) 
Looking forward to make my first contribution.

**Comment by shreyateeza** [comment] 2019-03-12 08:16
Hello everyone! I am Shreya from India and Outreachy applicant. I have already started contributing to the repo. I look forward to contributing as a part of Outreachy.

**Comment by gautamig54** [comment] 2019-03-12 09:44
Hello everyone! I am Gautami and I am really looking forward to contribute to public labs.

**Comment by fabsar** [comment] 2019-03-12 10:26
Hello everyone! I am Sargam , an Outreachy Applicant. I am a first timer and really look forward to be a part of this community!

**Comment by CleverFool77** [comment] 2019-03-12 11:34
@fabsar, Did you went through all first timers issues ? You can add yourself in #4963. And get yourself a issue assigned. Thanks :)

**Comment by fabsar** [comment] 2019-03-12 13:22
Thanks:)

**Comment by gauravano** [comment] 2019-03-12 13:31
CALL FOR OUTREACHY PROPOSALS

Hi everyone,

We've posted a call for proposals here - https://publiclab.org/notes/gauravano/03-12-2019/call-for-outreachy-2019-proposals, where we'd like to ask each of you to open a draft proposal and get some comments on it! Thank you!!

**Comment by bealearnscode** [comment] 2019-03-12 14:47
Hi,
I'm Beatrix, an Outreachy applicant. I'm also a cybersecurity student. I haven't contributed to open source in well over a year, so I'm excited to get re-acquainted with the skill and learn more.

**Comment by aggarwal19** [comment] 2019-03-12 18:04
Hello everyone !
I'm Shridhi and I'm looking forward to make my first contribution in this project .

**Comment by Harshithpabbati** [comment] 2019-03-12 18:05
@aggarwal add your name in the above list. You will be mentioned soon.
Thanks.

**Comment by megha070** [comment] 2019-03-12 18:58
Hello everyone!
This side Megha. I found this project really interesting . Looking forward to contribute to this project.

**Comment by gauravano** [comment] 2019-03-12 19:01
Hi @megha070! 

Are you looking forward for your first contribution as an Outreachy intern?

**Comment by aggarwal19** [comment] 2019-03-12 19:03
@Harshithpabbati , my name is already mentioned in the list (to get first timer issue) .
Thank you for the guidance .

**Comment by megha070** [comment] 2019-03-12 19:05
@gauravano yes!

**Comment by gauravano** [comment] 2019-03-12 19:30
ok, I have added your name to the list - https://github.com/publiclab/plots2/issues/4963 and we'll ping you soon with a issue. Thanks!

Also, you can see issues at https://github.com/publiclab/plots2/issues/ and if find any issue interesting,  then feel free to ask for help, if required.

**Comment by jywarren** [comment] 2019-03-12 23:30
Hello everyone! I am one of the maintainers of the project and I work for the Public Lab non-profit. You'll probably see me all over and please know you're welcome here! I'm overwhelmed by the amazing mutual support you are all showing. 👍 😄 💯 

Our community as you may have guessed runs on kindness and helping one another out 🙌 , so thanks to everyone who's taken their first steps, and ALSO to those who've helped someone else make their first contribution! 

I want to note that while we are excited to participate in Outreachy, we /may/ have more slots available for Google Summer of Code, if past years are any guide. So, if you post a proposal, please think about whether you'd be able to apply to Google Summer of Code as well, where we may have more funding to support additional people. The programs are distinct, but there are similarities, and we'd love to work with as many of you as possible. Thank you! 🎉

**Comment by Ivilili** [comment] 2019-03-13 15:24
Hi everyone, my name is Ivana and I'm interested in becoming a contributor to open source. Public Lab seems like a great project and I'm looking forward in helping and contributing in any way I can.

**Comment by Manvi07** [comment] 2019-03-13 17:59
Greetings everyone!
My name is Manvi Gupta. The Public lab community looks really great and supportive. I would love to contribute to this project. :grinning:

**Comment by SidharthBansal** [comment] 2019-03-17 10:49
Three optional suggestions to SoC students
If you were a GCI mentor please mention it in your proposal. We will give extra credit to these long term collaborators.
Second, it will be great to have a conference or seminar at your university about Public Lab and the programs which are held here. It is optional. No compulsion at all.
Thirdly, help each other in writing their proposals by giving suggestions under the proposals

**Comment by gauravano** [comment] 2019-03-17 12:50
Hi everyone,
### Update:
We have one more project for this Outreachy round:

**Project 2. Extend Leaflet Environmental Layers with new layer menu and layer addition workflow**: 
 https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#extend-leaflet-environmental-layers-with-new-layer

GitHub issue: https://github.com/publiclab/leaflet-environmental-layers/issues/134

Thanks!

**Comment by ananyaarun** [comment] 2019-03-17 13:57
@gauravano , I had a question , so does this mean one of the Public Lab projects will be dropped for this round ? Since the outreachy website mentions only 1 intern while there are 2 projects for Public Labs Community listed. Or is this subject to change ?

**Comment by gauravano** [comment] 2019-03-18 18:08
We would be taking 2 interns 1 for each project. @ananyaarun

**Comment by jywarren** [comment] 2019-03-18 21:39
Oh, actually where does it say only one intern? I believe we have reserved one spot and may potentially get assigned a second but are not yet sure of it. Thank you!

**Comment by ananyaarun** [comment] 2019-03-19 14:56
@jywarren , the outreachy website shows 1 intern 2 projects. Hence i was wondering if one will have to be dropped. But i think this is subject to change as you suggested.

**Comment by ebarry** [comment] 2019-03-19 16:00
Hi Outreachy Aspirants, 
If you are reading this, consider taking a minute to fill out our annual Survey which is going to be closing in another day or so -- your feedback will help our community learn! thanks! More info here: 
https://github.com/publiclab/plots2/issues/4614

**Comment by vaarigupta** [comment] 2019-03-19 18:12
Hello everyone, This is vaari gupta,an outreachy applicant. I am excited to work on FOSS. I have not contributed much in open source community. How can I contribute?

**Comment by fabsar** [comment] 2019-03-19 18:28
Hii @vaarigupta. If you are looking for a first timer issue add yourself here #4963 and you will be assigned an issue soon. All the best:)

**Comment by jywarren** [comment] 2019-03-22 19:27
Thanks to everyone for your proposals so far! I wanted to note also that, as @ananyaarun pointed out, we have opened a second project, which we are not 100% confirmed we'll be accepted for yet, but are hopeful. It relates to [Leaflet Environmental Layers](https://github.com/publiclab/leaflet-environmental-layers/), and you can read more about it here:

https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#extend-leaflet-environmental-layers-with-new-layer

as well as in this issue:

https://github.com/publiclab/leaflet-environmental-layers/issues/134

Thank you!!! :tada:

**Comment by gauravano** [comment] 2019-03-29 19:50
Hey everyone!

We are really happy to see the awesome proposals you all have submitted for the Outreachy and it's definitely going to be a tough call this time. 

We would like to inform you that, we have extended the application deadline of Outreachy project - **[Extend Leaflet Environmental Layers with new layer menu and layer addition workflow](https://www.outreachy.org/may-2019-august-2019-outreachy-internships/communities/public-lab/#extend-leaflet-environmental-layers-with-new-layer)** till April 2, 2019 4pm UTC, so your proposals are very much welcome.

Thank you everyone :tada:

**Comment by jywarren** [comment] 2019-03-30 00:13
Finally, we also recommend that people consider applying to the Summer of Code programs listed here -- you can use the same application as for Outreachy, or choose another from our ideas list (see the link):

https://publiclab.org/notes/warren/02-28-2019/call-for-summer-of-code-2019-proposals

This is because, although Google Summer of Code is not the same, we expect to see quite a few more slots funded by Google in that program and would love to consider your applications as part of that program too. Thank you, and we're happy to answer questions about it! The timeline is a little further back, and applications just opened. If you'd like to cross-list your proposal, please just add the tag `soc-2019-proposals` to your Outreachy proposal and it will be cross-listed, then apply to GSoC at:

http://summerofcode.withgoogle.com

Please note that requirements for applicants are quite different, but for those of you who meet GSoC's requirements, we would love to see your applications there too to increase the chances that we could accept more of you! Thank you!

**Comment by jywarren** [comment] 2019-05-06 23:55
Thank you, everyone - we've been extremely grateful and lucky to work with all of you. As you may have heard our projects with Outreachy were announced today and I wanted to express our gratitude for all of your presence, your work, your skills, and your spirit. Not everyone's project was selected but that does NOT mean we felt your proposals and your work were anything less than tremendous. 💯 We look forward to participating in Outreachy again in the future, and sincerely hope to have another opportunity to work with more of you. 🙌 

And of course I want to congratulate @CleverFool77 and @ananyaarun who we look forward to working with this summer. 🎉

**Closed by jywarren** 2019-05-06 23:55 UTC
Labels: outreachy, summer-of-code
