### ISSUE TITLE
External links containing an `@` at symbol currently parse as public lab usernames.

### ISSUE THREAD

**Issue by emilyashley** [publiclab/plots2#7675] opened 2020-03-17 20:48 UTC
Scenario:
When inserting an external link on a public lab post
And the link contains an `@`
Then it should parse as part of the URL and **not** a link to a public lab username

Screenshot from @joyofsoy:
![Screen Shot 2020-03-17 at 3 47 42 PM](https://user-images.githubusercontent.com/15912063/76900251-fb486500-6866-11ea-8a1f-3f208aae5f0f.png)

Here's an example link to test from the screenshot above: `https://medium.com/@erinargyle/working-during-covid-19-how-to-be-good-at-video-meetings-57f49fdb8dcd` 

A current workaround is to use a site like bit.ly to obfuscate the links, but we'd ideally fix this. Thanks @joyofsoy for reporting! :tada:

**Comment by emilyashley** [comment] 2020-03-17 20:49
Notes from Jeff:
> @jywarren : I think we need to change the @______ pattern matcher to not find the pattern inside of links. The pattern matcher is here: https://github.com/publiclab/plots2/blob/acd5a4910632c8cc80f9fadb54d8cc64c9600519/config/initializers/constants.rb#L2

> Here's a demo of the pattern match failing based on Joe's original links; it has to be modified to NOT recognize usernames inside of URLs: https://rubular.com/r/HsxxuTG8zG0zSL

**Comment by Tlazypanda** [comment] 2020-03-19 09:26
@emilyashley can I work on this?

**Comment by jywarren** [comment] 2020-03-24 14:37
@Tlazypanda that would be super, thank you!!!

**Comment by Tlazypanda** [comment] 2020-03-30 11:12
@jywarren @emilyashley  not exactly sure if this is what is wanted but I modified the regex as this - can you kindly check and guide me a bit :sweat_smile: Thanks :v: 
![image](https://user-images.githubusercontent.com/33183263/77906274-4e79d900-72a5-11ea-91e5-1594eed9bf10.png)

**Comment by ebarry** [comment] 2020-04-29 15:55
Hi @Tlazypanda , did you have a chance to try out any changes using this expression editor? https://rubular.com/r/HsxxuTG8zG0zSL Seems like a little game, to try and adjust how the @names are recognized on our site but not when there is a '/' on either side.

**Comment by Tlazypanda** [comment] 2020-04-29 16:02
Hey @ebarry  I am so sorry totally forgot about this issue while working on other  issues ...is it alright if I take it up after some days since my university examinations are going on :sweat_smile:

**Comment by ebarry** [comment] 2020-04-29 21:34
Of course!!! Good luck on exams!!!

**Comment by gauravahlawat81** [comment] 2020-12-17 16:39
Hey @ebarry, I might need your help.

```
([^`\w]|^)(?<!\/)\@([\w-]+)(?!\/)
``` 
I tried solving this issue using the above regex pattern,and it successfully ignores the starting `/` but doesn't do well when the forward slash is at the end. Refer to the screenshot below.

![First](https://user-images.githubusercontent.com/36696399/102516010-694ee080-40b4-11eb-9960-db8dc67c551c.png)

![Screenshot from 2020-12-17 22-07-48](https://user-images.githubusercontent.com/36696399/102515973-5e944b80-40b4-11eb-920c-7b38484f2507.png)

![Screenshot from 2020-12-17 22-06-44](https://user-images.githubusercontent.com/36696399/102515963-59370100-40b4-11eb-99eb-3b09e09407f7.png)

![Screenshot from 2020-12-17 22-07-23](https://user-images.githubusercontent.com/36696399/102515969-5c31f180-40b4-11eb-9d92-1459235b1b4a.png)

**Comment by gauravahlawat81** [comment] 2020-12-17 17:52
Update 

```([^`\w]|^)(?<!\/)\@([\w-]+)\b(?!\/)``` Seems to be working correctly.Can  you please confirm if this regex is correct or not @ebarry ?

**Comment by gauravahlawat81** [comment] 2020-12-18 15:17
@jywarren Can you confirm this ?

**Comment by ebarry** [comment] 2021-01-05 21:32
I wish i could confirm either way but i'm not familiar with regex, sorry for my delayed response, and THANK YOU for working on this!

**Comment by jywarren** [comment] 2021-01-05 21:54
Works perfectly! https://rubular.com/r/jfKfgjdqi00qy4

![image](https://user-images.githubusercontent.com/24359/103704067-a4875580-4f76-11eb-81ae-51ab06863ecb.png)

This can now be inserted at `constants.rb` -- it'd make a good first-timers-only issue too!

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://code.publiclab.org/#r=all), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @publiclab/reviewers to get it labelled. Or, if this is not your first time, try to solve it yourself!

****

**Comment by ebarry** [comment] 2021-01-05 21:57
Thanks for reviewing this @jywarren! Thank you Gaurav Ahlawat for doing
this!
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net

**Comment by gauravahlawat81** [comment] 2021-01-06 07:07
@ebarry Could you please convert it into FTO, so that others can solve it ? Thank!

**Comment by cesswairimu** [comment] 2021-01-06 07:48
great job @gauravahlawat81 I can do that for you...or maybe you would like to try and convert this yourself?...I am happy to help where stuck..what do you think?

**Comment by gauravahlawat81** [comment] 2021-01-06 07:50
Yeah sure, I would like to convert it by myself. How do I do that ?

**Comment by gauravahlawat81** [comment] 2021-01-06 07:50
Should I create a new issue or edit this one ?

**Comment by cesswairimu** [comment] 2021-01-06 07:54
Great :tada:, yeah  creating a new one would be simpler, when you click on new issue here https://github.com/publiclab/plots2/issues/new/choose select the `First timer Only Issue` and it will prefill a template...after this line where you have ``**Update** the file [$FILENAME]($BRANCH_URL) in the `$REPO` repository (press the little pen Icon) and edit the line as shown below.`` indicate the file that needs to be changed and the changes needed... Give it a title and that should be all

**Comment by gauravahlawat81** [comment] 2021-01-06 07:55
Alright, thanks @cesswairimu , I will give it a try!

**Comment by gauravahlawat81** [comment] 2021-01-06 08:08
@cesswairimu How do I generate the diff ?

**Comment by cesswairimu** [comment] 2021-01-06 08:21
Not sure if there is another way of doing it...the way I do it is using the first-timer-bot
So with this approach what you do is navigate to the file that you want to edit in this case I believe is  https://github.com/publiclab/plots2/blob/main/config/initializers/constants.rb and click on the edit button(pencil icon), make the changes that are needed, then the text-box below this `Create a new branch for this commit and start a pull request` edit that and make sure it starts with `first-timers-` then click commit changes...


after that you should see your issue created here https://github.com/publiclab/plots2/issues/ with author as first-timer-bot
more documentation on this is [here](https://probot.github.io/apps/first-timers/) if this doesn't make sense

**Comment by gauravahlawat81** [comment] 2021-01-06 08:33
I have created the issue, though I had to use a different approach. Please see if everything is fine there, and if something needs to be changed, do let me know.

**Comment by cesswairimu** [comment] 2021-01-06 08:37
The issue is perfect..thanks again

**Comment by cesswairimu** [comment] 2021-01-08 08:17
FTO link https://github.com/publiclab/plots2/issues/8947

**Comment by cesswairimu** [comment] 2021-01-08 09:58
Fixed in https://github.com/publiclab/plots2/pull/8972 Thanks everyone

**Closed by cesswairimu** 2021-01-08 09:58 UTC
Labels: Ruby, help wanted, ws

**Comment by ebarry** [comment] 2021-01-08 15:28
Thank you all!
Very neat workflow
--

+1 336-269-1539 / @lizbarry <http://twitter.com/lizbarry> / lizbarry.net
