### ISSUE TITLE
Limit extra long wiki titles

### ISSUE THREAD

**Issue by GettyOrawo** [publiclab/plots2#5426] opened 2019-04-09 09:17 UTC
Hi, this is a [first-timers-only issue](https://code.publiclab.org/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

There is a small section of wiki title creation that hasn't been taken care of. A wiki title needs to be as brief as any other title. However there are no limits to this when creating a wiki. http://localhost:3000/wiki  Our title can, in worst case, look like this:

![long-wiki](https://user-images.githubusercontent.com/17080976/55788133-6bc7fd00-5ac0-11e9-9f20-ee866e2ac212.gif)

We can add an HTML attribute `maxlength=""` to the title field and set it equal to the number of characters you are limiting to. In our case we can limit title characters to 50 or 60. Your choice.

The target file and line number is: 
https://github.com/publiclab/plots2/blob/master/app/views/wiki/edit.html.erb#L61

Add the attribute to this input tag and test if it is working. Note that only admins can create new Wikis so you will have to log in as an admin if you want to see this play on your local server. All the best! :smile: 

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### Please keep us updated

💬⏰ - We encourage contributors to be respectful to the community and provide an update **within a week** of claiming a first-timers-only issue. We're happy to keep it assigned to you as long as you need if you update us with a request for more time or help, but if we don't see any activity a week after you claim it we may reassign it to give someone else a chance. Thank you in advance! 

If this happens to you, don't sweat it! Grab another open issue.

### Is someone else already working on this?

🔗- We encourage contributors to link to the original issue in their pull request so all users can easily see if someone's already started on it. 

👥- **If someone seems stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://code.publiclab.org/#r=all). Thanks!

### 🤔❓ Questions?

Leave a comment below!

**Comment by GettyOrawo** [comment] 2019-04-09 09:21
@publiclab/reviewers

**Comment by HarshKhandeparkar** [comment] 2019-04-09 09:53
@publiclab/plots2-reviewers

**Comment by GettyOrawo** [comment] 2019-04-09 11:43
Thank you :slightly_smiling_face:

**Comment by jeremypurser** [comment] 2019-04-09 23:41
Hi! Could I claim this?

**Comment by GettyOrawo** [comment] 2019-04-11 04:28
sure @jeremypurser ! :smile:

**Comment by Aaru143** [comment] 2019-09-11 00:33
Is this issue still open ? Can I claim it ?

**Comment by IshaGupta18** [comment] 2019-09-11 03:07
Can you try to reproduce the problem on public lab's website and check if the problem still exists? If it does, go ahead and solve it!

**Comment by kvenkman** [comment] 2019-10-03 04:07
#6381 Submitted a PR here

**Comment by discombobulateme** [comment] 2019-10-03 17:52
Hello :) may I be assigned to contribute on this issue?

**Comment by IshaGupta18** [comment] 2019-10-03 19:02
I think someone has already submitted a PR on this, could you please find
some other issue to work on? Thank you

**Comment by cesswairimu** [comment] 2021-04-03 21:56
Looks like this is not solved yet...I will update the details and maybe we should limit it 200 or 150...the longest title I could find on the website is 143 chars

**Comment by cesswairimu** [comment] 2021-04-03 22:06
Just ran into https://github.com/publiclab/plots2/pull/6381#issuecomment-575679544 . Closing this. Thanks all

**Closed by cesswairimu** 2021-04-03 22:06 UTC
Labels: first-timers-only, unassigned
