### ISSUE TITLE
Align pagination to the center of the body

### ISSUE THREAD

**Issue by DakshGondaliya** [publiclab/plots2#3732] opened 2018-10-22 14:19 UTC
### Please describe the problem (or idea)
Current pagination is on the left side of the body part. Align it in the center of the body part.
> What happened just before the problem occurred? Or what problem could this idea solve?
![screenshot 250](https://user-images.githubusercontent.com/25260367/47297642-45f28d00-d633-11e8-930f-0feec8e6cdad.png)

> What did you expect to see that you didn't?
![screenshot 251](https://user-images.githubusercontent.com/25260367/47306723-dc7e7880-d64a-11e8-82f2-475dde88431c.png)

### Please show us where to look
https://infragram.org/

### What's your PublicLab.org username?
dynamic_daksh
> This can help us diagnose the issue: 

### Browser, version, and operating system
Windows 10, Google Chrome Version 70.0.3538.67 (Official Build) (64-bit)
> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment] 2018-10-22 15:39
Published onto GCI dashboard

**Comment by DakshGondaliya** [comment] 2018-10-22 20:21
Thank you @SidharthBansal

**Comment by CodeSarthak** [comment] 2018-10-25 16:02
I am willing to accept this as part of GCI, where is the source file?

**Comment by gauravano** [comment] 2019-02-13 10:36
Hi @jywarren, although the PR raised for the issue is merged but the https://infragram.org still have same un-aligned pagination bar. Have you pushed the commit to production or this issue should be transferred to infragram repo? 

Thanks!

**Comment by jywarren** [comment] 2019-02-13 22:06
I think we are done here, thank you! https://github.com/publiclab/infragram-js/pull/9

We'll publish soon - thanks a lot!

**Closed by jywarren** 2019-02-13 22:06 UTC
Labels: enhancement, more-detail-please

**Comment by gauravano** [comment] 2019-02-14 10:07
Great!
