### ISSUE TITLE
ical files are broken

### ISSUE THREAD

**Issue by dbeavers** [publiclab/plots2#302] opened 2015-07-23 23:57 UTC
For example, if you download the ical on http://www.publiclab.org/notes/stevie/07-08-2015/new-orleans-map-viewing-party and then view the file contents you will find it is useless.
BEGIN:VCALENDAR
VERSION:2.0
BEGIN:VEVENT
CLASS:PUBLIC
DESCRIPTION:false
DTSTART;VALUE=DATE:0NaNaNaNTaNaNaN
DTEND;VALUE=DATE:0NaNaNaNTaNaNaN
LOCATION:false
SUMMARY;LANGUAGE=en-us:New Orleans Map Viewing Party
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR

**Comment by ebarry** [comment] 2018-01-09 21:49
hi @dbeavers is this still an issue?

**Comment by dbeavers** [comment] 2018-01-10 03:50
I can't find any way to check it now.  Where can I find a page that
generates a .ical file?

**Comment by ebarry** [comment] 2018-01-10 16:24
hmm i'm not sure. We might not be doing iCal at all anymore, in which case we could also close https://github.com/publiclab/plots2/issues/354

**Comment by jywarren** [comment] 2018-01-17 00:55
https://publiclab.org/feed/tag/event:rsvp.ics -- see #354 -- although we could add a new one to make this link more visible.

**Comment by jywarren** [comment] 2018-01-17 00:57
I believe this is a duplicate of #354, which was an experimental and unfinished feature -- head over there for next steps!

**Closed by jywarren** 2018-01-17 00:57 UTC
