### ISSUE TITLE
Webpage crashes on closing `map-intro` popup in firefox

### ISSUE THREAD

**Issue by daemon1024** [publiclab/plots2#9287] opened 2021-03-11 20:16 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

On the map route, when you try to close the `map-intro` popup the webpage crashes. This is limited to firefox browser and seems to be working fine on chromium based browsers.

> What did you expect to see that you didn't?

The rest of the webpage should function normally even after closing it.

### Please show us where to look

https://publiclab.org/map

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

barun1024

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

Firefox 84+, Linux and Windows

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by daemon1024** [comment] 2021-03-11 20:24
https://user-images.githubusercontent.com/47106543/110850450-cdf59200-82d5-11eb-8ae2-9d29ecc39c8d.mp4

Screen cast showing the error :)

**Comment by 17sushmita** [comment] 2021-03-15 12:44
I'm not able to reproduce the error. It is working fine on my browser. Can you give more context?

**Comment by daemon1024** [comment] 2021-03-15 17:55
@17sushmita which browser are you using 🤔 I have mentioned my browser version in the issue description and as I said it's working fine on chromium based browsers/.

**Comment by jywarren** [comment] 2021-03-16 20:15
Aha, this is the code - it's actually kept in the database --

```js
<div class="map-intro">
  <a style="float:right;margin-top:-14px;" href="javascript:$('.map-intro').toggle()"><i style="color:#888;" class="fa fa-times"></i></a>
  <h3>Public Lab by region</h3>
  <p>This is a map of people, posts, and pages on PublicLab.org. Use the upper-left menu to view nearby environmental data as well.</p>
</div>
```

I guess this doesn't work in non-chrome? What should we change it to? Thank you for catching this!!!!

**Comment by daemon1024** [comment] 2021-03-16 20:58
I can see that it is considered a bad idea to execute javascript code in href.

**Comment by daemon1024** [comment] 2021-03-16 21:01
I can turn this into an FTO if you approve this change :)

**Comment by jcads** [comment] 2021-03-22 00:28
Can I work on this one?

**Comment by jcads** [comment] 2021-03-22 09:14
> Aha, this is the code - it's actually kept in the database --
> 
> ```js
> <div class="map-intro">
>   <a style="float:right;margin-top:-14px;" href="javascript:$('.map-intro').toggle()"><i style="color:#888;" class="fa fa-times"></i></a>
>   <h3>Public Lab by region</h3>
>   <p>This is a map of people, posts, and pages on PublicLab.org. Use the upper-left menu to view nearby environmental data as well.</p>
> </div>
> ```
> 
> I guess this doesn't work in non-chrome? What should we change it to? Thank you for catching this!!!!

Can we manually change this code?

**Comment by daemon1024** [comment] 2021-03-23 16:11
cc @publiclab/plots2-reviewers

**Comment by RuthNjeri** [comment] 2021-03-28 11:44
@jcads yes, the code can be manually changed but only through the database, you could try finding a fix for this locally and sharing it here, once it's confirmed, all @jywarren needs to do is update the code within the database. Does that make sense?

There are instances on the Public Lab site where the code is saved within the database, not on the files.

**Comment by jywarren** [comment] 2021-05-25 22:14
I changed this to:

```html
  <span style="float:right;margin-top:-14px;" onclick="$('.map-intro').toggle()"><i style="color:#888;" class="fa fa-times"></i></span>
```

Can you check if this works? Thanks everyone for the help!!!

**Closed** 2021-05-25 22:14 UTC
Labels: bug
