### ISSUE TITLE
Test `test_tag_index(TagControllerTest)` fails

### ISSUE THREAD

**Issue by vishaldeepak** [publiclab/plots2#1550] opened 2017-07-26 05:54 UTC
### What happened just before the problem occurred
Running `rake test` on the master branch seems to be failing one test. `test_tag_index(TagControllerTest)- test_tag_index(TagControllerTest)
test/functional/tag_controller_test.rb:114:in block in <class:TagControllerTest`

```
Failure:
  <[#<Tag tid: 11, vid: 0, name: "upgrade:latest", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 10, vid: 0, name: "activity:coding", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 14, vid: 0, name: "activity:spectrometer", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 2, vid: 0, name: "awesome", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 9, vid: 0, name: "blog", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 5, vid: 0, name: "chapter", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 7, vid: 0, name: "lat:71.0", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 8, vid: 0, name: "lon:52.0", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 6, vid: 0, name: "question:spectrometer", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 12, vid: 0, name: "spectrometer", description: nil, weight: 0, count: nil, parent: "spectrometry">,
   #<Tag tid: 1, vid: 0, name: "test", description: nil, weight: 0, count: nil, parent: nil>,
   #<Tag tid: 16, vid: 0, name: "activities:spectrometer", description: nil, weight: 0, count: nil, parent: nil>]> expected but was
  <[#<Tag tid: 16, vid: 0, name: "activities:spectrometer", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 10, vid: 0, name: "activity:coding", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 14, vid: 0, name: "activity:spectrometer", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 2, vid: 0, name: "awesome", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 9, vid: 0, name: "blog", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 5, vid: 0, name: "chapter", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 7, vid: 0, name: "lat:71.0", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 8, vid: 0, name: "lon:52.0", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 6, vid: 0, name: "question:spectrometer", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 12, vid: 0, name: "spectrometer", description: nil, weight: 0, count: nil, parent: "spectrometry">, #<Tag tid: 1, vid: 0, name: "test", description: nil, weight: 0, count: nil, parent: nil>, #<Tag tid: 11, vid: 0, name: "upgrade:latest", description: nil, weight: 0, count: nil, parent: nil>]>.
test_tag_index(TagControllerTest)
test/functional/tag_controller_test.rb:114:in `block in <class:TagControllerTest>


```

### Browser, version, and operating system
Mac OS Sierra - 10.12.5

**Comment by jywarren** [comment] 2017-08-07 15:19
This looks like an ordering issue -- the test specifies:

```ruby
assert_equal assigns['tags'].sort_by(&:count), assigns['tags']
```

But `count` seems to be nil in both cases, so it doesn't know how to sort. This happened because in the test data, none of the nodes have been "viewed" -- so they don't have a count (my best guess).

I think we need to simply sort both `tid` with `.sort_by(&:tid)` and they should then be equal. Could you open a pull request with that change on line 114 of `test/functional/tag_controller_test.rb` ?

Thank you!

**Comment by kkavita92** [comment] 2017-08-15 22:56
@jywarren Happy to jump on this if no one is taking a look!

**Comment by ryzokuken** [comment] 2017-08-16 12:47
@kkavita92 sure, give it a try!

**Comment by kkavita92** [comment] 2017-08-18 03:55
@ryzokuken Thanks, will get back to you with something in a couple of days 👍

**Comment by jywarren** [comment] 2017-08-21 10:51
I wasn't able to reproduce this, so maybe the first thing to check is if you see this error when you run tests at all. If not, and if nobody else can reproduce this, we might close it for now! Thanks!!

**Comment by sagarpreet-chadha** [comment] 2017-10-18 21:33
<img width="991" alt="screen shot 2017-10-19 at 2 22 05 am" src="https://user-images.githubusercontent.com/14952645/31743188-d4a2c378-b477-11e7-9001-836a45495735.png">

@jywarren sir...while testing i encountered the same test failing . Can i work on this ?

**Comment by jywarren** [comment] 2017-10-19 00:23
Cool, have you tried the remedy I proposed above? 

>  sort both `tid` with `.sort_by(&:tid)`

Seems like that could resolve the issue. Please give it a try!

**Comment by sagarpreet-chadha** [comment] 2017-10-19 05:33
Yes sir you are correct , the remedy solves the problem .

**Comment by jywarren** [comment] 2017-10-23 17:51
Super, merged!!!

**Closed by jywarren** 2017-10-23 17:51 UTC
Labels: bug, fto-candidate, help-wanted, testing
