### ISSUE TITLE
Link To Action stats/subscriptions broken 

### ISSUE THREAD

**Issue by sagarpreet-chadha** [publiclab/plots2#1717] opened 2017-10-24 13:01 UTC
This issue refers to #1525 .

### What happened just before the problem occurred

On clicking the link (shown in image) 
<img width="1264" alt="screen shot 2017-10-24 at 5 56 14 pm" src="https://user-images.githubusercontent.com/14952645/31942979-ca12c07c-b8e4-11e7-83c9-35eda84b7b67.png">

we get following error : 
<img width="481" alt="screen shot 2017-10-24 at 5 59 04 pm" src="https://user-images.githubusercontent.com/14952645/31943068-184cc3f0-b8e5-11e7-8423-b8f239b186d9.png">

### Relevant URLs

There is a naming error on line : 
https://github.com/publiclab/plots2/blob/85e74d597bb6015ab1abb553238fcd483906e0a7/config/routes.rb#L201
should be  match 'stats/subscriptions' => 'stats#subscriptions'    instead   of 
 match 'stats/subscriptions' => 'stats#subscription' . 

Also 
https://github.com/publiclab/plots2/blob/85e74d597bb6015ab1abb553238fcd483906e0a7/app/controllers/stats_controller.rb#L5
There is an undefined method tag.name which should be tag.tagname .

Also there must be a test for this action in : 
` /tests/functional/stats_controller_test.rb`

### Browser, version, and operating system

For bug reports, fill out the above template; for feature requests, you can delete the template.

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by jywarren** [comment] 2017-10-25 22:25
Hi, this would make a terrific first-timers-only issue!

****

This has been marked as a good candidate for becoming a [first-timers-only issue](http://www.firsttimersonly.com) like [these](https://github.com/publiclab/plots2/labels/first-timers-only), meaning that it's simple, self-contained, and with some extra formatting, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider [reformatting or reposting it as a first-timers-only issue](https://publiclab.org/notes/warren/10-31-2016/create-a-welcoming-first-timers-only-issue-to-invite-new-software-contributors), and then ping @jywarren to get it labelled. Or, if this is not your first time, try to solve it yourself!

**Comment by ViditChitkara** [comment] 2017-10-26 06:33
@sagarpreet-chadha are you working on it?
If not, shall I try it?

**Comment by sagarpreet-chadha** [comment] 2017-10-26 09:56
@ViditChitkara...no i am not working on this issue :)

**Comment by ViditChitkara** [comment] 2017-10-26 10:02
Ok, I'll fix it. Thanks for the update @sagarpreet-chadha

**Closed** 2017-10-26 18:18 UTC
Labels: bug, fto-candidate, help-wanted

**Comment by ebarry** [comment] 2018-09-13 14:40
Hi! Thank you for fixing this!
I'm wondering if this is what this page is supposed to look like?

<img width="833" alt="screen shot 2018-09-13 at 10 39 27 am" src="https://user-images.githubusercontent.com/161439/45495476-531d8180-b741-11e8-8141-43b302eb3b60.png">

**Comment by jywarren** [comment] 2018-09-13 19:05
I don't remember this page, but from the code history it looks like it was intended to show as succinctly as possible how many subscribers there were for different tags, as per a request you made in 2016. That does seem like how the page is supposed to look! My guess is that it was part of a very big (#964) set of changes and we didn't block out time to do an interface since it answered an urgent question you had.
