### ISSUE TITLE
Weird warnings while testing

### ISSUE THREAD

**Issue by ryzokuken** [publiclab/plots2#2365] opened 2018-02-17 21:42 UTC
While testing locally, I'm seeing weird warnings:

```
/Users/ryzokuken/.rvm/gems/ruby-2.3.4/gems/activerecord-4.1.16/lib/active_record/associations/builder/collection_association.rb:38: warning: already initialized constant TagNodeAssociationExtension
/Users/ryzokuken/.rvm/gems/ruby-2.3.4/gems/activerecord-4.1.16/lib/active_record/associations/builder/collection_association.rb:38: warning: previous definition of TagNodeAssociationExtension was here
```

Let's find out why they show up.

/cc @jywarren @publiclab/reviewers

**Comment by seafr** [comment] 2018-02-18 16:53
I have been seeing this for some time now (and I thought it was a problem with my setup).

**Comment by MayankKashyap** [comment] 2018-02-18 16:55
Same on my case..

**Comment by SidharthBansal** [comment] 2018-02-18 19:09
Me too

**Comment by jywarren** [comment] 2018-02-20 19:31
Yes! This would be great to solve :-)

**Comment by sashadev-sky** [comment] 2019-09-11 12:51
This error is often coming up from dependencies and you cannot fix without updating. We came across a lot of them in MK in the past few months. after updates, they are all gone.

I think they are harmless, but annoying

**Comment by simonastefan** [comment] 2019-09-11 13:14
While the warning is in the activerecord gem, the cause for this one is in the PL code. From the PR: Warnings caused by double association declaration: tag has_many node through 2 different tables. Only one is valid and still exists.
The two association both eventually trigger same constant creation in the gem.
`has_many :node, through: :drupal_node_tag do`
`has_many :node, through: :node_tag do`

While it has no functional impact, the cause is leftover legacy code. Also, the code comment stating that the first has_many applies is false and can be misleading.

**Comment by jywarren** [comment] 2019-09-11 14:45
Great sleuthing. Let's remove `has_many :node, through: :drupal_node_tag
do` then -- does that sound right to people?

**Comment by jywarren** [comment] 2019-12-13 20:01
We believe this is fixed in https://github.com/publiclab/plots2/issues/2365 - please rebase your pull requests over the latest `master` branch to confirm, thank you all for identifying this issue and for your patience! And thanks @cesswairimu for the fix!!! 🙌 💪 🎉

**Comment by jywarren** [comment] 2019-12-13 20:02
Ah oops my last message was for https://github.com/publiclab/plots2/issues/6950 - re-opening this one!

**Closed** 2020-01-17 15:49 UTC
Labels: Ruby, bug, help wanted, testing
