### ISSUE TITLE
make Markdown preview match Rails-rendered Markdown

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#234] opened 2015-02-21 02:56 UTC
@Fastie sez:

> In a [comment on a research note](http://publiclab.org/notes/cfastie/11-07-2013/focus-on-filters), this markdown for a table:

`| ......Camera......|.............. Variable Iris..........   |     .......ND filter(s)  |  
| -------------------------- |:-----------------------:| :--------------------:|  
| SD1100| no | yes|  
| A2200 | no     |   yes |  
| A495 | yes (2 round holes)    |    ? |  
| SX120 | yes (~6 leaves)    |    ? |  
| S95 | yes (6 leaves)     |    ? |  `

> parses correctly in preview mode but does not parse to a table like this when published:

| ......Camera......|.............. Variable Iris..........   |     .......ND filter(s)  |  
| -------------------------- |:-----------------------:| :--------------------:|  
| SD1100| no | yes|  
| A2200 | no     |   yes |  
| A495 | yes (2 round holes)    |    ? |  
| SX120 | yes (~6 leaves)    |    ? |  
| S95 | yes (6 leaves)     |    ? |  

@btbonval sez: 

> Standard markdown does not support tables.
http://meta.stackoverflow.com/questions/73566/is-there-any-markdown-to-create-tables
> The preview program is probably supporting extended features (not part of Markdown) which the Ruby renderer does not support.
> The appropriate fix would be to limit the preview program's extended feature set, if possible.

**Comment by btbonval** [comment] 2015-02-21 07:42
I think this covered adequately by #151 and is a complete duplicate of #139

**Closed by btbonval** 2015-02-21 07:42 UTC
Labels: enhancement
