### ISSUE TITLE
Repeated words in a line

### ISSUE THREAD

**Issue by divyabaid16** [publiclab/plots2#5010] opened 2019-03-11 14:56 UTC
Hi, this is a [first-timers-only issue](https://publiclab.github.io/community-toolbox/#r=all). This means we've worked to make it more legible to folks who either **haven't contributed to our codebase before, or even folks who haven't contributed to open source before**. 

If that's you, we're interested in helping you take the first step and can answer questions and help you out as you do. Note that we're especially interested in contributions from people from groups underrepresented in free and open source software!

We know that the process of creating a pull request is the biggest barrier for new contributors. This issue is for you 💝

If you have contributed before, **consider leaving this one for someone new**, and looking through our general [help wanted](https://github.com/publiclab/plots2/labels/help-wanted) issues. Thanks!

### 🤔 What you will need to know.

Nothing. This issue is meant to welcome you to Open Source :) We are happy to walk you through the process.

### 📋 Step by Step

- [ ] 🙋 **Claim this issue**: Comment below. If someone else has claimed it, ask if they've opened a pull request already and if they're stuck -- maybe you can help them solve a problem or move it along!

- [ ] 📝 **Update** At [https://publiclab.org/stats](https://publiclab.org/stats) there are two simultaneous ```and``` present.
There should be only one ```and```.

![Selection_055](https://user-images.githubusercontent.com/32747809/54132948-2ff73480-443b-11e9-831c-8b0ab934049e.png)

Update:

Replace https://github.com/publiclab/plots2/blob/master/config/locales/en.yml#L256 with
`<b>%{notes_count} notes</b> and <b>%{wikis_count} wiki edits</b>`

- [ ] 💾 **Commit** your changes

- [ ] 🔀 **Start a Pull Request**. There are two ways how you can start a pull request:

1. If you are familiar with the terminal or would like to learn it, [here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.

2. You can also [edit files directly in your browser](https://help.github.com/articles/editing-files-in-your-repository/) and open a pull request from there. 

- [ ] 🏁 **Done** Ask in comments for a review :)

### 🤔❓ Questions?

Leave a comment below!

### Is someone else already working on this?

We encourage you to link to this issue by mentioning the issue # in your pull request, so we can see if someone's already started on it. **If someone seem stuck, offer them some help!** Otherwise, [take a look at some other issues you can help with](https://publiclab.github.io/community-toolbox/#r=all). Thanks!

(This issue was created by [First-Timers-Bot](https://github.com/hoodiehq/first-timers-bot).)

**Comment by divyabaid16** [comment] 2019-03-11 14:58
@cesswairimu @gauravano Is this issue correct for first-timers.

**Comment by gauravano** [comment] 2019-03-11 18:55
hey @divyabaid16, you need to update the code link as I have recently merged some changes to en.yml. thanks!

**Comment by divyabaid16** [comment] 2019-03-12 06:14
@gauravano Updated!

**Comment by cesswairimu** [comment] 2019-03-12 07:26
Yes @divyabaid16 its a good first timer issue good catch and thanks :smile: Will get someone to start on this

**Comment by cesswairimu** [comment] 2019-03-12 07:31
Issue for @nazeem1988

**Comment by helenatxu** [comment] 2019-03-12 07:32
Hello, can I /claim it?

**Comment by cesswairimu** [comment] 2019-03-12 07:38
Hello @helenatxu this one is for @nazeem1988, will add on the list and will try and get an issue for you. thanks

**Comment by divyabaid16** [comment] 2019-03-24 07:01
@nazeem1988 do you need any help in this?
I would be happy to help you out!

**Comment by Saad2714** [comment] 2019-07-11 02:21
HI, it seems the issue is still open... can I work on this issue ??

**Comment by divyabaid16** [comment] 2019-07-11 06:50
Ya you can work on this @Saad2714 
Thanks!

**Closed** 2019-07-24 15:24 UTC
Labels: assigned, first-timers-only
