### ISSUE TITLE
Cross-wired zoom and layer issues on inline maps

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#7397] opened 2020-01-30 21:13 UTC
Hi, sorry, i'm just noticing some oddness with the unearthing layer here: 

https://publiclab.org/wiki/onecranston#location

![image](https://user-images.githubusercontent.com/24359/73490814-4839b000-437b-11ea-8afd-d4aca5bae7e0.png)

It seems that the zooming and layer loading are a little cross-wired. Like, i zoom but the unearthing layer doesn't. Could this have something to do with this PR, or something else we recently changed? cc @crisner as well -- thank you!

_Originally posted by @jywarren in https://github.com/publiclab/plots2/pull/7371#issuecomment-580462290_

**Comment by crisner** [comment] 2020-01-31 07:08
The unearthing layer zooms well when I zoom on the map. However, I had issues with zooming the map. It is because two baselayers are loaded on the tile pane causing conflict.
One from here,
https://github.com/publiclab/plots2/blob/3bffa3b78c29049b1940070912a8ca5dc7776c4e/app/assets/javascripts/leaflet_helper.js#L98

And one from within LEL which defaults to using a default baselayer if one is not passed in.
https://github.com/publiclab/plots2/blob/3bffa3b78c29049b1940070912a8ca5dc7776c4e/app/assets/javascripts/leaflet_helper.js#L105-L107

We could remove line 98 from the leaflet_helper.js file and let LEL default to the baselayer within it. But there is an issue with relying on the default baselayer when using multiple maps in a page in the version of LEL used here. The next version has the fix.  The other fix is passing in the baselayers as done here:
https://github.com/publiclab/plots2/blob/3bffa3b78c29049b1940070912a8ca5dc7776c4e/app/views/map/map.html.erb#L92-L104

P.S: The lines are commented out because the correct variable name for the baselayer was not passed in causing a reference error.

**Comment by crisner** [comment] 2020-01-31 10:31
This is a gif of the issue on localhost which is what I encountered when I checked out the inline map in https://publiclab.org/wiki/onecranston#location. This is the same as issue[#376](https://github.com/publiclab/leaflet-environmental-layers/issues/376).
![baselayer-problem](https://user-images.githubusercontent.com/29401459/73531204-f1e27500-443f-11ea-89e8-ee65af92756b.gif)

Depending on how we decide to proceed with this we could use this fix below until we bump LEL. Here's the gif after the fix:
![baselayer-fix](https://user-images.githubusercontent.com/29401459/73531236-00309100-4440-11ea-8df4-120c4cd8994d.gif)

Changing the lines:
1)
https://github.com/publiclab/plots2/blob/505e13f88ca2efa9fd889f29d284928315ec542d/app/assets/javascripts/leaflet_helper.js#L98
to
```
var baselayer = L.tileLayer('https://a.tiles.mapbox.com/v3/jywarren.map-lmrwb2em/{z}/{x}/{y}.png').addTo(map) ;
```
2)
https://github.com/publiclab/plots2/blob/505e13f88ca2efa9fd889f29d284928315ec542d/app/assets/javascripts/leaflet_helper.js#L105-L107
to
```
L.LayerGroup.EnvironmentalLayers({
        baseLayers: {
          'Gray-scale': baselayer
        },
         include: layers,
      }).addTo(map);
```
3)
https://github.com/publiclab/plots2/blob/505e13f88ca2efa9fd889f29d284928315ec542d/app/assets/javascripts/leaflet_helper.js#L132-L134
to
```
var baselayer = L.tileLayer('https://a.tiles.mapbox.com/v3/jywarren.map-lmrwb2em/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
      }).addTo(map);
```

4)
https://github.com/publiclab/plots2/blob/505e13f88ca2efa9fd889f29d284928315ec542d/app/assets/javascripts/leaflet_helper.js#L141-L143
to
```
L.LayerGroup.EnvironmentalLayers({
        baseLayers: {
         'Gray-scale': baselayer
        },
          hash: !!sethash,
      }).addTo(map);
```

@nstjean, was looking over the baselayer issue and has confirmed that her changes work with the new LEL version. https://github.com/publiclab/leaflet-environmental-layers/issues/376#issuecomment-580423959

**Comment by nstjean** [comment] 2020-01-31 14:18
Yes, we will be removing those baselayers in plots2 as soon as the newest LEL version is in plots2!

**Comment by jywarren** [comment] 2020-01-31 14:34
Hi all, what do you think our schedule is for a new LEL? We could push one through by mid-day today? cc @emilyashley on this fix, just so you see the full lifecycle of a bug => fix => publication, which should be pretty fast!

Thanks, all!

**Comment by jywarren** [comment] 2020-01-31 18:22
Great, is this closed now?

**Comment by nstjean** [comment] 2020-01-31 19:17
Should be fixed with the new LEL, not sure if you want to close it now or wait!

**Comment by nstjean** [comment] 2020-02-19 18:46
This is all fixed with LEL updated!

**Closed by nstjean** 2020-02-19 18:46 UTC
Labels: bug, help wanted
