### ISSUE TITLE
Unable to post comments on research notes

### ISSUE THREAD

**Issue by sashadev-sky** [publiclab/plots2#6083] opened 2019-07-30 01:08 UTC
I've been experiencing it for a while, it comes and goes but is really disruptive. For ex., trying to comment on divys post:

![image](https://user-images.githubusercontent.com/41092741/62092767-6eec2200-b244-11e9-869d-cd15c9262239.png)

Then on page refresh the comment is not there and I see this:

![image](https://user-images.githubusercontent.com/41092741/62092788-87f4d300-b244-11e9-9fd2-21bdb3ef4b64.png)

Commenting on other peoples comments does not work either, although in the past that has sometimes worked while regular commenting has not.

Here are my console errors: 

![image](https://user-images.githubusercontent.com/41092741/62092816-afe43680-b244-11e9-8429-7f03ac9f2380.png)

**Comment by sashadev-sky** [comment] 2019-07-30 01:09
@gauravano there is a contributor working on an action cable project right? Could you please tag him here if so and if you think this relates to that (see console errors)!

**Comment by gauravano** [comment] 2019-07-30 05:05
Looking into it.

**Comment by gauravano** [comment] 2019-07-30 05:10
Hmm, it worked for me. I just left test comments on 2 posts on Divya - https://publiclab.org/notes/divyabaid16/07-22-2019/updated-evaluation-2-gsoc#c25167 and https://publiclab.org/notes/divyabaid16/07-03-2019/mapknitter-multiple-image-export#c25166

Can you try commenting again @sashadev-sky? Also, do you think it maybe due to emoji?

**Comment by gauravano** [comment] 2019-07-30 05:14
Yeah, it's due to comment text. Confirmed from Sentry -  https://sentry.io/organizations/publiclab/issues/1033489492/?project=1410626&query=is%3Aunresolved

**Comment by gauravano** [comment] 2019-08-09 20:10
Hi @sashadev-sky, closing this issue. Please re-open it if you think, problem is not due to the above mentioned reason. Thank you!

**Closed by gauravano** 2019-08-09 20:10 UTC
Labels: bug
