### ISSUE TITLE
Drag and drop feature of comment editor does not work properly when editing a comment

### ISSUE THREAD

**Issue by urvashigupta7** [publiclab/plots2#8670] opened 2020-10-23 04:23 UTC
When a file is uploaded using drag and drop feature it gets added in different text box.
### Steps to reproduce bug :
 * Add file in comment box using drag and drop (Don't post new comment just add the file)
*  Try editing any existing comment, the file will get added in wrong textbox

![ezgif com-video-to-gif (8)](https://user-images.githubusercontent.com/41363633/96956087-db6fd280-1514-11eb-83c9-f38c1e90a7a7.gif)

**Comment by KarenEfereyan** [comment] 2020-10-24 11:35
@cesswairimu is this something i can take up?

**Comment by cesswairimu** [comment] 2020-10-24 12:23
Hi, thanks @urvashigupta7 for opening this, I tested locally and it works fine. @KarenEfereyan could you please check on https://stable.publiclab.org/  could be its fixed but its not deployed yet. If you find the issue on stable you can go ahead. Thanks all

**Comment by urvashigupta7** [comment] 2020-10-24 13:19
Hi @cesswairimu. I am unable to add images while editing the comment on [https://stable.publiclab.org/ ](https://stable.publiclab.org/ ). It just shows never-ending **uploading**

![Screenshot from 2020-10-24 18-49-21](https://user-images.githubusercontent.com/41363633/97082753-a608d900-1629-11eb-9401-749e5f4379a0.png)

**Comment by cesswairimu** [comment] 2020-10-24 15:06
Great investigation, Thanks @urvashigupta7, would you like to work on this  or should @KarenEfereyan give it a try

**Comment by KarenEfereyan** [comment] 2020-10-25 09:49
> 
> 
> Great investigation, thanks @urvashigupta7, would you like to work on this or should @KarenEfereyan give it a try

@urvashigupta7 would you like to work on it? Thanks cess

**Comment by urvashigupta7** [comment] 2020-10-25 10:49
@KarenEfereyan You can try this out 😄 Thanks!!

**Comment by KarenEfereyan** [comment] 2020-10-25 22:58
@cesswairimu could you please assign this to me?

**Comment by KarenEfereyan** [comment] 2020-10-25 23:00
> @KarenEfereyan You can try this out 😄 Thanks!!

I see that you are a competitive programmer. I have been long interested in that. Could you tell me more about it?

**Comment by cesswairimu** [comment] 2020-10-26 07:38
Go ahead @KarenEfereyan

**Comment by urvashigupta7** [comment] 2020-10-26 12:19
> > @KarenEfereyan You can try this out smile Thanks!!
> 
> I see that you are a competitive programmer. I have been long interested in that. Could you tell me more about it?

Sure @KarenEfereyan . I would be happy to help. Let us just connect on [twitter](https://twitter.com/urvashi_g07), we can discuss about this there.

**Comment by KarenEfereyan** [comment] 2020-11-11 17:59
@cesswairimu @urvashigupta7  things have been tough on my side recently. Can you help me to tackle this issue?

**Comment by KarenEfereyan** [comment] 2020-11-12 01:01
@urvashigupta7 i'm unable to replicate the issue. I dragged and dropped files several times and afterward went ahead to edit comments and there are no irregularities. Or am i mistaken?

**Comment by urvashigupta7** [comment] 2020-11-12 03:47
Hi @KarenEfereyan. Edit comment does not work on https://stable.publiclab.org/ but I see edit comment works fine locally. But I am facing the issue I tried to show in the gif above.

**Comment by KarenEfereyan** [comment] 2020-11-12 07:23
> Hi @KarenEfereyan. Edit comment does not work on https://stable.publiclab.org/ but I see edit comment works fine locally. But I am facing the issue I tried to show in the gif above.

Oh okay. Thanks so much

**Comment by jywarren** [comment] 2020-12-01 17:02
Hello all, thank you for investigating and documenting this so carefully. I'm going to edit the title to add some specificity that this is during editing a comment. It may also be different depending on if the edited comment was just made (with no page refresh) or if it was there already, since newly made comments are inserted using JavaScript instead of being built-in at the time the page is prepared by Ruby. 

I'm going to mark this as part of the overall Comment Editor project but whoever would like to work on it, i recommend writing a test that very specifically demonstrates this behavior, of editing a comment then drag-and-dropping an image - and to copy and adapt the test from this example:

https://github.com/publiclab/plots2/blob/a23a3f98a1847a4d6b7f241299a98dfa877d66ee/test/system/comment_test.rb#L136-L156

Thank you so much!

**Comment by jywarren** [comment] 2020-12-01 17:02
and linking to #8775

**Comment by noi5e** [comment] 2020-12-27 05:52
I'm researching this bug right now, and I can consistently reproduce it. Here are some instructions for those curious:

Steps to Reproduce Bug
1. Upload an image to the main comment form (at the bottom of page).
2. Open an edit comment form.
3. Upload an image to the edit comment form.
4. The image doesn't end up in edit form (expected behavior). Instead it ends up in the main comment form (actual behavior).

Bug Notes
- This bug is present in research notes, and questions (not wikis).
- This bug is also present between an edit comment form, and a 'Reply to this comment' form.
  - ie. you can reproduce it if you follow the instructions above, and replace 'main comment form' with 'Reply to this comment' form.
- The bug is present regardless of whether or not you upload via select, or drag-and-drop.
- The bug is present only when an edit comment form is involved.
  - For example, cross-wiring doesn't happen when you upload into the main comment form, then upload into a 'Reply to this comment' form.

I wrote a system test demonstrating this behavior and will open a PR for it shortly.

**Closed** 2021-01-08 22:25 UTC
Labels: JavaScript, bug, help wanted
