### ISSUE TITLE
'click to unfollow' is not working in /tag section

### ISSUE THREAD

**Issue by geekychasser** [publiclab/plots2#4406] opened 2018-12-26 12:26 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

![image](https://user-images.githubusercontent.com/24489162/50445798-16b01300-0937-11e9-8715-81c310da21f2.png)

here we are not able to unfollow the tags direct which we are following and it is redirected to this page,
but we should be able to unfollow directly from ```/tags```

![image](https://user-images.githubusercontent.com/24489162/50445840-5676fa80-0937-11e9-8db8-c241a8080ca4.png)

### Please show us where to look

https://publiclab.org/tags

### What's your PublicLab.org username?

geekychaser

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by oorjitchowdhary** [comment] 2018-12-26 12:49
Hi @geekychaser .. I don't find any unfollow button on the page. I think the `following` button was meant to function like this... 
However, I think we can change this. So instead of the `following` button we show `unfollow` and its function would be to remove that subscription

This seems good.

**Comment by geekychaser** [comment] 2018-12-26 12:54
@oorjitchowdhary on hovering over the ```following``` its show click here to unfollow.
![image](https://user-images.githubusercontent.com/24489162/50446522-44975680-093b-11e9-933d-d35ad00b53eb.png)


so on clicking it button should turn to ```follow``` again rather than redirecting to other page where we need to unfollow again

**Comment by oorjitchowdhary** [comment] 2018-12-26 13:06
I just went through the issue on PL. You're right. 
The `following` button should be firstly renamed to `unfollow`.
Then we see, if the button is clicked you're redirected to `/unsubscribe/tag/tag_name`. I think this where the problem is. 
If you click unfollow on the /tags page or /subscriptions, you're redirected to some URL like `subscriptions?_=1545829506`

**Comment by oorjitchowdhary** [comment] 2018-12-26 13:08
> so on clicking it button should turn to `follow` again rather than redirecting to other page where we need to unfollow again

When you've successfully unsubscribed to a tag. You go to /tags again and then you'd have to refresh it once again to see it the button change to `follow`.

I think this page is missing AJAX. Sorry if I'm wrong

**Comment by geekychaser** [comment] 2018-12-26 13:09
yes exactly this is the issue, and then you there again need to click on this button to this button to unfollow
![image](https://user-images.githubusercontent.com/24489162/50446904-832e1080-093d-11e9-91a7-1803aee7158d.png)

**Comment by gauravano** [comment] 2018-12-28 14:16
Hi @geekychaser @oorjitchowdhary do you guys like to work on this issue together?

**Comment by jywarren** [comment] 2019-10-05 16:41
I think we need to set the data-method to delete in the a tag here!

**Comment by SidharthBansal** [comment] 2019-10-07 17:07
@gauravano I think both of them have abandoned this task.

**Comment by snpd25** [comment] 2019-10-08 02:21
Hey @SidharthBansal , if no one is working on this issue, can I give it a try?

**Comment by renugasaraswathy** [comment] 2020-10-05 12:21
Hi @gauravano @geekychasser,  I would like to work on this issue. Could you assign it to me? Thanks.

**Comment by gauravano** [comment] 2020-10-05 18:40
Hi @renugasaraswathy, go ahead. Thanks!

**Comment by renugasaraswathy** [comment] 2020-10-07 02:06
Hi @gauravano @publiclab/reviewers, just realised that the label "hac**koct**oberfest" used in this repo is incorrect. As per [Hacktober's update](https://hacktoberfest.digitalocean.com/hacktoberfest-update), the label is "hacktoberfest". 

Thanks

**Comment by KarishmaVanwari** [comment] 2022-02-08 20:38
Hey @geekychasser @grvsachdeva , can I take up this issue, if it's open?

**Comment by cesswairimu** [comment] 2022-02-11 05:07
Hi @KarishmaVanwari, The page has gone through some revamps and has fixed most of the issues discussed above is how it is currently:
![Screenshot from 2022-02-11 07-50-01](https://user-images.githubusercontent.com/17081074/153540080-2ecd4c93-6de2-4ea6-b452-4da87a1ce95a.png) The `unfollow` button still redirects to subscriptions page and  we would love your help on this. Thanks

**Comment by cesswairimu** [comment] 2022-09-30 07:15
### 💡Format this Issue Into a First Timers Issue
This has been marked as a good candidate for becoming a [first-timers-only issue](https://code.publiclab.org/#r=all) like these, meaning that it's **simple, self-contained**, and with some extra formatting✍️, could be a great entry point for a new contributor. If you're familiar enough with this code, please consider **reformatting it as a first-timers-only issue**, and then ping @publiclab/reviewers to get it labelled🏷. Or, if this is not your first time, **try to solve it yourself**🧑‍💻!

****
### todo:
This is the method that is called on unfollow.
https://github.com/publiclab/plots2/blob/e1d5fd7a4e1efba3949fdd0887381aee2418b5ff/app/controllers/subscription_controller.rb#L84-L109

Replacing the redirects to `redirect_to request.referrer`  should resolve this

**Comment by ghubrakesh** [comment] 2022-10-04 07:27
Hello @cesswairimu, I would Like to take up this issue.

**Comment by cesswairimu** [comment] 2022-10-04 08:13
hello @ghubrakesh, we would like your help...please go ahead, Thanks

**Comment by cesswairimu** [comment] 2022-10-16 10:02
Converted this to an fto https://github.com/publiclab/plots2/issues/11490. Closing this. Thanks all

**Closed by cesswairimu** 2022-10-16 10:02 UTC
Labels: help wanted, JavaScript, Ruby, fto-candidate, hacktoberfest
