### ISSUE TITLE
Comments and count missing from profile page

### ISSUE THREAD

**Issue by jywarren** [publiclab/plots2#2588] opened 2018-04-06 19:04 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?

@eustatic has certainly commented, but I don't see any on https://publiclab.org/profile/eustatic

I wonder if there's a variable missing from the `profile` method in:

https://github.com/publiclab/plots2/blob/master/app/controllers/users_controller.rb

We ought to test for that too -- a functional test with `assert_not_nil assigns(:comments)` maybe?

**Comment by Gauravano** [comment] 2018-04-06 19:13
okay I guess I know what the problem is, due to this https://github.com/publiclab/plots2/pull/2373 newly generated comments are having status = 1 and while fetching comment_count we are taking considering those comments with status = 0 only. @jywarren please have a look at https://github.com/publiclab/plots2/pull/2373#discussion_r170422216

**Comment by jywarren** [comment] 2018-04-06 19:49
I see! Shall we flip comment_count to ==0 then?

**Comment by Gauravano** [comment] 2018-04-06 20:03
we can change the status of all comments to 1 so that it matches node status pattern. By #2373 , I could only introduce the default field with comment status, but I guess for changing the status of all comments(old ones) migration need to be run on the production as I have stated here https://github.com/publiclab/plots2/pull/2373#discussion_r170422216.

**Comment by jywarren** [comment] 2018-04-09 15:10
I believe as in #2373 we already have, as you pointed out -- the migration has been run already. But maybe there was a problem -- i see there are ~613 comments in the db with status = 0, starting with:

```
"#<Comment cid: 18529, pid: 0, nid: 15584, uid: 516343, subject: \"\", comment: \"Hi @mridulnagpal , i have this doubt that this fea...\", hostname: \"\", timestamp: 1519158889, status: 0, format: 1, thread: \"0b/\", name: nil, mail: nil, homepage: nil, aid: 0>"
```

and ending with:

```
"#<Comment cid: 19325, pid: 0, nid: 12337, uid: 451808, subject: \"\", comment: \"Hey @matthew! I am trying to build same PPM kit yo...\", hostname: \"\", timestamp: 1523272549, status: 0, format: 1, thread: \"02/\", name: nil, mail: nil, homepage: nil, aid: 0>"
```

The first was 2018-02-20 and the last was today: 2018-04-09

So are we somehow not setting comment status for newly created comments properly? 

Aha! We typically use `node.add_comment` -- a helper method, maybe we should deprecate this, but -- it still sets zero status:

https://github.com/publiclab/plots2/blob/2f35d8734139a35b524af0c29305122b19bcbffb/app/models/node.rb#L569-L581

I can manually change all comments to status = 1 again with `Comment.update_all ["status = ?", 1]` -- shall I?

**Comment by Gauravano** [comment] 2018-04-09 16:10
thanks, @jywarren for pointing out the model `node.rb` ,  we can just change `node.rb` to set status as 1 and then you can run query manually to change the status of all comments. Also, as this issue comes out, I would see if in our codebase we are using query with status = 0 anywhere else. How does it sound?

**Comment by cesswairimu** [comment] 2020-10-08 20:41
The comments count are displayed correctly on the profile page currently and the link also works. Closing this. Thanks everyone

**Closed by cesswairimu** 2020-10-08 20:41 UTC
Labels: bug, fto-candidate, help wanted
