### ISSUE TITLE
Sign-up Form Validation message correction

### ISSUE THREAD

**Issue by gauravano** [publiclab/plots2#3340] opened 2018-09-16 20:38 UTC
**We are preparing to participate in Google Code-in, and have reserved this issue for participants in GCI - but we'd love to have your help with another one! Please check out https://code.publiclab.org to see more.**

# Problem

When a user tries to submit an empty sign up form, and also does not check off the recaptcha box, This output is shown: 

![image](https://user-images.githubusercontent.com/41092741/64667642-7b10f500-d428-11e9-8273-fe91767a290e.png)

# Solution

Instead, we want all the relevant errors ("field cannot be empty" or so) to be listed along with the failed recaptcha verification. 

Each box in this problem is worth some points. We will accept answers that complete one part and not the other, but encourage you to go for all 3. Completion of all three will result in bonus points :)

- [ ] fix the `create` action so that the correct errors show
- [ ] fix the error messages themselves as well. If you see below, there are three different errors for email, but only one of them is correct. 
- [ ] write a test reflecting this fix. Guidelines: the test must fail without your changes, and your changes are what makes it pass.

![image](https://user-images.githubusercontent.com/41092741/64667496-faea8f80-d427-11e9-85b9-725f1c9cb19d.png)

**Comment by gauravano** [comment] 2018-10-22 21:08
Hi, this issue has been opened as a task on GCI dashboard. If you are Google Code-In participant and want to solve this issue, please claim it from Google Code-In [website](https://codein.withgoogle.com/organizations/public-lab/) . Thanks!

**Comment by gauravano** [comment] 2018-10-22 21:08
@SidharthBansal, publish this one. Thanks!

**Comment by SidharthBansal** [comment] 2018-10-22 21:14
This task is published on GCI dashboard. Thanks all.

**Comment by venkateshdb** [comment] 2018-10-25 15:39
Hi there,
I would like to work on this issue.

**Comment by generationXcode** [comment] 2018-10-28 07:58
can I try?

**Comment by venkateshdb** [comment] 2018-10-28 08:20
Yes, I was working on it but , i got lots of problems while installing plot2 on my windows system.
If you could pls tell me.

**Comment by avsingh999** [comment] 2018-10-28 08:36
hi @venkateshdb if you face any problem then you can ask your problem in publiclab gitter channel https://gitter.im/publiclab/publiclab,
post a screenshot which error you are getting
thank you :smile:

**Comment by venkateshdb** [comment] 2018-10-28 16:09
![therubyracer_error](https://user-images.githubusercontent.com/24228920/47618454-35da2200-daf9-11e8-9de0-9269e498cbc4.png)

At first I was getting error while installing libv8 gem but with the help from @gauravano  , I managed to install it but after that , This was the error I was getting while installing therubyracer gem.

**Comment by raddhika** [comment] 2018-11-04 11:38
not able to reproduce the exact copy of the origin
the "reCAPTCHA verification failed, please try again" won't load
also, sign up with google,twitter, etc. wont show up
<img width="599" alt="screen shot 2018-11-04 at 5 07 32 pm" src="https://user-images.githubusercontent.com/44643389/47963588-35d7a600-e054-11e8-8227-8b4ed5e86f72.png">
<img width="640" alt="screen shot 2018-11-04 at 5 07 48 pm" src="https://user-images.githubusercontent.com/44643389/47963590-3c661d80-e054-11e8-88ee-5b0b76b639b7.png">

**Comment by raddhika** [comment] 2018-11-04 11:39
here is what i am able to see
<img width="808" alt="screen shot 2018-11-04 at 5 09 08 pm" src="https://user-images.githubusercontent.com/44643389/47963601-68819e80-e054-11e8-84e2-a877a5b53e70.png">

**Comment by Paarmita** [comment] 2018-11-12 19:01
@venkateshdb You can ask your problems on the gitter providing the screenshots there. And this issue has been resolved so you can take some other GCI tasks. Thanks :)

**Comment by oorjitchowdhary** [comment] 2018-12-10 11:19
@publiclab/reviewers Is this issue solved?

**Comment by SidharthBansal** [comment] 2018-12-10 12:51
No.

**Comment by SidharthBansal** [comment] 2018-12-10 12:51
Nobody is working on this. If you wish then you can work on this.

**Comment by oorjitchowdhary** [comment] 2018-12-10 14:14
I've an idea for this.. what about changing the fields to required.. The user won't be able to submit unless the field is filled up...

**Comment by SidharthBansal** [comment] 2018-12-10 14:37
Check it at pl.org

**Comment by SidharthBansal** [comment] 2019-01-10 16:52
@Dsxv you can try to debug it. You were looking for some issues to be tackled and finding difficult to find easy ones, so helping you.

**Comment by Dsxv** [comment] 2019-01-10 18:00
@SidharthBansal Thanks for Help !  How about we disable the submit button until the mandatory fields are completed ?

**Comment by SidharthBansal** [comment] 2019-01-10 18:02
Good idea. Go for it.

**Comment by SidharthBansal** [comment] 2019-01-14 08:21
@Dsxv how is it going here?

**Comment by SidharthBansal** [comment] 2019-01-14 18:48
@Dsxv I am really sorry. Actually we want all the errors to be produced on the pl.org. @Dsxv you can work on that also if you want.

**Comment by ananyaarun** [comment] 2019-03-16 09:57
@gauravano , i recently worked on login form validation can i work on this ? Adding a required field to this will ensure a null form is not submitted .

**Comment by gauravano** [comment] 2019-03-16 11:29
Go ahead @ananyaarun! Thanks :+1:

**Comment by SidharthBansal** [comment] 2019-03-17 04:39
Yeah sure

**Comment by SidharthBansal** [comment] 2019-09-13 08:24
Sasha it will be great if you can open up a new issue and close this one.
We don't want misunderstanding for Gci candidates.

**Comment by sashadev-sky** [comment] 2019-09-15 18:17
Ok if we want to keep it can either you or @gauravano please re-open with code links :)

**Comment by SidharthBansal** [comment] 2019-09-16 16:27
Moved to #6303 
@sashadev-sky it will be great if you use `hide` feature instead of `delete` feature.
Thanks for help!

**Closed** 2019-11-27 18:01 UTC
Labels: add-code-links, gci-candidate, reserved-for-gci
