### ISSUE TITLE
There is no save button on edit profile page if you once save wrong  

### ISSUE THREAD

**Issue by vishalka98** [publiclab/plots2#3523] opened 2018-09-28 10:36 UTC
### Please describe the problem (or idea)
There is no button on edit profile page if you save wrong format email or password and confirm-password not match.You can't go back or forward and can't change anythong at that time.
> What happened just before the problem occurred? Or what problem could this idea solve?

> What did you expect to see that you didn't?
![screenshot 7](https://user-images.githubusercontent.com/31175911/46203721-4c456000-c338-11e8-804b-ec559ece575a.png)

I want a button on profile edit page ,because if once we save wrong email or password then we can change email and password at same time.

### Please show us where to look

https://publiclab.org/profile/edit

### What's your PublicLab.org username?
caiptanamerica234
> This can help us diagnose the issue: 

### Browser, version, and operating system
windows 10-chrome

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by SidharthBansal** [comment] 2018-09-30 09:12
I can't understand the issue. Can anyone please explain me?
The save button did not appear because the web page was not loaded fully, I personally think so.

**Comment by 14Richa** [comment] 2018-09-30 09:40
@SidharthBansal I think what @vishalka98 means is that when you save some wrong information (example your email address is not valid) then the page shows an error but there is no edit button which you can click and go back to filling the right information. 
![desktop_issuepubliclab](https://user-images.githubusercontent.com/41283476/46256047-e2a58d00-c4c2-11e8-9d02-29a97fb3ea0b.png)

I guess the fix would be simple one to give an edit button on this page. 
Shall I work on this since it has not been assigned to anyone? Thanks :)

**Comment by SidharthBansal** [comment] 2018-09-30 10:02
I assigned an issue to you right now.
Let's take @jywarren input in this. According to me, we don't need to do anything here.

**Comment by avsingh999** [comment] 2018-09-30 11:32
@vishalka98  @SidharthBansal  this is work properly in local machine,

**Comment by Souravirus** [comment] 2018-10-01 19:31
Yeah, @vishalka98 is right there is no save button after entering an invalid email address. So, for that, we have to press the back button of the browser button which is not the optimal way.

**Comment by jywarren** [comment] 2018-10-01 20:54
It does seem like there is an issue. Perhaps documenting it in a gif would
help to narrowly highlight the specific problem?

https://github.com/publiclab/plots2/issues/3513

**Comment by Souravirus** [comment] 2018-10-03 22:48
@jywarren here is the GIF, I have made about the problem,
![editprofile](https://user-images.githubusercontent.com/17192149/46443760-7eb5e980-c78c-11e8-8268-3fb6d0e8178b.gif)

**Comment by 14Richa** [comment] 2018-10-08 09:44
Sent a PR https://github.com/publiclab/plots2/pull/3645

**Comment by sagarpreet-chadha** [comment] 2018-10-12 06:04
Hi @14Richa ...your solution looks valid and seems to solve the issue 😄  .
But i guess as pointed out by @Souravirus , it would be more easy from user point of perspective to make the edits on that same page and not go to previous page .

What do you think ?

Thank you 🎈 !

**Comment by msrdinesh** [comment] 2019-12-10 13:13
Hii is this issue open? if so, I would like to work on this.

**Comment by SidharthBansal** [comment] 2019-12-10 16:19
I hope so. Go for it if it is not solved yet!
Thanks

**Comment by sakshi-2412** [comment] 2021-12-23 14:57
Is this issue still open? I am not able to reproduce this error, I think it has been resolved already 🤔

**Comment by sakshi-2412** [comment] 2021-12-26 15:52
@TildaDares can you please confirm, thanks!

**Comment by TildaDares** [comment] 2021-12-26 19:01
Hi @sakshi-2412, yes this has been resolved. Thanks for informing me!

**Closed** 2021-12-26 19:01 UTC
Labels: bug, help wanted, fto-candidate, add-code-links
