### ISSUE TITLE
The toolbox under the textarea goes out of the screen on Mobile

### ISSUE THREAD

**Issue by urvashigupta7** [publiclab/plots2#7626] opened 2020-03-11 08:58 UTC
![Screenshot_20200311_142503_com android chrome](https://user-images.githubusercontent.com/41363633/76399215-43b5dd80-63a4-11ea-952c-2e690a8cfbbe.jpg)

### Where to see?
https://publiclab.org/post

**Comment by urvashigupta7** [comment] 2020-03-11 09:02
I also think that this toolbar needs to be fixed while scrolling. There is no point in making this toolbar movable with scroll as it is intended to be used only for the purpose of content related to textarea.

**Comment by urvashigupta7** [comment] 2020-03-11 09:06
@cesswairimu Please take a look at it.

**Comment by urvashigupta7** [comment] 2020-03-12 12:49
@publiclab/reviewers

**Comment by VladimirMikulic** [comment] 2020-03-12 13:14
Duplicate of #7067

**Closed by VladimirMikulic** 2020-03-12 13:14 UTC
Labels: bug
