### ISSUE TITLE
Markdown button disables on using keyboard shortcut

### ISSUE THREAD

**Issue by sssash18** [publiclab/plots2#7238] opened 2020-01-14 15:34 UTC
### Please describe the problem (or idea)

> What happened just before the problem occurred? Or what problem could this idea solve?
The markdown button in create note disables after using keyboard shortcut
**Before using keyboard shortcut 'cmd+m'**
![Screenshot 2020-01-14 at 8 59 17 PM](https://user-images.githubusercontent.com/57896905/72357625-492ed880-3711-11ea-93f1-0d8440ea6ce5.png)
**After using shortcut**
![Screenshot 2020-01-14 at 8 59 24 PM](https://user-images.githubusercontent.com/57896905/72357652-564bc780-3711-11ea-931d-215590c9b708.png)

> What did you expect to see that you didn't?
It must still be functioning.

### Please show us where to look

https://publiclab.org/ ...

### What's your PublicLab.org username?

> This can help us diagnose the issue: 

### Browser, version, and operating system

> Many bugs are related to these -- please help us track it down and reproduce what you're seeing!

****

## Thank you!

Your help makes Public Lab better! We *deeply* appreciate your helping refine and improve this site. 

To learn how to write really great issues, which increases the chances they'll be resolved, see:

https://publiclab.org/wiki/developers#Contributing+for+non-coders

**Comment by sssash18** [comment] 2020-01-14 15:35
@publiclab/reviewers Kindly provide your views on this?

**Comment by nstjean** [comment] 2020-01-15 18:09
Interesting! I took a look at it and it looks like it's trying to switch to markdown mode, but it's not changing the button to the "rich" button.

For example, here's what I had before pushing any buttons:

![FireShot Capture 216 - 🎈 Public Lab_ Post - stable publiclab org](https://user-images.githubusercontent.com/49460529/72459075-fa785180-3797-11ea-90ec-98be6c6ce692.png)

When I push the markdown button it switches to markdown mode and displays the "rich" button:
![FireShot Capture 217 - 🎈 Public Lab_ Post - stable publiclab org](https://user-images.githubusercontent.com/49460529/72459105-095f0400-3798-11ea-9008-51e843bc9f99.png)

But if I instead push ctrl-M it shows me markdown, a disabled button and no toolbar:
![FireShot Capture 218 - 🎈 Public Lab_ Post - stable publiclab org](https://user-images.githubusercontent.com/49460529/72459125-167bf300-3798-11ea-8e57-1aadd7798dbe.png)

I think we'll have to look at why a keypress is triggering something. Maybe we should just turn off the keyboard shortcut for that page, whatever it is.

**Comment by sssash18** [comment] 2020-01-16 10:07
@nstjean So how do we proceed with this?

**Comment by nstjean** [comment] 2020-01-16 14:00
I would first try to figure out why a keyboard shortcut is triggering something. There has to be code somewhere that is causing that, we'll have to hunt it down.

**Comment by keshavsethi** [comment] 2020-01-16 20:45
@nstjean This is due to the following function 
![Screenshot from 2020-01-17 02-11-22](https://user-images.githubusercontent.com/36025262/72561356-0adf1800-38cf-11ea-9d54-cb01d1813a8d.png)
This is from PublicLab.Editor.js

**Comment by keshavsethi** [comment] 2020-01-16 20:47
If we press cmd+m then markdown is disabled but after that if we press cmd+p or cmd+h it moves back to respective modes.

**Comment by nstjean** [comment] 2020-01-16 21:05
Ok great! So the problem is that when it enters markdown mode it's not
changing the button over. We need to find out why pushing the button does
one thing and entering markdown mode by ctrl-M has a different result. Both
should do the same thing.

**Comment by VladimirMikulic** [comment] 2020-01-17 22:44
This has been fixed, as well as scroll to the top, image modal errors...
@jywarren needs to publish a new version so we have that changes on pl.org/post.

Please close this issue.

**Comment by jywarren** [comment] 2020-01-18 03:23
@VladimirMikulic can you link to the relevant issues so there's a history here? then we can close it! Thanks!

**Comment by VladimirMikulic** [comment] 2020-01-18 15:27
The issue: https://github.com/publiclab/PublicLab.Editor/issues/341

The PR for it: https://github.com/publiclab/PublicLab.Editor/pull/383

**Comment by SidharthBansal** [comment] 2020-01-18 15:33
Feel free to reopen it if needed

**Closed by SidharthBansal** 2020-01-18 15:33 UTC
Labels: bug
